import argparse, copy, functools, http.server, json, sys, threading, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
parser=argparse.ArgumentParser(); parser.add_argument('--task-dir',type=Path,required=True); parser.add_argument('--site-dir',type=Path); args=parser.parse_args(); task=args.task_dir; shots=task/'screenshots'; shots.mkdir(exist_ok=True)
raw=json.load(urllib.request.urlopen('https://live.wly0829.cn/computer-access/state',timeout=20)); data={k:raw[k] for k in ('host','cockpit','automation','observed_at_unix','served_at_unix','display_cache') if k in raw}; data['hardware']={'health':raw['hardware']['health']}
history=json.loads((task/'validation/real-history-replay/health-history.json').read_text('utf8')); latest=history['points'][-1]; health=data['hardware']['health']['pc_health']; health['trend_points']=[p for p in history['points'] if p['boot']==latest['boot'] and latest['t']-90000<=p['t']<=latest['t']]; health['recording_started_at_unix']=history['continuity']['began']
(task/'qa-status.json').write_text(json.dumps({'candidate_fields_replay_not_deployed':True,**data}),encoding='utf8'); checks={}; errors=[]; state={'data':data}
class Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args): pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(args.site_dir or task/'preview-qa-final'))); threading.Thread(target=server.serve_forever,daemon=True).start()
with sync_playwright() as playwright:
    browser=playwright.chromium.launch_persistent_context(str(task/'chrome-qa'),executable_path=r'C:\Program Files\Google\Chrome\Application\chrome.exe',headless=True); page=browser.new_page(); page.on('pageerror',lambda error:errors.append(str(error)))
    page.route('**/__status',lambda route:route.abort() if state['data'] is None else route.fulfill(json=state['data'])); page.add_init_script("Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__copied=text}}})")
    def load(row):
        state['data']=row; page.goto(f'http://127.0.0.1:{server.server_port}/cockpit/stutter/'); page.wait_for_function("!document.getElementById('headline').textContent.includes('正在连接')")
    for width,height in [(1440,1000),(390,844)]:
        page.set_viewport_size({'width':width,'height':height}); load(data); page.locator('#trend-note').evaluate("node=>node.append('（候选字段回放，未部署）')"); checks[f'overflow_{width}']=page.evaluate('document.documentElement.scrollWidth<=innerWidth'); page.screenshot(path=str(shots/f'stutter-{width}.png'),full_page=True)
    checks['real_unknown_preserved']=page.locator('.hero').get_attribute('data-state')=='unknown' and '不知道' in page.locator('#headline').inner_text(); checks['gap_not_joined']=page.locator('svg .curve').get_attribute('d').count('M')>=2; checks['missing_count_not_zero']='无卡顿' not in page.locator('body').inner_text()
    warn=copy.deepcopy(data); warn['hardware']['health']['pc_health'].update(state='warn',reason_code='resource_high'); warn['cockpit']['know']=[{'id':'pc-health','title':'电脑健康','severity':'yellow','current':True,'ai_hint':{'logs':'QA_LOG_BODY_MUST_NOT_COPY'}}]; load(warn); page.locator('#copy-one').click(); text=page.evaluate('window.__copied'); checks['copy_id_local_address_no_logs']='id=pc-health' in text and 'http://127.0.0.1:18793/computer-access/api/status' in text and 'QA_LOG_BODY_MUST_NOT_COPY' not in text
    normal=copy.deepcopy(warn); normal['hardware']['health']['pc_health'].update(state='ok',trend_state='ok',reason_code='ok'); normal['cockpit'].update(know=[],need_you=[],cards=[{'id':'computer_health'}]); load(normal); checks['normal_copy_all_gray_disabled']=page.locator('#copy-all').is_disabled() and page.locator('#copy-all').inner_text()=='现在没有要交给 AI 的事' and page.locator('#copy-all').evaluate(r"node=>{let c=getComputedStyle(node).backgroundColor.match(/\d+/g).map(Number);return Math.max(...c)-Math.min(...c)<30}"); checks['normal_issue_hidden_felt_kept']=page.locator('#copy-one').is_hidden() and page.locator('#copy-block').is_hidden() and page.locator('#copy-felt').is_visible(); page.screenshot(path=str(shots/'normal-390.png'),full_page=True)
    stale=copy.deepcopy(normal); stale['hardware']['health']['pc_health']['observed_at_unix']-=1000; load(stale); checks['stale_sample_unknown']=page.locator('.hero').get_attribute('data-state')=='unknown'; old=copy.deepcopy(normal); old['display_cache']['collectors']['hardware'].update(state='stale',observed_at_unix=health['observed_at_unix']-1000); load(old); checks['stale_source_unknown']=page.locator('.hero').get_attribute('data-state')=='unknown'; page.screenshot(path=str(shots/'stale-source-390.png'),full_page=True)
    page.evaluate("()=>{navigator.clipboard.writeText=async()=>{throw Error('QA clipboard rejected')}}"); page.locator('#copy-felt').click(); checks['clipboard_failure_manual']=page.locator('#copy-manual').is_visible() and 'http://127.0.0.1:18793/computer-access/api/status' in page.locator('#copy-manual').input_value()
    checks['felt_missing_hint_fallback']='还没有 ai_hint' in page.locator('#copy-manual').input_value() and 'id=computer_health' in page.locator('#copy-manual').input_value()
    load(None); checks['read_failure_unknown']=page.locator('.hero').get_attribute('data-state')=='unknown'; checks['no_js_errors']=not errors; browser.close()
server.shutdown(); report={'checks':checks,'errors':errors,'screenshots':str(shots),'candidate_fields_replay_not_deployed':True}; (task/'stutter-qa.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8'); print(json.dumps(report,ensure_ascii=False)); sys.exit(0 if all(checks.values()) else 1)
