import { generatedPanelFacts } from "./panel-facts.generated.js";

const currentERules = generatedPanelFacts.authority;

function skill(definition) {
  return {
    provenance: "个人维护的能力入口",
    sourceKind: "personal_install",
    availability: "available",
    statusTone: "mixed",
    sourceState: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 中的唯一源码已核对`,
    installState: "canonical junction 已安装",
    transactionState: `${generatedPanelFacts.skills.transactionCampaignCount} 个供应事务全部终态；0 个坏事务`,
    currentTaskState: "本轮宿主回执未知",
    freshTaskState: "新任务回执未知",
    endToEndState: "按场景验收",
    evidenceObservedAt: `供应链现场：${generatedPanelFacts.observedAt}；项目场景按各项记录`,
    evidenceBasis: `.agents ${currentERules.releaseId} release ${currentERules.gitCommit.slice(0, 7)}、当前 Personal Skill supply（个人能力供应链），以及本页明确标注的既有项目/Provider（固定服务入口）证据；source/install/transaction 通过不冒充 current/fresh/E2E`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    supplyEvidenceCommand: "E:\\.agents\\tools\\Test-PersonalSkillSupply.ps1 -RequireInstalled -NoExternalEvidence -Json",
    ...definition
  };
}

export const skills = [
  skill({
    slug: "personal-media",
    name: "personal-media",
    title: "个人照片、视频与录音检索",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "用自然语言从本机受管媒体目录查找照片、视频和录音，打开原件，或生成一个可随时清理的临时浏览文件夹。",
    useWhen: ["记得画面、地点、文字、录音内容或大致日期，但不知道原件路径", "需要打开少量真实媒体原件", "需要把一组查询结果放进临时文件夹浏览", "需要明确区分图片、视频和音频"],
    avoidWhen: ["查找 Word、PDF 等非媒体原件", "按人物大范围扫描媒体库", "删除、修改或上传媒体", "重建第二套索引、服务或后台任务"],
    inputs: ["1 到 4 个能出现在内容中的区分词", "可选地点、描述、分类、媒体类型和日期", "明确要求完整集合时才使用 all"],
    outputs: ["少量可读候选和绝对原件路径", "媒体类型、已知日期、地点、分类和匹配依据", "按请求创建的同卷 hardlink 浏览目录", "零命中时的真实过滤条件和覆盖缺口"],
    flow: ["把用户原话压缩成最小可靠过滤条件", "用 SQLite 条件和 FTS 执行小结果 search", "核对权威原件定位记录确实指向现存原件", "需要浏览时创建 task-unique hardlink 文件夹", "身份问题只把选中的少量原件交给 person:self 能力", "用户不再需要时只清理那个受管浏览目录"],
    boundaries: ["私密项默认隐藏，只有用户明确要求才包含", "地点只表示已复核的拍摄现场，文字里的地名走 query", "不使用当前没有证据的人物过滤", "不读取完整 NDJSON、全盘扫描或复制媒体进知识库", "浏览清理绝不删除原件"],
    dependencies: ["V:\\Personal\\Projects\\personal-media", "E:\\Media\\_manifests\\personal-media-current\\catalog.sqlite3", "E:\\Pictures、E:\\Videos 与 E:\\Music\\录音 canonical roots"],
    tests: "个人媒体项目当前共 45 项回归，其中 43 项通过、2 项真机项跳过；新回读覆盖全部 1,182 项精选进入手机包与云候选，普通检索和状态不触发同步。Skill 的来源与安装证据另行核对。",
    sourcePath: "E:\\.agents\\skills\\personal-media\\SKILL.md",
    endToEndState: "本地 search、browse 和 clean 契约已验"
  }),
  skill({
    slug: "personal-materials",
    name: "personal-materials",
    title: "非媒体原件定位",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "忘了合同、报告或其他非媒体原件放在哪里时，先给少量最可能的候选；只有我选中一项后才核对真实文件并打开，不全盘乱搜，也不提前暴露路径。",
    useWhen: ["知道材料是什么，但不知道它放在哪里", "一个既有 locator（定位记录）已失效，需要在登记来源内重新发现", "需要在几个已批准位置之间查找同一份非媒体原件"],
    avoidWhen: ["照片、视频、录音或其他视听媒体", "所属业务已经有可靠精确路径", "需要判断材料含义、案件或健康事实，而不是找原件", "要求全盘扫描、后台索引或批量复制原件"],
    inputs: ["对材料名称、时间、版本角色、用途或原生目录的普通描述", "可选的已登记来源提示；不要求用户重复系统已经知道的本机路径或内部 ID"],
    outputs: ["find 或 discover 阶段少量不含真实路径的候选卡", "明确选中后才返回现场核验过的真实路径、字节数、SHA-256 与打开状态", "零命中或达到上限时的实际来源范围、文件/目录计数、截止原因和来源缺口"],
    flow: ["所属业务已有可靠 locator 时直接使用原业务入口，跳过本 Skill", "先用 find 查询已登记的非媒体定位和绑定文字", "登记候选明确时选择 material key，再由 open 重新核对当前大小和 SHA-256", "没有合适登记候选且位置确实未知时才用 discover；此阶段只看文件名、原生目录名和 stat（文件状态），不读正文、不算哈希", "选择一个 discovery token（发现候选令牌）后调用 open-discovered，核对来源根、路径边界和文件状态，计算这一份原件的 SHA-256，再登记并按请求打开", "没有命中时只报告本次覆盖与缺口，不推断其他设备、账号或未登记位置"],
    boundaries: ["照片、视频、录音及其他视听媒体始终交给 personal-media", "候选 token、material key 和内部来源 ID 不进入面向用户的回答", "项目只保存最小 locator/metadata SQLite（定位与元数据数据库）及与原件绑定、可删除重建的文字，不保存原件字节、人物事件或跨领域画像", "discover 最多选择 8 个来源，全部来源共享 2500 个文件和总计 8 秒的预算，每来源最多 12 层，并且不跟随链接", "不复制、移动、改写或删除原件；hash 漂移、来源根变化或文件状态变化都失败关闭"],
    dependencies: ["个人材料查找项目（私有源码）", "personal-materials.handoff.v1 与项目最小 locator/metadata SQLite（定位与元数据数据库）"],
    tests: "40 项回归全部通过（29.20 秒）；Ruff 静态检查通过；显式 inventory 只读盘点来源规模，默认 status 仍保持快速。",
    sourcePath: "E:\\.agents\\skills\\personal-materials\\SKILL.md",
    endToEndState: "项目源码与合成 fixture（测试样本）回归；本次网页刷新未读取私人原件、真实来源根或默认应用现场"
  }),
  skill({
    slug: "wechat-direct",
    name: "wechat-direct",
    title: "微信上下文与具名归档",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "读取一段微信对话及回复关系，核对图片、语音、视频和文件属于哪条消息，或维护一个明确联系人或群的可重放本地归档；当前真正能打开字节的媒体主要是精确语音。",
    useWhen: ["回答一个聊天中的上下文问题", "读取某个具名联系人或群的历史", "核对聊天媒体关系或打开精确语音", "读取当前已缓存的朋友圈内容"],
    avoidWhen: ["一次同步整个账号", "后台持续同步", "没有明确联系人或范围", "把聊天材料复制到第二数据库"],
    inputs: ["联系人或群名", "账号、时间范围或消息线索", "归档时的单一具名目标"],
    outputs: ["按原生顺序排列的小范围上下文", "消息回复关系、全部媒体关系与当前可打开语音", "单一目标的增量归档或朋友圈缓存结果"],
    flow: ["读取项目当前入口说明", "聊天问题走 context", "完整具名历史走 sync-contact", "精确语音走 media-open", "朋友圈走 moments 或 sync-moments"],
    boundaries: ["一次只处理一个具名联系人或群", "不做全账号后台任务", "图片、视频、表情和文件当前只保留关系与缺口", "硬崩溃半成品不冒充可自动续跑", "缓存 miss 不冒充无数据", "语音转写交给中文 ASR"],
    dependencies: ["E:\\Projects\\Tools\\WeChatDirect", "中文 ASR 用于语音媒体"],
    tests: "50 项测试与 2 个子测试通过，覆盖账号身份、原生顺序、回复、媒体关系、语音、增量归档、朋友圈缓存、快速路径完整性、来源漂移和导出验真。",
    sourcePath: "E:\\.agents\\skills\\wechat-direct\\SKILL.md",
    endToEndState: "源码回归与无正文 Doctor 已验；本轮未读取真实具名聊天"
  }),
  skill({
    slug: "google-workspace-direct",
    name: "google-workspace-direct",
    title: "Google Workspace 固定入口",
    status: "已安装 / 固定 Google Workspace 服务入口已配置",
    maturity: "A-",
    summary: "需要查自己的 Gmail、Google Drive 或日历时，它固定使用已经登记的同一个账号读取；只有系统确实提供对应写入能力、而且用户明确要求时，才会修改外部内容。",
    useWhen: ["按条件查邮件", "查找或导出 Drive 文件", "读取日历事件", "需要原生 Google Docs 导出"],
    avoidWhen: ["切换其他账号", "静默改走浏览器、公共 Connector 或 rclone", "Provider 没有暴露目标写操作", "Google Photos、Admin 或支付"],
    inputs: ["窄查询、对象 ID 或时间范围", "写操作时的精确对象、内容和动作授权"],
    outputs: ["最小必要邮件、文件或日历结果", "原生文档导出", "写操作的 Provider 回执与 read-back"],
    flow: ["选择固定 Provider 的精确 operation", "默认执行只读", "原生文档必须走 Drive export", "写入前核对 Provider 能力和授权", "按同一 Provider read-back"],
    boundaries: ["不落中央库", "不自动同步", "不换账号或第二 Provider", "删除、发送、邀请和公开分享需要精确授权"],
    dependencies: ["PCConfig 的 google-workspace.primary Provider", "已登记 OAuth 绑定"],
    tests: "Provider binding、action 和 install 三组测试通过；本次未重新验证在线账号身份。",
    sourcePath: "E:\\.agents\\skills\\google-workspace-direct\\SKILL.md",
    endToEndState: "在线身份本轮未复核"
  }),
  skill({
    slug: "chinese-asr",
    name: "chinese-asr",
    title: "中文录音转写与说话人证据",
    status: "已安装 / 正式环境回归通过",
    maturity: "A",
    summary: "把中文和微信录音转成可搜索文字；需要时再选择带时间位置、匿名说话人或本人声音线索的模式。普通录音默认留在本机，重要录音只有本次明确允许才进入云端交叉验证。",
    useWhen: ["需要中文录音全文，或明确选择带时间位置的模式", "需要区分匿名说话人 cluster", "需要判断精确句段是否支持 person:self", "重要专业录音需要双链验收"],
    avoidWhen: ["扫描整个音频库", "把 cluster 数直接当真实人数", "把 ASR 当逐字法律证书", "timeout 后盲目重新提交同一 job"],
    inputs: ["一个具名音频或视频音轨", "模式、时间范围和必要的说话人证据边界", "云路线需要明确双开关授权"],
    outputs: ["转写文本；所选模式支持时附时间戳，需要时附匿名 cluster", "objective sidecar 与 job 状态", "本人归属的精确句段、覆盖范围和不确定性"],
    flow: ["普通录音走 strict", "长录音走 long-strict", "说话人先聚类再对精确句段做 held-out attribution", "重要录音按授权进入唯一云路线", "以原音频为权威复核结果"],
    boundaries: ["原音频始终高于转写", "云失败不能伪装成本地成功", "其他说话人保持匿名", "空文本和超时不能自动解释为没有内容"],
    dependencies: ["E:\\Projects\\Tools\\ChineseASR", "模型 registry", "LocalGpuBroker", "本地私有 person:self profile"],
    tests: "2026-08-31 项目正式 Python 3.11 venv 的当前全量回归为 345 tests OK，关键 15 项定向验证全部通过，doctor 也确认 Qwen、FunASR 与 PyTorch 已安装。",
    sourcePath: "E:\\.agents\\skills\\chinese-asr\\SKILL.md",
    endToEndState: "正式 venv 与主要模型链已验"
  }),
  skill({
    slug: "timeaudit-diagnostics",
    name: "timeaudit-diagnostics",
    title: "TimeAudit 有界历史诊断",
    status: "已安装 / 12 项 provider 合同测试与一小时真实查询通过",
    statusTone: "pass",
    maturity: "A",
    summary: "当电脑的卡顿、发热、磁盘/网络、掉帧、睡眠或采集断档需要历史证据时，用一次有界聚合查询回答“这段时间实际覆盖了什么、出现了哪些相关信号、还缺什么”；它不是 TimeAudit 控制器，也不会把相关性冒充根因。",
    useWhen: ["间歇性电脑问题已经过去，需要回看 1 到 168 小时内的历史", "需要先区分没有异常、没有游戏帧和根本没采到数据", "硬件、FPS、睡眠或采集覆盖会改变当前诊断结论", "需要把历史聚合与 Windows、驱动、任务或 PCConfig 现场证据对齐"],
    avoidWhen: ["只需要此刻的实时状态", "想控制、启动、停止或修复 TimeAudit", "需要逐进程或逐窗口明细而当前 aggregate-only 接口不能回答", "试图用一次阈值信号证明硬件损坏、恶意程序或用户意图", "把超过 168 小时拆成大量窗口暴力查询"],
    inputs: ["具体电脑问题与尽可能窄的时间范围", "最近事件可用 1–168 小时，具名事件使用精确 UTC 起止", "需要关联的 Windows、驱动、任务或 PCConfig 现场证据"],
    outputs: ["请求窗口、覆盖新鲜度、样本数、边界/内部最大空档", "CPU/GPU、内存、磁盘、网络与有效游戏帧的聚合摘要", "active/idle/display-off/lock/sleep 的区间并集时长和未覆盖时间", "阈值 occurrence（出现次数）、因果限制、真实缺口与下一项安全诊断动作"],
    flow: ["选择能改变判断的最短时间窗", "调用固定 `timeaudit_diagnostic_summary.py` 一次", "验证 schema、owner、status、窗口、coverage、样本和输出省略标志", "只有 game_performance.status=observed 时解释 FPS/1% Low/frametime", "把信号与实时状态和其他 Owner 证据关联", "先给实用结论，再说明窗口、关键聚合、缺口和下一步"],
    boundaries: ["TimeAudit 只是可选历史证据，不单独证明根因", "单次窗口最多 168 小时，不网格化暴力查询", "provider 为速度与语义稳定只返回聚合；进程、路径、标题等字段类别并非天然敏感，可由其他合适路线在有价值时使用", "不调用 Grafana、db_audit、PCConfig cursor 或采集控制入口", "provider unavailable/stale/empty 时回到普通诊断，不把缺数据写成健康"],
    dependencies: ["E:\\Projects\\Tools\\TimeAudit\\timeaudit_diagnostic_summary.py", "TimeAudit 本机 PostgreSQL 容器", "E:\\Projects\\Tools\\TimeAudit\\TIMEAUDIT_DIAGNOSTIC_SUMMARY_CONTRACT.md"],
    tests: "TimeAudit main 44a842e 的 diagnostic summary provider 合同与测试仍在当前源码；本轮 `--hours 1` 真实查询返回 schema timeaudit.diagnostic-summary.v1、status=ok、coverage=fresh、3702 个样本，最新样本年龄约 0.77 秒，8 个 privacy flag 均为 false。",
    sourcePath: "E:\\.agents\\skills\\timeaudit-diagnostics\\SKILL.md",
    sourceState: `Skill 初始实现来自 d719dea；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与 source/install 供应验证分别回读通过`,
    currentTaskState: "本轮一小时真实 provider 查询通过，未控制或重启任何 TimeAudit 组件",
    freshTaskState: "来源 Owner 的 projectless 任务已发布并回读 Skill 与 provider",
    evidenceObservedAt: `当前 Skill 来源/安装供应回读：${generatedPanelFacts.observedAt}；一小时真实查询现场：2026-08-31 12:13（中国时间）`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 中可发现的 TimeAudit diagnostics Skill、TimeAudit PUBLIC main 44a842e 的 provider/contract/tests，以及既有一小时真实聚合查询；源码、安装、provider 现场与因果结论保持分层。`,
    endToEndState: "固定 Skill → 有界 provider → schema/coverage/聚合解释的真实一小时路径已验"
  }),
  skill({
    slug: "localocr",
    name: "localocr",
    title: "图像理解与精确 OCR 分工",
    status: "已安装 / 三条自然请求验收已通过",
    maturity: "A",
    summary: "处理图片时先看用户真正要什么：只描述场景就用原生视觉；要逐字、坐标、表格或本地处理就用 LocalOCR；既要看画面又要抄文字时，两条路线独立取证并分开呈现。",
    useWhen: ["准确抄写图片里的小字、浅色字或关键数字", "扫描 PDF、多页图片、表格、公式、印章、版面或坐标", "既要描述场景又要准确复制文字", "源像素必须留在本机处理"],
    avoidWhen: ["只需要描述普通照片里的场景、物体、活动、颜色或纹理", "把原生视觉当逐字正确证明", "把 OCR 当场景描述模型", "把空文本直接理解成没有文字", "timeout 后重复创建同一 job"],
    inputs: ["一张或多张图片、PDF 或明确文件夹", "想要的结果：场景描述、精确文字或两者", "是否要求全部本地处理，以及可选 engine、版面模式和输出格式"],
    outputs: ["场景请求的原生视觉观察", "精确 OCR 文字、坐标、置信度、表格和版面结构", "API、TXT、Markdown 与 JSON 中确定性的 display_summary（人话状态摘要）", "分开的视觉观察、精确文字、识别状态、不确定与冲突"],
    flow: ["先按请求结果选择原生视觉、LocalOCR 或两路", "只看场景时直接检查原图，不启动 LocalOCR", "精确文字与结构请求走本机 OCR", "混合请求让两条路线独立读取同一原图", "按视觉观察、精确文字、识别状态和冲突合并答案", "复用返回的 job 和 output，区分 deadline、broker、配置和识别失败"],
    boundaries: ["原生视觉负责场景理解，不是逐字正确证明", "LocalOCR 负责精确文字证据，不是场景描述模型", "两路冲突时保留分歧并复核原图区域，不静默覆盖", "明确要求全部本地时不把源像素交给原生视觉", "display_summary 只投影客观状态，不替代原始 OCR 或 objective sidecar", "不把 timeout 124 当 OCR 失败，不把空文本当否定结论", "GPU 重载必须串行"],
    dependencies: ["E:\\Projects\\Tools\\LocalOCR", "WSL Python", "PaddleOCR", "LocalGpuBroker"],
    tests: ".agents 31278a0 的 autonomy 回归覆盖混合触发、三路选择与证据分离；来源 Owner 的实现盲自然请求验收已分别通过只看场景、精确抄字、场景加精确文字三条路径。LocalOCR acc6d15 为 display_summary 的客观投影、多格式输出和缓存版本增加回归；此前 18,980 字节小图 auto→ocr、objective 与 job sidecar 的真实验收仍是历史运行证据，本次网站刷新没有重跑源像素。",
    sourcePath: "E:\\.agents\\skills\\localocr\\SKILL.md",
    currentTaskState: "本轮网站任务只核对来源提交、供应状态和公开展示，没有处理新的图片或启动 OCR 模型",
    freshTaskState: "来源 Owner 已用实现盲自然请求分别验收场景只走视觉、精确文字走 OCR、混合请求分离两类证据",
    evidenceObservedAt: "Skill 供应、.agents 与 LocalOCR 远端 main 回读：2026-09-02 12:17（中国时间）",
    evidenceBasis: ".agents source 31278a0 的 LocalOCR Skill、openai.yaml 与自治回归，LocalOCR PUBLIC main acc6d15 的 display_summary 实现/测试，以及来源 Owner 的三条实现盲用户路径；source、install、产品代码、历史真实 OCR 与本轮网站取证保持分层。",
    endToEndState: "场景只用原生视觉、精确文字用 LocalOCR、混合请求分开视觉观察/精确文字/识别状态/冲突的三条用户路径已验"
  }),
  skill({
    slug: "personal-health",
    name: "personal-health",
    title: "个人健康上下文",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "回答本人的健康、用药、过敏、检查、趋势、睡眠和活动问题，并在收到新报告或明确刷新设备数据时更新当前健康事实。",
    useWhen: ["问题取决于本人的当前健康资料", "需要解释新检查报告", "需要刷新已登记健康设备数据", "高风险健康建议需要结合权威医学资料"],
    avoidWhen: ["与本人无关的通用健康问题", "恢复旧中央个人系统", "把模型建议写成医生结论", "建立持续后台同步"],
    inputs: ["健康问题、新报告或明确纠正", "设备刷新时的已登记数据入口"],
    outputs: ["基于 CURRENT 的当前回答", "事实、医生意见、模型建议和未知的明确分层", "经 Health Owner 审核的更新"],
    flow: ["普通问题先读完整 CURRENT", "高风险问题再查权威指导", "新报告走 capture 和 brief", "由 Health Owner 复核后更新", "保持 unknown 和证据日期"],
    boundaries: ["不读旧记忆代替 CURRENT", "不建中央画像", "不自动持续同步", "不把建议和事实混写"],
    dependencies: ["个人健康项目的 CURRENT", "高风险问题的权威医学来源"],
    tests: "2026-08-31 项目当前 112 项合成回归通过；它不代表真实账号或医学 E2E。供应元数据已修复并通过 320 字符预算与 quick validation。",
    sourcePath: "E:\\.agents\\skills\\personal-health\\SKILL.md"
  }),
  skill({
    slug: "daily-preferences",
    name: "daily-preferences",
    title: "日常偏好与个性化推荐",
    status: "Source（源码）、安装、当前状态、全新任务发现与真实推荐 E2E（端到端）均已验收",
    statusTone: "pass",
    maturity: "A-",
    sourceKind: "personal_install",
    summary: "记住我当前明确表达的日常偏好，在吃喝、购物、出行、娱乐、工具和审美选择中给出有理由、能纠正的建议；我刚说的话优先于旧记录，也不会把过去压成固定人格。",
    useWhen: ["用户本人明确说喜欢、不喜欢、以后想怎样选，或表示自己改主意了", "想根据既有偏好获得美食、购物、支付与消费习惯、出行、旅行景点、住宿、娱乐或数字消费推荐", "要在服务选择、工具习惯、审美或其他没有专门领域 Owner 的日常取舍中得到个性化建议", "需要解释一次购买、用餐、支付或服务选择背后的偏好，并允许后续纠正", "用户明确说“准备投递增量”，需要先查看各来源覆盖与缺口"],
    avoidWhen: ["医学饮食、过敏、用药或治疗限制，应以个人健康入口为主", "预算、债务、还款、授信或资产配置，应交给资产领域", "卡号、密码、登录或执行真实付款，应交给本地凭据入口", "合同、私人专业事务文书或其他正式材料，应交给文书和材料制作入口", "对象、朋友或其他人的偏好，不能由用户本人的消费史代替", "PRD、代码、职业、项目或产品设计，不读取私人偏好快照"],
    inputs: ["用户当前直接表达的喜欢、不喜欢、理由、纠正或改变想法", "一个关于吃喝、购物、支付消费、出行旅行、住宿、娱乐、数字消费、服务工具、审美或日常决策的自然问题", "只有用户明确准备投递增量时，才接收其提供的具名来源包"],
    outputs: ["同范围最新明示成为 current（现行偏好）、旧表述保留为 historical（历史偏好）的可纠正记录", "每个开放领域至少 3 个熟悉稳妥、3 个相邻探索和 3 个明确标为推测的新鲜尝试组成的选择菜单；还有显著不同路线时继续列，不用同款变体凑数", "Steam 游戏请求只使用实际玩过的游戏并附当前商店分类；未玩/应用不混入，历史取得方式保持 Unknown", "每个候选的具体内容或规格、适合理由、关键取舍，以及必要的粗略价格、场景或搜索词", "支撑本次排序的最小证据、事实核对、未知和可复制的搜索接力", "增量投递前逐 source instance（来源实例）的实际覆盖截止或快照时间、缺口、原始材料、重叠起点、full/incremental 模式，以及 12 项未接入来源的 availability/evidence；材料到齐后继续闭合偏好语义"],
    flow: ["从 daily-preferences 私有项目根运行相对入口；用户直接表达偏好时执行 `pwsh -NoProfile -File .\\daily-preferences.ps1 record --key <preference-key> --statement <用户原话>`，同范围最新明示成为 current，旧表述只保留为 historical", "普通推荐先读取私有数据根中的 CURRENT 薄快照；快照不存在或过期时继续查最小证据，不把缺快照说成用户没有偏好", "执行 `pwsh -NoProfile -File .\\daily-preferences.ps1 evidence --query <用户自然问题> --limit 24 --json`；开放题按会改变选择的轴补查，不能把一包最高分命中冒充全貌", "Steam 娱乐/数字问题读取按 AppID 合并的统一个人库；只有实际玩过的 game/demo 进入普通游戏 evidence，application 和未玩观察退出，并从公开商店元数据补当前免费/付费分类", "优先保留具体商品、口味、规格或菜品原名；order observation（订单观察）只证明买过或点过，只有成功记录才进入 repeat count（复购计数），退款、关闭、取消或失败订单只保留交易事实并从普通偏好 evidence（证据）和模型上下文排除；跨时间复购和真实 user expression（用户表达）共同支持可推翻推定，payment observation（支付观察）不重复计算已有详细订单", "时间只在来源、语义和状态相当时调整排序；久远有效成功记录和未更正明示不自动过期，低频、长期未买或没有记录只表示证据较弱/Unknown，不能反推不喜欢", "准备把具体商品或品类写成复购偏好、或解释为什么时，运行 `facts --term <品牌或核心词> --term <品类词> --json` 核对成功与非成功状态、时间范围和文本变体；商家模板、赠品、未选选项、替他人询问、假设或单纯疑问都不能升级成用户偏好", "只有冲突、过度概括、索引过期或原件细节会改变候选时，才按 locator（原件定位）有界读取原件；媒体和非媒体原件继续由各自入口保管", "开放式推荐把历史当排序依据而不是白名单；每个开放领域至少给 3 个熟悉稳妥、3 个相邻探索和 3 个标明依据的推测新选项，还有显著不同路线时继续列，不用同款变体凑数；每项用一两句说明具体内容、理由和取舍", "实时平台信息有帮助时只给与本次需求匹配的 1–2 个平台和可复制关键词，不冒充权威最低价，也不替用户下单或付款", "用户说“准备投递增量”时，先从私有项目根运行 `pwsh -NoProfile -File .\\daily-preferences.ps1 status --json`；这一准备步骤零扫描、零导入，不改业务数据或 SQLite 主文件。它逐个 source instance 说明实际覆盖截止，Unknown 时给快照时间，并列缺口、原始材料、重叠起点、full/snapshot/incremental/manual 模式；再单列 12 项未接入逻辑来源及 availability/evidence。用户提供材料后才运行 `ingest`，完整权威快照才用 full，普通补包使用 incremental；接着完成覆盖/缺口回读、偏好新增/增强/减弱/未知判断、相关快照重建和普通自然问题回验，或明确报告语义无变化"],
    boundaries: ["当前同范围明示优先，明确回顾过去并给出日期的旧记录不能覆盖现行偏好", "只保留薄快照和会改变当前选择的最小证据，原件留在各自 Owner，不移动、覆盖或删除", "Steam 四账号按用户明示合为同一人，但仅观察/安装/未玩和应用不进入普通游戏偏好；当前商店分类不证明历史取得方式", "单次订单或付款不自动证明喜欢；退款、关闭、取消或失败订单不进入普通偏好证据、模型上下文或成功复购计数，也不能反推任何偏好", "时间只调整同等证据排序；久远、低频、长期未买或无记录都不自动等于过期/不喜欢", "材料保全或 ingest 成功不等于偏好增量完成，还须闭合覆盖/缺口、语义变化、快照和普通问题回验", "parser 列表不是来源全景；退役 PersonalOS 只作一次性发现线索，不恢复旧系统", "偏好推定必须保留具体依据并允许接受、拒绝和纠正", "不输出星座式人格标签，不建立中央个人画像、向量库、服务、队列、第二状态库或后台同步", "不替代个人健康、预算资产、本地凭据与真实付款、文书和材料制作、他人关系偏好或工作产品设计", "除非用户明确只要一个选择，否则不替用户作唯一决定、固定套餐、下单或付款"],
    dependencies: ["daily-preferences 私有项目的稳定相对入口", "私有数据根中的 CURRENT 薄快照", "偏好原件仍由各来源 Owner 保管；本页不公开本机定位"],
    tests: `个人 Skill 供应的 source（源码）、quick validation（快速校验）与 canonical junction（规范目录联接）通过；2026-09-04 实现项目 PRIVATE main=0b88ce9，v0.6 行为 90c3c28 的 43/43 测试通过。当前为 19 条明示、7 个推定、61 条 current 证据、54,887 个 current 键、62,022 条总记录、84 份制品、13 个来源实例、1 个来源 gap 与 12 项未接入来源。Steam 本地/商店各 132 条、精确关联 132 条、分类 110 paid/21 free/1 unavailable；普通游戏查询返回 12 个已玩游戏（10 paid/2 free），未玩和应用为 0。2026-09-01 的三条实现盲请求早于 Steam，只保留其当时的路由与事实证据，不冒充 Steam fresh E2E。`,
    sourcePath: "E:\\.agents\\skills\\daily-preferences\\SKILL.md",
    sourceBytes: 6889,
    sourceSha256: "b0b4735c37fae0eb4c675740993665f4500f838b6342e72aa2f2a06d349ca552",
    sourceState: `canonical Skill 源码已在干净的当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 核对并由 PRIVATE main 远端回读`,
    installState: "canonical junction 已安装并指向唯一源码",
    currentTaskState: "PASS（通过）；19 条 current 明示、7 个推定、61 条 current 证据、54,887 个 current 记录键与 12 个 v0.6 非人工来源已核对；Steam 游戏只返回已玩项，来源 gap 为 1",
    freshTaskState: "PASS（通过）；2026-09-01 三条实现盲自然推荐、增量准备与具体事实请求能自行选择 daily-preferences 并保持有界只读边界；本轮新增语义没有冒充新的 fresh E2E",
    evidenceObservedAt: `Skill 供应现场：${generatedPanelFacts.observedAt}；项目 v0.6、Steam/来源全景与偏好语义回读：2026-09-04，以 PRIVATE main 0b88ce9 的 CURRENT_ACCEPTANCE.md 为准；三条实现盲验收观察于 2026-09-01`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `canonical SKILL.md（规范能力说明）的 bytes/hash（字节数/指纹）、当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 的 PRIVATE main 远端回读、实现项目 PRIVATE main=0b88ce9 与 v0.6 行为 90c3c28、43/43 项目测试、当前 54,887/62,022/84/19/7/61 聚合、13 来源/12 未接入/1 gap、Steam 132/132/132 与 110/21/1 分类、当前只读购物和 Steam 游戏回读、时间证据回归、历史 v0.6 迁移与 2026-09-01 实现盲请求；公开页不复制账号、游戏清单、游玩细节、原件路径或私人正文。`,
    endToEndState: "PASS（通过）；2026-09-01 三条实现盲请求继续证明当时的吃喝推荐、11 来源增量准备和具体事实路径。2026-09-04 Steam 游戏查询返回 12 个实际玩过的游戏，10 paid/2 free，未玩和应用为 0；43 项回归与 Source Owner 当前验收分别证明多账号合并、商店分类、来源全景与边界，没有冒充 Steam 的 fresh AI 推荐 E2E"
  }),
  skill({
    slug: "document-materials",
    name: "document-materials",
    registryName: "personal-formal-documents",
    title: "文书和材料制作",
    status: "已安装 / 2.0.1 虚构生成链已验 / 真实事项未运行",
    maturity: "A-",
    summary: "把必要原件整理成合同、说明、申请、通知、售后材料或附件包，同时生成可编辑文档和 PDF 并逐页检查；文件做完、本人签完、真正递送和对方处理会分开记录。",
    useWhen: ["已有明确目标、接收对象和必要原件，需要形成正式可编辑文书", "需要同源 DOCX、PDF、附件清单或自包含材料包", "需要逐页核对、签名图片存在性与可见性、版本冻结和后续状态留痕", "需要判断当前究竟是已生成、本人已签、可递送、已递送、已收件还是已处理"],
    avoidWhen: ["只修改一个已知 Word/PDF 文件，直接使用文档或 PDF 能力", "只需要找到原件，进入个人材料查找", "持续变化的需求、项目评审与执行跟踪，进入工作交付", "通用翻译、随手文案、普通消息或他人的事务", "没有原件或事实依据就补写内容", "把本地生成、签名或 ready 状态写成外部现实结果", "未经精确授权递送、付款、撤回或联系外部对象"],
    inputs: ["当前事项的目标、接收对象、期限、状态和下一步", "最小必要原件、已确认事实、来源说明与真正未知", "输出格式、附件、签名要求和接收渠道", "需要外部动作时对精确对象、版本、内容和动作的授权"],
    outputs: ["可继续编辑的 DOCX、同源 PDF 和核过附件", "绑定输入、审计、逐页彩色/灰度图与所需签名快照的自包含材料包", "内容、页码、页面边缘、签名图片存在性与可见性、精确文件集合与哈希验收", "produced（已生成）、signed（本人已签）、ready_for_delivery（已具备递送条件）、delivered（已递送）、received（已收件）、handled（已处理）的分层状态", "独立的 counterparty_signed_returned（对方签回）记录、下一步与恢复点"],
    flow: ["判断是否应进入本项目", "读取当前事项并只取必要原件", "分开事实、来源说明、未知和本人决定", "冻结DOCX/PDF、附件、签名和渠道方案", "生成同源成品", "重读正文并逐页检查彩色/灰度页面", "形成自包含ready_for_delivery材料包", "现实动作完成后分别回读递送、收件、处理和对方签回", "中断后先核对最近材料包再继续"],
    boundaries: ["私人事实、原件、草稿、签名、成品和回执不进入公开 Git", "整包输入固定不等于每条事实来源已机械闭合，真正未知继续保留", "自动字段/页面验收不等于整篇语义和语气已审完", "本人签名与对方签回相互独立", "ready_for_delivery 明确 delivered=false", "不建立数据库、后台服务、队列或第二套材料系统"],
    dependencies: ["受保护的当前材料状态与原件", "正式文书与材料生成、逐页渲染和校验入口", "必要时的原件定位、消息上下文、录音转写或扫描识别能力"],
    tests: `Skill 快速校验、canonical junction（规范目录联接）与 ${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 供应事务通过；实现项目 2.0.1 为 526 pass、6 skip、101 subtests，通用文书 32 pass；隔离 wheel 两个入口均用 Microsoft Word + Poppler 完成完全虚构 plan/build/verify。本轮没有运行真实个人材料或外部递送 E2E。`,
    sourceLocatorVisibility: "withheld",
    sourcePath: "withheld:document-materials",
    publicSourceLabel: "个人 Skill 供应链中的“文书和材料制作”入口",
    sourceBytes: 2179,
    sourceSha256: "462a6592e7fbd42ace718091af3d9c2a1070a36843ac2eeb7d6107f1d9116dd8",
    sourceState: `文书和材料制作 Skill 内容已正式回读；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与供应安装现场另行回读，各层分开说明`,
    installState: "canonical junction 已安装并与规范源码一致",
    currentTaskState: "本轮只运行完全虚构样张，未制作或递送真实个人材料",
    freshTaskState: "安装后的全新 Sol Max 任务已发现“文书和材料制作”入口；发现通过不等于真实事项执行通过",
    evidenceObservedAt: `当前供应链：${generatedPanelFacts.observedAt}；实现与隔离安装验收：2026-09-01`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `文书和材料制作 Skill 当前说明、.agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId}、${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent、${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 终态事务、实现项目 PRIVATE main 3ab7fb4、全仓/聚焦回归与隔离 wheel 虚构验收；供应、实现和真实事项证据保持分层。`,
    endToEndState: "PASS（完全虚构安装后 plan/build/verify）；真实个人材料、真实签名和外部递送 E2E 为 not_run"
  }),
  skill({
    slug: "work-delivery",
    name: "work-delivery",
    title: "工作交付副驾驶",
    status: "已安装 / 0.2.0 当前实现盲路由已通过 / 真实工作价值待验",
    maturity: "B+",
    summary: "当需求说明、会议记录和表格会继续变化，却要生成口径一致的 PRD、评审材料和执行表时，把这项工作送进现有交付项目；来源、冲突、成品和后续变化都能对应起来。",
    useWhen: ["一个持续工作事项有 2–5 份明确来源，并且需要两类以上相互一致的交付物", "本轮只要 PRD，但这些资料明确还会继续变化", "需求或来源会继续变化，需要知道哪些事实和旧 build 已经过期", "要继续一个已经存在的交付包，而不是重新整理全部材料"],
    avoidWhen: ["只编辑一次单个 Word、PPT 或表格", "没有用户明确选择来源就扫描目录、账号或旧对话", "学习、职业发展、求职或私人文书材料", "未经精确授权发送、发布、审批、建任务或修改外部系统"],
    inputs: ["用户明确选择的 2–5 份需求、会议记录、规则、表格或其他工作资料", "新持续事项的稳定且非空 package ID、标题和目标；已有交付包使用原 ID 进入更新命令", "每条候选事实或假设的值、类别、原文证据、动作和非空决定理由", "本轮实际需要的 docx、pptx、xlsx 格式；只要 PRD 时只请求 docx"],
    outputs: ["来源覆盖、已确认事实、假设、冲突、未知、质量状态和唯一待决定事项", "PRD.md、manifest.json、traceability.csv、产品需求文档.docx、项目评审.pptx、执行跟踪表.xlsx 中本轮实际请求且质量允许的文件", "来源变化后的自动重新绑定、过期事实、过期 build 和下一版决定"],
    flow: ["读取项目当前 AGENTS.md 和稳定入口，不在 Skill 里复制实现", "新持续 PRD 使用一个 work-delivery.batch.v1 请求提交 package ID、标题、目标、2–5 份明确来源、证据事实和所需格式", "先交回来源覆盖、关键事实、冲突/缺口和拟采用结构或准确 ETA", "把事实、假设、冲突和未知分开，只让用户处理真正需要决定的项目", "只有 SQLite 重建的 canonical manifest 报告 quality.status=ready 才调用正式 Office 构建；手写 ready 被拒绝", "只要 PRD 时只请求 docx，不等待或启动 PPTX/XLSX", "已有 package ID 通过 update-source、impact、review、build、verify 和 artifacts 继续", "来源更新时唯一原文自动重新绑定，消失或不唯一的事实和引用变化的旧 build 才过期"],
    boundaries: ["一次性单文件或无持续来源关系的普通文本 PRD 直接使用现成文档、演示或表格能力，不增加交付包", "当前正式输出只有 PRD.md、manifest.json、traceability.csv、产品需求文档.docx、项目评审.pptx、执行跟踪表.xlsx；没有现成项目计划、周报或汇报", "可靠输入仍以本地文本、Markdown 和 CSV 为主；其他格式先由相应能力读取或导出", "AI 分析在项目外，Skill 与项目核心都不内置模型或扫描器", "普通 2–5 份来源约 5 分钟内给出覆盖、关键事实、冲突/缺口、结构或准确 ETA；最终时间按来源长度、冲突、输出和同模型同质量直接基线判断", "事实确认后的确定性 PRD.md + DOCX 目标不超过 15 秒；机械时间不冒充整个工作提速", "缺目标、范围、需求、异常、验收、证据或存在关键冲突时，quality 不得 ready，正式 Office builder 保持 0", "没有交付包导出、SQLite 备份、数据库丢失恢复或跨机器迁移", "外部发送、发布、审批、邀请和修改必须由当前请求另行精确授权"],
    dependencies: ["PRIVATE work-delivery-copilot 项目", "work-delivery.batch.v1 规范请求", "现有文档、演示文稿和电子表格运行时作为正式产物构建依赖"],
    tests: `Skill 源码、快速校验、canonical junction（规范目录联接）和 ${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 供应事务通过；0.2.0 为 37/37 tests 与 Ruff 通过，隔离 wheel 和两套完全合成 Office E2E 通过。当前 fresh Sol Max 实现盲自然请求未获 Skill、工具或内部路线提示，自主选择 work-delivery，覆盖 3/3 指定来源，确认 27 条事实和 39 条追溯；5 条待确认中的 4 条阻断正式交付，quality 保持 draft，只生成三个 core files，Office builder 为 0，current verify 通过且旧 build stale。总可见墙钟约 12 分 12 秒，成功 batch 核心约 0.043 秒；这不证明真实工作提速。`,
    sourcePath: "E:\\.agents\\skills\\work-delivery\\SKILL.md",
    sourceBytes: 5178,
    sourceSha256: "e39ed36db7a3c753bca217d31a0ab3f0c20a3ae5dbf6508f3693b78126ba90fb",
    sourceState: `Skill 内容在 .agents PRIVATE main 6a9e1b0 已正式回读；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与供应安装现场另行回读，各层分开说明`,
    installState: "canonical junction 已安装并与规范源码一致",
    currentTaskState: "当前实现盲 E2E 建立一个完全合成交付包；真实工作包仍为 not_run",
    freshTaskState: "当前 fresh Sol Max 在无路线提示时自主选择 work-delivery，并正确让 draft 质量门阻断正式 DOCX",
    evidenceObservedAt: `当前供应链：${generatedPanelFacts.observedAt}；0.2.0 来源与实现盲 E2E：2026-09-01`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `.agents PRIVATE main 6a9e1b0 的 work-delivery Skill、当前 source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId}、work-delivery-copilot PRIVATE main 73f92f1 与 0.2.0 实现 c815ea3、37 项回归、Ruff、隔离 wheel、两套合成 Office E2E 和当前实现盲自然路由；供应、功能、正式成品与真实价值保持分层。`,
    endToEndState: "PASS（无提示路由、3/3 来源边界与 draft 质量门）；PASS（两套完全合成正式 Office E2E）；真实工作、真实来源变化与时间价值为 not_run / baseline_required"
  }),
  skill({
    slug: "documents",
    name: "documents",
    title: "可编辑 Word 文书与逐页验收",
    status: "宿主已集成 / 本轮未跑真实文档",
    statusTone: "mixed",
    maturity: "A-",
    provenance: "宿主集成能力",
    sourceKind: "host_integrated",
    capabilityId: "host:documents",
    evidenceSourceCommit: null,
    summary: "创建、编辑、修订或批注 DOCX（可编辑 Word 文档）时，先按文档用途选结构和样式，再把成品渲染为逐页图片检查裁切、重叠、字体、表格与页眉页脚；只有最后一轮逐页目检通过才交付可编辑文书。",
    useWhen: ["创建或编辑 DOCX / Word 文书", "需要修订痕迹、批注、表单或内容控件", "需要把本地 DOCX 导入原生 Google Docs", "版面、表格、页眉页脚和逐页视觉质量会影响交付"],
    avoidWhen: ["只需要普通纯文本回答", "只读 PDF 而不处理 Word 文档", "把文字提取或 OOXML（Word 文档内部结构）检查当成版面验收", "用户只要最终 DOCX 时交付内部 PNG 或调试 PDF"],
    inputs: ["目标内容、受众、用途与输出格式", "可选模板、参考 DOCX 或必须保留的原结构", "需要修订、批注、表单或 Google Docs 导入时的精确要求"],
    outputs: ["可编辑 DOCX", "需要时的修订、批注、表单或原生 Google Docs 成品", "内部逐页 PNG 目检与结构检查结果"],
    flow: ["发现宿主 workspace 依赖", "按模板或文档类型固定结构与样式 token", "创建或做最小局部编辑", "渲染全部页面为 PNG", "逐页检查并修复后重新渲染", "只交付用户要求的最终文档"],
    boundaries: ["bundle（随宿主发布的能力包）版本只记录本次观察，不作为未来准入", "每个有意义的编辑批次后重新渲染并逐页检查", "Google Docs 新文档先生成并验收本地 DOCX，再走原生导入", "LibreOffice 缺失时必须明确说明未完成视觉门，其他渲染错误先修复"],
    dependencies: ["Codex bundled workspace dependencies", "宿主当前 documents capability（文档能力）"],
    tests: "宿主源码与集成状态可发现；本轮未创建或编辑真实 DOCX，Current/Fresh/E2E 保持 Unknown。",
    sourcePath: "host:documents",
    observedSourcePath: "C:\\Users\\10979\\.codex\\plugins\\cache\\openai-primary-runtime\\documents\\26.826.12353\\skills\\documents\\SKILL.md",
    sourceBytes: 42857,
    sourceSha256: "adb4fa343854795dcb724871b66c5e05ba537d110a62ecc700fa2f44967a0295",
    evidenceSourceCommit: null,
    sourceState: "宿主 bundle canonical source（规范源码）已核对",
    installState: "宿主已集成；按稳定能力发现，不以 bundle 版本准入",
    transactionState: "宿主集成能力不经过个人 Skill 安装事务",
    currentTaskState: "本轮未创建或编辑真实 DOCX",
    freshTaskState: "Fresh task（全新任务）回执 Unknown（未知）",
    endToEndState: "真实文档创建、渲染与逐页验收 E2E 本轮 Unknown",
    evidenceObservedAt: "宿主 bundle 26.826.12353：2026-08-31 本轮观察",
    evidenceBasis: "宿主集成 documents capability（文档能力）的源码身份只由结构化来源字段记录；宿主版本不成为准入，本轮没有真实文档 E2E。",
    supplyEvidenceCommand: "Codex workspace dependency loader（工作区依赖发现入口）"
  }),
  skill({
    slug: "pdf",
    name: "pdf",
    title: "PDF 读写、表单与逐页验收",
    status: "宿主已集成 / 本轮未跑真实 PDF",
    statusTone: "mixed",
    maturity: "A-",
    provenance: "宿主集成能力",
    sourceKind: "host_integrated",
    capabilityId: "host:pdf",
    evidenceSourceCommit: null,
    summary: "读取、生成、检查或填写 PDF 时，同时核对内容结构与真实页面；交互表单还要检查 AcroForm（PDF 表单字段树）、页面控件、字段值和外观流，不能用“画面看见值”冒充字段已经正确写入。",
    useWhen: ["读取或审阅版面重要的 PDF", "程序化生成正式 PDF", "填写并验证交互式 AcroForm", "需要逐页检查裁切、重叠、字体、表格或页码"],
    avoidWhen: ["只需编辑 DOCX 源文书", "只看文本提取就判断版面正确", "未经明确要求把可编辑表单压平", "把旧页面图或成功退出码当成本轮 PDF 验收"],
    inputs: ["PDF 原件或要生成的内容与版式要求", "表单字段名、目标值和是否明确要求压平", "页数、关键文本、交互性与视觉验收条件"],
    outputs: ["读取结果、生成 PDF 或已填写表单", "字段树、页面控件、字段值与外观的一致性检查", "全部页面的 PNG 目检结论"],
    flow: ["读取结构与页数", "按任务选择生成、提取或表单路线", "表单同时核对字段树和页面控件", "写入后重新打开并验证逻辑值", "渲染全部页面检查真实外观", "只交付最终 PDF"],
    boundaries: ["bundle 版本只记录本次观察，不作为未来准入", "视觉通过不能替代表单字段树和逻辑值检查", "默认保留表单交互性；只有用户明确要求才压平", "每次有意义更新后重新渲染并检查全部页面"],
    dependencies: ["Codex bundled workspace dependencies", "Poppler", "reportlab、pdfplumber 与 pypdf", "宿主当前 pdf capability（PDF 能力）"],
    tests: "宿主源码与集成状态可发现；本轮未读取、生成或填写真实 PDF，Current/Fresh/E2E 保持 Unknown。",
    sourcePath: "host:pdf",
    observedSourcePath: "C:\\Users\\10979\\.codex\\plugins\\cache\\openai-primary-runtime\\pdf\\26.826.12353\\skills\\pdf\\SKILL.md",
    sourceBytes: 7269,
    sourceSha256: "9e429bfc5ada20ccf25a531484e3dcc5da59811d936a7cc5dfd23dbf2dfadd31",
    evidenceSourceCommit: null,
    sourceState: "宿主 bundle canonical source（规范源码）已核对",
    installState: "宿主已集成；按稳定能力发现，不以 bundle 版本准入",
    transactionState: "宿主集成能力不经过个人 Skill 安装事务",
    currentTaskState: "本轮未读取、生成或填写真实 PDF",
    freshTaskState: "Fresh task（全新任务）回执 Unknown（未知）",
    endToEndState: "真实 PDF 读写、表单与逐页验收 E2E 本轮 Unknown",
    evidenceObservedAt: "宿主 bundle 26.826.12353：2026-08-31 本轮观察",
    evidenceBasis: "宿主集成 pdf capability（PDF 能力）的源码身份只由结构化来源字段记录；宿主版本不成为准入，本轮没有真实 PDF E2E。",
    supplyEvidenceCommand: "Codex workspace dependency loader（工作区依赖发现入口）"
  }),
  skill({
    slug: "md-to-pdf",
    name: "md-to-pdf",
    title: "Markdown 导出 PDF",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    provenance: "本地维护插件",
    summary: "在 Windows 上把 Markdown 按文档语义转换成 PDF，支持中文路径、样式配置、精确分页和不依赖 Typora 的导出。",
    useWhen: ["Markdown 需要正式 PDF", "需要 CSS 或 presentation profile", "需要精确页数或分页", "中文文件名和路径必须稳定"],
    avoidWhen: ["需要修改原 Markdown 正文", "把渲染成功当语义验收", "绕过现有文档样式约束"],
    inputs: ["Markdown 源文件", "输出 PDF 路径", "可选 CSS、profile 和页数要求"],
    outputs: ["原子发布的 PDF", "source hash、页数、文本和布局验证结果"],
    flow: ["先判断文档语义", "选择批量 preset 或 styled converter", "优先 Playwright，必要时使用 Edge CLI fallback", "验证 hash、时间、大小、页数和 Unicode 文本", "交给 PDF 安全渲染做目检"],
    boundaries: ["不修改 Markdown", "不依赖 Typora 许可", "fallback 不降低验收", "陈旧 PDF 不能冒充本轮结果"],
    dependencies: ["本地 Edge", "Node 浏览器运行时或 Edge CLI", "md-pdf-toolkit"],
    tests: "插件转换相关的 13 项测试和 4 个子测试全部通过。",
    sourcePath: "E:\\.agents\\plugins\\md-pdf-toolkit\\skills\\md-to-pdf\\SKILL.md",
    endToEndState: "核心转换与样式路径已验"
  }),
  skill({
    slug: "pdf-render-safe",
    name: "pdf-render-safe",
    title: "PDF 安全渲染与目检",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    provenance: "本地维护插件",
    summary: "把 PDF 的每一页变成清晰图片和一张总览图，方便我肉眼检查排版；同时核对原文件指纹，避免拿旧图片或错误渲染结果当成这次输出。",
    useWhen: ["需要肉眼检查 PDF 布局", "需要高 DPI 页面或联系表", "怀疑输出陈旧", "中文路径或页码选择需要稳定"],
    avoidWhen: ["只验证纯文本内容", "使用未受支持的 shell wrapper renderer", "删除其他任务产生的图片"],
    inputs: ["PDF 路径", "页码、DPI 和输出 prefix"],
    outputs: ["页面 PNG", "contact sheet", "含 source SHA、页数、renderer 和 stale cleanup 的 JSON report"],
    flow: ["150 DPI 全量初检", "定位可疑页", "只对可疑页提高 DPI", "验证 source fingerprint 和输出集合", "结合文本与页数判断"],
    boundaries: ["只删除同 prefix 的陈旧 PNG", "渲染成功不等于语义完整", "不接受 wrapper 冒充 renderer"],
    dependencies: ["Poppler", "Pillow", "md-pdf-toolkit"],
    tests: "测试通过，覆盖页码选择、prefix、renderer 边界和精确 stale cleanup。",
    sourcePath: "E:\\.agents\\plugins\\md-pdf-toolkit\\skills\\pdf-render-safe\\SKILL.md",
    endToEndState: "主要渲染路径已验"
  }),
  skill({
    slug: "mojibake-doctor",
    name: "mojibake-doctor",
    title: "中文乱码诊断与修复",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "诊断 UTF-8、GBK、GB18030、BOM、替换字符、私用区和双重转码，并以预览、备份和原子替换完成可逆修复。",
    useWhen: ["中文出现乱码", "怀疑编码或 BOM 损坏", "出现替换字符或私用区", "可能发生双重转码"],
    avoidWhen: ["没有读取原始 bytes（字节）", "信息已经丢失却强行猜字符", "跟随 junction（目录联接）修改另一个 source（源码）"],
    inputs: ["精确文件或目录", "可选编码线索"],
    outputs: ["scan 和 diagnosis", "默认只读 repair plan", "apply 后的 verify 结果和原字节 backup"],
    flow: ["读取 raw bytes", "scan 和 diagnose", "先 preview", "显式 apply", "重新读取并 verify"],
    boundaries: ["单文件 hash-pinned transaction", "原字节 backup", "atomic replace", "信息丢失时回到 Git、备份或重新生成"],
    dependencies: ["本地 Python"],
    tests: "12 项 Python 测试和专门 Skill 测试通过。",
    sourcePath: "E:\\.agents\\skills\\mojibake-doctor\\SKILL.md",
    endToEndState: "主要修复路径已验"
  }),
  skill({
    slug: "file-intake-router",
    name: "file-intake-router",
    title: "混合附件分流",
    status: "已安装 / 薄路由",
    maturity: "A-",
    summary: "当我一次给出 Word、PDF、表格、图片、压缩包或整个文件夹，不知道该用哪个读取工具时，它先看清文件结构，再把每一类材料交给真正适合的读取器；单个已知文件不需要它。",
    useWhen: ["附件类型混杂", "无法确认是文本 PDF 还是扫描 PDF", "输入是 archive 或目录", "需要先做最小 inventory"],
    avoidWhen: ["一个已知 Word、PDF、表格或图片", "把所有文件都 OCR", "扫描无关子目录", "路由完成后仍继续接管处理"],
    inputs: ["少量文件 inventory", "用户想得到的最终结果"],
    outputs: ["一个最合适 reader 的明确路由", "必要时最小的后续输入范围"],
    flow: ["识别容器和文件结构", "优先结构化提取", "选择 Word、PDF、表格、OCR、ASR 或其他原生 reader", "交接后退出路由"],
    boundaries: ["单一已知类型直接 reader", "先结构化提取后 OCR", "目录只检查满足请求的子集", "默认不上传私有材料"],
    dependencies: ["当前宿主可用的原生 readers"],
    tests: "source、install、quick validation 与 Personal Skill 语义回归均已通过。",
    sourcePath: "E:\\.agents\\skills\\file-intake-router\\SKILL.md"
  }),
  skill({
    slug: "browser-control-continuity",
    name: "browser-control-continuity",
    title: "浏览器任务恢复、上传与提交回读",
    status: "已安装 / Fresh 自然路由已验 / 真实浏览证据分层",
    statusTone: "pass",
    maturity: "B+",
    sourceKind: "personal_install",
    summary: "在 Codex 或 Chrome 更新、受管浏览控制中断、旧标签页状态不明、异步表单选项尚未加载，或文件上传只显示进度却没有完成时，尽量保留用户已登录和已填写的现场，恢复同一受管浏览能力，并把上传、提交与平台记录回读分别验收。",
    useWhen: ["浏览控制内核或受管运行文件缺失，但旧标签页和登录态仍有价值", "表单下拉项依赖前一层异步加载，连续点击会丢状态", "需要逐个上传文件并确认页面真正进入成功态", "点击提交后必须从新生成的平台记录核对字段和附件", "一次跨项目浏览故障已经完成真实恢复，需要判断是否沉淀可复用教训"],
    avoidWhen: ["页面专属字段、收件人、业务规则或提交内容，应留在所属项目", "当前没有受管浏览 Provider（能力提供方），本 Skill 不能自造浏览器客户端", "想用本地恢复权限绕过登录、验证码、网站权限或外部动作授权", "只有猜测或一次失败，没有成功恢复和用户可见 E2E", "需要任意下载第三方二进制或覆盖现有运行文件"],
    inputs: ["当前受管浏览 Provider 的原生操作说明", "现有标签页、控制会话与页面的实时状态", "运行缺口报错中精确的 canonical browser scripts 目录", "用户明确选择的单个上传文件和目标表单", "真实失败、最小恢复与最终页面回读证据"],
    outputs: ["保留或重新接管的同一已登录标签页，必要时同 Profile（浏览器配置档）的新标签页", "只复制缺失文件且可清理的临时运行兼容恢复回执", "逐文件 authoritative success（权威成功态）与精确附件数回读", "提交前字段快照、提交后平台记录与实际附件核对", "达到真实证据阈值后原位更新且带退出条件的跨项目浏览教训"],
    flow: ["先读当前受管浏览能力的原生说明并列出现有受控标签页", "控制重置后优先重新取得同一标签页；锁定页保留为备份，只有继续价值更高时才在同一已登录 Profile 新开标签", "运行文件缺失时先走官方刷新；无支持路线且满足同官方包族、只补缺失、禁止覆盖时，先 Inspect 再 Repair", "helper 只处理 browser-service.mjs、browser-accessibility.wasm.br 与 zxing_reader.wasm 三个受管文件，并逐一回读 SHA-256", "恢复后必须真实连接并做只读标签页核对，任务结束或原生包恢复后凭 receipt（回执）Cleanup", "上传时先等待 file chooser（文件选择器），再点按钮并一次只放一个绝对路径", "每个文件要求页面 authoritative success 与精确文件名回读后才继续", "异步控件按实时依赖一层层展开，下一层标签出现后再选择", "提交前重读关键字段、附件数与文件名；提交后打开平台记录再次核对", "只有失败、成功恢复与用户可见 E2E 三层齐全时，才把跨项目机制写回本 Skill 并说明退休条件"],
    boundaries: ["这是受管浏览能力之上的连续性层，不是第二浏览器客户端、原始自动化服务器或授权旁路", "优先保护已填写、已登录和用户拥有的标签页，不先重载、导航或关闭", "文件名、100% 进度或页面跳转都不是成功；必须读取页面成功态和最终记录", "临时恢复只补精确缺失文件，核对 source/target SHA-256 一致，不覆盖现有目标，并在原生路径恢复后清理", "本地恢复不授权登录、传输、上传、验证码、删除或最终提交", "不公开标签页正文、附件名、平台记录 ID、截图、秘密或临时回执内容", "跨项目浏览机制归本 Skill，页面字段与业务含义归具体项目"],
    dependencies: ["当前宿主提供的 managed browser Provider（受管浏览能力）", "同一官方 bundled browser package family（浏览器包族）的完整旧版本，仅用于有界缺失文件恢复", "scripts/Invoke-BrowserControlContinuity.ps1 的 Inspect / Repair / Cleanup", "当前任务 E 盘临时目录中的恢复 receipt"],
    tests: "`.agents` PRIVATE main=e2cc7e9，活动 E100 release 仍绑定 6922fd8；Skill source、quick validation 与 canonical junction 已通过，当前供应为 29 个 active install intent、41/41 个终态事务。来源 Owner 已完成全新任务自然路由验收；网站本轮没有重放真实上传、最终提交或临时 runtime 修复，因此分别保留既有真实浏览证据与当前安装证据。",
    sourcePath: "E:\\.agents\\skills\\browser-control-continuity\\SKILL.md",
    sourceBytes: 6276,
    sourceSha256: "43efbbb0f8e05d5c7d90d567bc57bd62f53ea0bc13406e7f388ff9a2d0c7d283",
    sourceState: "browser-control-continuity 在当前 .agents PRIVATE main=e2cc7e9 中可达；Skill 首次发布提交为 0cfef9e，E100 release 为 6922fd8，当前源码与已安装目录一致",
    installState: "canonical junction 已安装，source 与 quick validation 通过",
    currentTaskState: "PASS（通过）；来源任务核对 Skill、确定性恢复 helper 与供应安装，网站任务只读取公开安全合同",
    freshTaskState: "PASS（通过）；来源 Owner 已完成无内部路线提示的全新任务自然路由验收",
    evidenceObservedAt: "2026-09-04；供应现场与 PRIVATE main 已重新回读",
    evidenceBasis: "PRIVATE source/install/transaction、全新任务自然路由回执，以及既有真实浏览故障的失败→恢复→用户可见回读；当前 helper 未在网站任务中执行，不用源码存在冒充一次新 runtime 恢复",
    endToEndState: "旧标签页保留、异步控件、逐文件上传成功态与提交后记录回读来自已完成真实浏览工作；新 Skill 的 fresh route 已验，但任意未来网站仍需自己的字段、附件与最终记录现场验收"
  }),
  skill({
    slug: "media-person-self",
    name: "media-person-self",
    title: "具名媒体中的本人判断",
    status: "已安装 / 图像已验 / 语音复用",
    maturity: "B",
    summary: "需要判断一张指定照片里的人是不是我，或一段指定录音、视频音轨里有没有我的声音时，它只比较这几个明确文件，分别给出图像框或语音时间段和不确定性；不会扫描媒体库，也不会识别其他人。",
    useWhen: ["判断用户是否出现在一张明确照片中", "指出哪个 face box 是本人候选", "判断一段具名录音或视频音轨的精确句段是否支持本人说话", "只有一个文件或很短的显式列表"],
    avoidWhen: ["扫描相册、目录或整个媒体库", "识别或命名其他人", "建立人脸或声纹库", "把相似度当法律身份", "把未测试 cluster 的全部语句都归给本人"],
    inputs: ["一个具名媒体或很短的显式列表", "私有可撤销 face template 或 held-out voice profile", "语音需要精确时间戳句段和最小已绑定上下文"],
    outputs: ["图像的 present、not detected、no face 或 unknown", "face index、bounding box 或精确音频时间段", "self、other、unknown 的覆盖范围和一句可反驳依据"],
    flow: ["照片用固定检测器找 face box", "固定识别器与私有模板比较", "录音和视频音轨复用中文 ASR 的时间戳与匿名 cluster", "对最多两句清晰句段做 held-out voice evidence", "分别输出视觉和语音结果，不强行合并", "质量、profile 或覆盖不足时保留 unknown"],
    boundaries: ["不暴露模板向量、声纹或内部相似度", "不命名其他人", "不复制或修改源媒体", "不从文件名、时间接近或目录推断身份", "删除或替换 profile 会改变未来判断"],
    dependencies: ["本地 YuNet 与 SFace", "私有 person:self face template", "ChineseASR 的 Paraformer、时间戳和 held-out voice profile"],
    tests: "照片 adapter 8 项测试通过；语音链复用中文 ASR 的既有句段证据能力，Skill 自身仍缺少一组独立语音回归。",
    sourcePath: "E:\\.agents\\skills\\media-person-self\\SKILL.md",
    endToEndState: "照片路径已验；并发候选不计入"
  }),
  skill({
    slug: "local-secret-broker",
    name: "local-secret-broker",
    title: "本地凭据 Broker",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "需要确认某个账号或密钥是否存在、让程序使用它、或做备份恢复时，它从本机 Password Center（密码中心）走受保护入口处理；默认只返回账号和状态，不把密码或访问令牌暴露到聊天、命令行和普通文件。",
    useWhen: ["查询某个账号或 SecretRef 是否存在", "需要精确获取一个凭据字段", "让浏览器或程序 blind fill", "执行凭据备份、恢复或轮换"],
    avoidWhen: ["把秘密放进聊天、argv、环境变量或普通文件", "未明确请求就揭示明文", "自动处理验证码、Passkey 或 CAPTCHA", "设备处于不可信状态"],
    inputs: ["目标服务、账号或 SecretRef", "一个精确 operation", "需要明文时的明确请求和人类因子"],
    outputs: ["metadata-only lookup", "受保护 capability 或 blind-fill 结果", "必要时单字段明文，不进入普通日志"],
    flow: ["普通查询先 metadata-only", "沿固定 reference 选择精确 operation", "需要最高权限时触发相应因子", "在消费点执行", "正式 read-back"],
    boundaries: ["秘密值不进入公开面板", "人类验证失败只暂停", "管理员权限令牌不扩大授权", "device untrusted（设备不可信）时失败关闭"],
    dependencies: ["PCConfig Password Center（密码中心）", "KDBX 或相应秘密权限来源", "活动保护策略"],
    tests: "精确 lookup fast-path（快速查询路径）测试通过；活动规则权威当前有效。",
    sourcePath: "E:\\.agents\\skills\\local-secret-broker\\SKILL.md",
    endToEndState: "受保护场景按需验收"
  }),
  skill({
    slug: "authorization-file-broker",
    name: "authorization-file-broker",
    title: "最高权限文件加解密",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "当用户明确说要加密或解密某几个文件、某个目录时，它让 Password Center 完成真正的加密、校验和中断恢复；源文件不删除，遇到同名冲突也不会覆盖。",
    useWhen: ["批量加密明确文件或目录", "验证加密 bundle 而不落地明文", "解密到明确目标", "中断后继续已授权任务"],
    avoidWhen: ["扫描磁盘寻找文件", "分析文件语义", "覆盖已存在冲突文件", "删除源文件或 bundle"],
    inputs: ["精确源路径和目标", "Encrypt、Verify 或 Decrypt operation", "最高权限因子"],
    outputs: ["加密 bundle 或恢复目录", "不含内容和 key 的 receipt", "冲突与未处理项"],
    flow: ["解析精确对象", "取得最高权限能力", "执行 Encrypt、Verify 或 Decrypt", "中断时从 authenticated state 恢复", "正式 read-back"],
    boundaries: ["内容和 key 不进入聊天、stdout 或 JSON", "不覆盖冲突", "不删除源", "不扩大到未点名路径"],
    dependencies: ["Password Center", "活动最高权限链"],
    tests: "6 项测试通过，覆盖 round-trip、恢复、幂等解密、篡改和 source change fail-closed。",
    sourcePath: "E:\\.agents\\skills\\authorization-file-broker\\SKILL.md",
    endToEndState: "受保护 round-trip 已验"
  }),
  skill({
    slug: "vault-workflow",
    name: "vault-workflow",
    title: "本地加密库查看、编辑与备份",
    status: "已安装 / 隔离回归已验",
    maturity: "A",
    summary: "为 vault-tool 选择仅检查、本地查看／编辑或私人密文备份入口。只检查时不解密；需要原文时明确指定库，由本人在本地输入密码和必要密钥文件。编辑保留未改成员与原参数；普通密文发布有远端字节回读，README保护另报其较窄的API结果。不把未保存退出当成功，也不与密码中心混用。",
    useWhen: ["不打开原文地检查库结构与环境", "在本机查看或编辑指定库里的支持文本", "核对精确密文的私人备份", "明确要求保护指定远端 README 正文"],
    avoidWhen: ["把它当 Password Center（密码中心）", "把密码交给模型或命令行参数", "向非 PRIVATE（私有）目标发布", "把预演、路径存在或关闭窗口当成保存完成"],
    inputs: ["明确的模式、操作意图和目标库；LocalView/LocalEdit 要求 VaultFile", "本人只在本地输入密码，按库要求选择精确密钥文件", "远端写入还需明确的私人目标、路径和制品"],
    outputs: ["不含原文的元数据、建议与实际效果状态", "本地窗口中的支持文本，或明确的 saved／未保存／取消结果", "普通发布的真实写入和远端密文字节回读；README保护只有单提交API结果，不混同"],
    flow: ["先分清仅检查、本地读写还是远端动作", "检查模式只读结构和环境，不自动执行建议", "本地读写明确目标，本人提供所需凭据；不捕获会打印明文的CLI查看输出", "保存前检查成员、原KDF（密码派生参数）和槽位容量；不能保真则停止", "普通密文发布核对默认分支字节；README保护只有本地候选自检与单提交API结果，后续字节回读另列未实现"],
    boundaries: ["密码和原文不返回模型；本地读写不把原文落盘", "PromptOnly只采集并丢弃输入，不验证密码或自动找库", "编辑不静默更换密钥文件、KDF或丢弃未解锁槽", "回退失败须保留失败状态和密文恢复副本，不能被下一次操作洗成成功", "与密码中心及其最高权限文件入口各自独立"],
    dependencies: ["vault-tool 的本地容器与加密实现", "PowerShell 适配脚本和本地 Tk 图形界面", "仅远端动作依赖 GitHub 私人目标与现有 gh 工具"],
    tests: "本轮41项虚构文件回归通过，覆盖元数据、成员与参数保真、容量拒绝、保存和回退失败、发布结果字段校验；独立复验通过。真实密码框、私人远端和换机恢复不由隔离替身测试代替。",
    sourcePath: "E:\\.agents\\skills\\vault-workflow\\SKILL.md",
    endToEndState: "隔离样例已验；真实私人操作未验"
  }),
  skill({
    slug: "project-entry-gate",
    name: "project-entry-gate",
    title: "Git 项目身份入口",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "在准备改代码、提交、推送、发布或恢复仓库前，它先确认我究竟在哪个仓库，这个仓库是公开还是私有，当前分支和远端是什么，有没有未提交或未同步的改动，以及现在能不能安全继续。它只提供事实，不替用户授权推送。",
    useWhen: ["不确定当前 checkout（本地检出目录）属于哪个仓库", "准备恢复、迁移、推送或发布", "需要确认仓库是公开还是私有、默认分支是否正确", "多个 Git worktree（工作树）和同步状态会影响实施"],
    avoidWhen: ["已经明确仓库身份、只做普通可逆本地编辑", "把 admission（准入结果）误当成用户已经授权推送", "Git 动态事实不会改变当前决定却仍做全量扫描"],
    inputs: ["要检查的 GitHub 仓库 owner/repo（仓库所有者或命名空间 / 仓库名，例如 wlyaaaaa/wly0829.cn）", "可选的本地工作树或目标分支", "这次只需缓存、实时 GitHub 信息、刷新远端引用，还是完整发布检查"],
    outputs: ["真实本地仓库路径、远端地址、公开性、当前分支、上游分支、工作树、未提交改动和同步状态", "明确的继续、先处理再继续或停止建议；它本身不产生用户授权"],
    flow: ["先判断当前决定需要多新的 Git 事实", "调用 Git Owner 的 admission（准入检查）", "只检查本次指定的工作树或分支", "把事实结果与用户授权分开", "真正发布前再次用完整 publication profile（发布检查）回读"],
    boundaries: ["仅仅出现一个绝对路径不会自动触发", "cached（缓存）事实不能冒充 live（实时）事实", "decision（建议结果）不会自动授予 push（推送）权限", "仓库公开风险不清楚时停止发布"],
    dependencies: ["E:\\GitHub总索引", "Git 和 GitHub metadata"],
    tests: "Skill 和 Provider fixture 通过，覆盖 identity、visibility、target、sync、dirty、no-upstream 和 public exposure。",
    sourcePath: "E:\\.agents\\skills\\project-entry-gate\\SKILL.md",
    endToEndState: "真实仓库 admission 已多次使用"
  }),
  skill({
    slug: "personal-panel-refresh",
    name: "personal-panel-refresh",
    title: "个人看板实质刷新与发布合并",
    status: `已安装 / ${currentERules.releaseId} 活动规则与供应通过 / 对应快照有界合并与稳定批次`,
    maturity: "A-",
    summary: "一个已登记项目、规则或能力发布后，它只检查网站里对应的说明会不会因此说错话。需要更新时优先交给正在发布的网站负责人合并；没人负责才开新任务，不扩成全站重做，也不让来源项目原地等待。",
    useWhen: ["来源项目已经完成发布和正式回读", "本次变化涉及网站登记的项目、规则或能力", "页面里的事实、解释、边界、成熟度或使用判断可能因此变错", "网站可能已有另一个活动发布 Owner，需要避免重复发布或竞争写入"],
    avoidWhen: ["来源还只是草稿、候选或未验证状态", "只有格式、注释、内部重构、时间戳或仅哈希变化", "当前页面已经准确说明受阻状态，没有新的实质失真", "需要本人明确启动的页面没有新的更新请求", "试图让来源工作直接修改、测试或发布网站"],
    inputs: ["网站登记的项目、规则或能力", "来源身份、正式远端回读提交、改动路径、观察时间与活动代际", "assessor（影响评估器）原因与为什么页面会实质失真的 Source Owner 判断", "产品、Rules、Skills、System 中确实由这个来源直接影响的公共表面"],
    outputs: ["无需更新，或需要网站跟进的实质判断与理由", "发送给现有活动发布 Owner 的一次有界增量，或没有活动 Owner 时安排一份全新网站工作", "绑定来源身份、回读提交、改动路径、观察时间与活动代际的对应快照增量", "产品与技术新增、修改、退役/替代和 Unknown 的有界语义差分", "Project、Rules、Skills、System 各自 changed、unchanged 或 blocked 的闭包", "一个稳定发布批次的一次完整网站检查、单次定向提交、现有 PUBLIC main 正常推送、Pages 部署与公网回读"],
    flow: ["等来源 Owner 完成自己的发布和正式回读", "每次重新读取网站登记清单，把来源解析到唯一对应快照，只运行相关路径影响评估，不枚举无关项目或转成全站复核", "Source Owner 对照当前页面判断是否真的实质失真", "不影响页面或需要本人明确启动的页面没有新请求时明确 no-op", "读取实时任务列表；只有状态精确为 active 且当前 Owner 范围覆盖本次网站发布才复用，标题、更新时间、旧交接、历史 Owner 或来源对话都不充分，其他状态全部排除", "存在唯一合格发布 Owner 时只发送一次来源身份、提交、路径、原因、实质判断和受影响表面；即使它由另一来源创建或正在刷新别的登记快照，也由它合并同一候选", "没有合格发布 Owner 时按当前经济路由选择 Sol 家族或更强未来模型并安排一份全新网站工作", "安排受理只证明发送或创建成功，不证明已读、合并或完成；来源立即继续，不等待、不轮询", "网站负责人为每个增量绑定来源身份、回读提交、路径、观察时间和活动代际；同源后继提交只替换被它包含的同源证据，其他来源增量继续保留", "只有来源输入、E 代际、Registry revision（登记表修订号）和负责表面仍匹配时才复用证据；同源新提交本身不制造 Owner 范围反复变更", "先完成一个连贯编辑批次和对应聚焦检查；批次稳定后只运行一次完整测试、构建、公开内容门和最终浏览验收", "同一失败类别在输入未变时重复两次就先诊断共同原因；预览服务使用可控后台会话、就绪期限和仅清理本任务进程的收口", "全部检查通过后只发布一次现有 PUBLIC main，等待 Pages 并从公网回读"],
    boundaries: ["每次来源事件只更新它的对应登记快照与会因此说错的直接表面，不调用全站复核", "不复制网站登记清单", "不建 watcher（监视器）、daemon（后台进程）、定时任务或轮询", "不在来源工作里编辑、构建、测试或发布网站", "不把草稿、候选或未验证状态当成已发布事实", "同一来源提交与同一网站目标不重复发送或创建", "现有活动发布 Owner 优先；发送失败时不另开竞争任务", "不把开发或预览服务当前台长任务等待；只启动可控制、可限时并能准确关闭的后台会话", "语义判断和正文写入不降级到 Luna、Terra 或本地模型，也不把今天的精确模型写成永久上限", "跨任务派发受理不等于对方已读或完成，来源不读取进度、不等待、不轮询", "现有长期授权不跳过 system/developer/platform、Owner scope、目标解析、拒绝、补证、网站检查或本人预览，也不覆盖新公网目标、付费、秘密暴露、force-push（强制推送）或用户明确暂缓"],
    dependencies: ["wly0829.cn Registry 与路径影响评估器", "网站 Execution Owner 与当前任务状态解析", "native-economy-routing 的当前模型家族与思考强度选择", "桌面 AI 工作台的现有任务跟进与全新工作入口", "已验收的 PUBLIC main、GitHub Pages 与公网回读路径"],
    tests: `当前 ${currentERules.releaseId} 活动规则、Skill supply 与安装分层通过；${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent、${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 个终态事务。e2cc7e9 的语义回归覆盖单一对应快照、禁止全站扩张、增量五元绑定、匹配时证据复用、同源提交不引发责任范围抖动、稳定批次一次最终门、重复失败先诊断以及可控后台预览；既有 active 精确判断、失败不竞争和受理不等于完成继续通过。本轮真实链路把多个来源增量交给一个活动网站 Owner，并由同一 PUBLIC 发布与 Pages 回读收口。`,
    sourceState: `personal-panel-refresh 唯一源码已在 .agents PRIVATE main=e2cc7e9 正式回读并安装；当前活动规则仍为 ${currentERules.releaseId}，网站只展示 source/install 的正式事实`,
    currentTaskState: "PASS（通过）；本轮一个活动网站发布 Owner 已接收 daily-preferences、E100/新 Skill 与 e2cc7e9 同源后继增量，按对应快照合并为同一候选，没有创建竞争网站任务或扩成全站复核",
    freshTaskState: "无活动网站 Owner 时的全新网站工作路线已有历史验收；本轮存在活动 Owner，因此正确选择跟进而非另开工作",
    evidenceObservedAt: `活动 Owner 合并链、当前来源/供应与网站最终发布观察于 2026-09-04；供应链现场：${generatedPanelFacts.observedAt}`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} panel_post_publish_closeout、personal-panel-refresh 唯一源码与供应事务、历史全新网站工作路线、本轮 existing Owner（现有责任方）跟进和网站内容/构建/PUBLIC/Pages 检查；不公开任务编号或内部维护账本。`,
    sourcePath: "E:\\.agents\\skills\\personal-panel-refresh\\SKILL.md",
    sourceBytes: 12037,
    sourceSha256: "c5286475e8c1f3e24bacf40a4ba5ff1e1846febf2261b27c6249a28977284e9c",
    endToEndState: "无活动 Owner 时的全新网站工作路线与来源立即继续已有历史证据；本轮现有 Owner 路线以多个来源有界跟进、对应快照合并、稳定批次单次正常推送和 Pages/公网回读闭合，安排受理本身不冒充完成"
  }),
  skill({
    slug: "control-plane-doctor",
    name: "control-plane-doctor",
    title: "三控制面只读体检",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "当用户说“检查三个控制面现在是否健康、有没有漂移、迁移或恢复问题”时，它只读取被点名的 .agents、Git 或 PCConfig 状态，汇总哪里正常、哪里警告、哪里阻塞；它自己不实施修复。",
    useWhen: ["明确要求控制面健康检查", "需要漂移或迁移验收", "跨仓库恢复", "需要聚合 health 和 convergence"],
    avoidWhen: ["普通项目实现", "直接实施修复", "没有选择 Owner 却扫描全部控制面", "把 cached warning 当 block"],
    inputs: ["Owner、check 和 freshness"],
    outputs: ["各 Owner 的 health、convergence、warning 和 block", "精确 remediation owner"],
    flow: ["按选择的 Owner 调用精确 provider", "默认 cached 和 zero-write", "聚合而不篡改原状态", "需要修复时退出 Doctor 并交给真实 Owner"],
    boundaries: ["不修复、不安装、不改任务", "不 commit 或 push", "未选择的 Owner 连 provider 路径都不读取", "warning 与 block 分开"],
    dependencies: ["Personal Skill validator", "Git admission", "PCConfig drift provider"],
    tests: "Owner scope 与 Skill metadata 测试通过；description 已恢复为显式 Use when 入口。",
    sourcePath: "E:\\.agents\\skills\\control-plane-doctor\\SKILL.md"
  }),
  skill({
    slug: "tailscale-safe-exposure",
    name: "tailscale-safe-exposure",
    title: "Tailnet 精确暴露",
    status: "已安装 / 环境条件型",
    maturity: "B",
    summary: "需要让一台指定设备通过 Tailscale 访问本机服务，或检查 Sunshine/Moonlight 为什么走直连、DERP 或中继时，它先看当前监听和防火墙，只开放必要端口给必要 peer，并记录怎样回滚。普通局域网和 Wi-Fi 问题不走它。",
    useWhen: ["只允许 tailnet 内访问本地服务", "需要 peer-scoped firewall", "检查 reverse port 或 loopback 暴露", "验收 Sunshine/Moonlight direct、DERP 或 Peer Relay"],
    avoidWhen: ["普通 LAN、Wi-Fi 或 VPN 问题", "默认打开 Funnel", "把 RemoteAddress 设为 Any", "一次修改多个机制和端口"],
    inputs: ["精确 service、protocol、port 和 peer", "当前 Tailscale 身份、监听和 firewall 基线"],
    outputs: ["preimage、最小配置差异、rollback", "本机、tailnet 和 peer 分层验收"],
    flow: ["读取身份和监听基线", "选择单一最小机制", "记录 preimage 和停止条件", "执行一项变更", "read-back 与具名 peer 验收", "失败按预记 rollback"],
    boundaries: ["默认禁 Funnel", "禁止宽泛 remote/interface", "read-back 失败即回滚", "没有具名 peer 不能声称 E2E"],
    dependencies: ["Tailscale CLI", "精确服务和 peer 环境"],
    tests: "本机 CLI 当前存在；未做本轮具名 peer 连接验收，也没有独立 Skill 全套测试。",
    sourcePath: "E:\\.agents\\skills\\tailscale-safe-exposure\\SKILL.md",
    endToEndState: "具名 peer E2E 未验"
  }),
  skill({
    slug: "llm-backend-toolkit",
    name: "llm-backend-toolkit",
    title: "额外模型 Backend 工具箱",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "当原生子代理不适合、但有一个范围很小且结果可以独立验收的任务时，它可以把这个任务交给本机登记的其他模型后端，保存 job 和结果，再由顶层模型复核。普通并行仍优先原生子代理。",
    useWhen: ["任务封闭且有独立 verifier", "原生代理之外的 Backend 有明确净收益", "允许保存 job、result 和 receipt"],
    avoidWhen: ["普通子代理委派", "没有独立验收标准", "把显式 crosscheck 当 fallback", "云文本没有 cloud allowed"],
    inputs: ["有明确目标和 verifier 的 request JSON", "隐私是否允许云端"],
    outputs: ["job id、result 和 receipt", "由顶层模型独立验收后的结论"],
    flow: ["读取 live backends", "选择符合边界的一条 route", "submit", "按建议时间读取一次 job result", "保留 receipt，由顶层模型验收"],
    boundaries: ["不是原生 child（子代理）", "不自动 fallback（切换后备路线）", "失败不能冒充 complete（完成）", "registry（登记表）状态会漂移，必须现场读取"],
    dependencies: ["E:\\.agents\\config\\llm-backend-registry.json", "对应 Provider runtime"],
    tests: "专项测试、live backend listing、quick validation 和 metadata 语义断言全部通过。",
    sourcePath: "E:\\.agents\\skills\\llm-backend-toolkit\\SKILL.md"
  }),
  skill({
    slug: "native-economy-routing",
    name: "native-economy-routing",
    title: "原生代理经济路由",
    status: "已安装 / 宿主条件型",
    maturity: "B",
    summary: "当任务能拆成互不冲突、可以分别验收的支路时，它先确认当前工作台真实提供的模型、思考强度和父子角色，再判断开零到十个子代理是否真的能提高质量。每个子代理只拿必要范围，创建前再复核一次现场；身份不可靠时只关闭并行委派，主任务继续。",
    useWhen: ["任务出现独立可验支路", "上下文压缩或重大 steer 后需要重判", "child 完成或槽位释放", "当前任务确实需要原生并行"],
    avoidWhen: ["没有可信宿主身份", "普通工具步骤", "把代理名称当身份证明", "固定默认某个模型家族"],
    inputs: ["UserPromptSubmit（用户请求进入时）或 SubagentStart（子代理启动时）注入的 verified model（已验证模型）、effective effort（实际思考强度）、root/child（根/子代理）、turn hash（本轮指纹）、E release 与 contract SHA", "旧 root 完全没有 Hook（宿主钩子）或注入时，同一任务中用户已经给出的自然语言 model/effort 确认；确认层规范化别名，thread binding（任务绑定）只保存 canonical ID（规范标识）", "当前任务的独立支路、slots（并行槽位）、资源和写入冲突", "PreToolUse（工具创建前复核）在真实 spawn（创建子代理）前取得的身份、家族、effort 与参数"],
    outputs: ["0 到 10 的直属代理判断", "模型家族、effort、scope 和 fork 边界"],
    flow: ["root 的 UserPromptSubmit 或 child 的 SubagentStart 在 0–10 判断前注入可信身份与当前 E identity", "只有旧 root 完全没有 Hook 或注入时，才把同一任务中已有的自然语言 model/effort 确认规范化后写入并回读耐久 thread binding；child 不继承", "上下文压缩、E identity 变化或加载不确定时重读当前 11 条路由规则、重派生并刷新代际快照；E 换代本身不要求用户重复确认", "代理自己按任务语义、净收益、冲突和 slots 评估 0–10、模型家族与 effort", "真实 spawn 前由 PreToolUse Hook 复核 TOCTOU、家族上限、effort 上限和参数", "root 继续负责方向、集成和最终验收，不因派出 child 原地空等"],
    boundaries: ["Hook 只验证身份、E identity 与参数，不选择模型家族或代理数量、不创建 child，也不制造授权", "耐久 thread binding 只用于完全没有 Hook 或注入的旧 root，只落 canonical ID，child 不继承", "E release 换代不撤销已经成立的用户确认；规则明确撤销该路径或身份冲突时才失败关闭", "PreToolUse 只是 spawn 前复核，不能代替判断前的可信身份", "Hook 或有效绑定缺失只关闭委派，普通调查、实现和最终答复继续", "不依赖 Stop Hook；app version（应用版本）和 versioned path（带版本路径）不是准入条件", "委派只能收窄 scope、授权、家族和 effort，root 始终保留最终责任"],
    dependencies: ["宿主 UserPromptSubmit 与 SubagentStart Hook", "旧 root 的耐久 thread binding 入口", "真实 spawn 前的 PreToolUse Hook", "当前 E release 与 capability contract", "宿主原生 child identity（子代理身份）与 slots"],
    tests: "聚焦 Gate 与 Hook 回归覆盖判断前身份注入、旧 root 对话绑定、PreToolUse 创建前复核、无 Stop Hook 依赖和更新连续性；真实可用性仍由每个任务的宿主身份、E identity、授权与 slots 决定。",
    sourcePath: "E:\\.agents\\skills\\native-economy-routing\\SKILL.md",
    currentTaskState: "按本次 UserPromptSubmit 或 SubagentStart 注入的宿主身份与 E identity 现场判断；不沿用其他任务的 child 数量或回执",
    freshTaskState: "每个新任务必须重新取得自己的宿主身份；只有完全无 Hook 的旧 root 可建立耐久绑定，child 不继承",
    endToEndState: "判断前注入与创建前复核是两层独立证据；创建成功只证明该次宿主路径，每个任务仍需独立验证模型、effort、E identity 与结果"
  }),
  skill({
    slug: "token-budget-advisor",
    name: "token-budget-advisor",
    title: "工作台配额与 GPT-5.6 Sol 文本计量",
    status: "已安装 / 上次 Fresh task E2E 已验",
    maturity: "A",
    summary: "仅在用户明确询问当前工作台配额或 reset（重置）状态，或要求按 GPT-5.6 Sol 的权威口径计算、比较可见文本的模型计量单位（Token）时触发。配额走只读账号用量入口；Token 优先使用完成响应 usage 或官方 input_tokens，不能取得时返回 Unknown。",
    useWhen: ["用户明确询问当前工作台 quota（配额）或 reset（重置）状态", "用户明确要求按 GPT-5.6 Sol 统计可见文本 Token（模型计数单位）", "比较两个 Prompt（提示词）或文件的 Token 数", "接近明确 Token 边界，需要官方计数"],
    avoidWhen: ["仅仅因为任务长或可能压缩就自动触发", "推断隐藏 prompt、tools 或 reasoning", "把估算当成正式账单", "为了报告数字而回显用户正文"],
    inputs: ["明确的 quota/reset 问题，或一段可见文本/明确文件", "GPT-5.6 Sol 计数口径", "可选的明确 Token 数值预算"],
    outputs: ["只读配额/reset 状态，或 GPT-5.6 Sol 权威 Token 数", "使用的 usage/input_tokens 来源和没有计入的内容", "安全低于、接近、超过预算或 Unknown 的判断"],
    flow: ["配额问题读取只读 account/rateLimits 状态", "Token 问题优先使用响应 usage 或官方 input_tokens", "官方计数不可用时返回 Unknown", "只报告数字、方法、排除项和边界判断"],
    boundaries: ["不猜隐藏上下文", "不回显正文或账号标识", "不计算 API 价格或美元成本", "不把字符、字节或其他模型计数冒充 GPT-5.6 Sol"],
    dependencies: ["工作台只读 usage 状态入口或官方 input_tokens 计数"],
    tests: "Source、quick validation、autonomy、semantic、junction installer 和 supply contract 全部通过；Fresh 0.150.1 root 已发现并实际调用 Skill，o200k_base exact=3，预算 10 时返回 safely_below。",
    sourcePath: "E:\\.agents\\skills\\token-budget-advisor\\SKILL.md",
    freshTaskState: "Fresh root（全新根任务）已发现并实际使用",
    endToEndState: "Token 计数路径已有历史验收；当前配额/reset 只在用户明确请求时现场读取"
  })
];

export const excludedSkills = [];
