import { generatedPanelFacts } from "./panel-facts.generated.js";

const currentERules = generatedPanelFacts.authority;

function skill(definition) {
  return {
    provenance: "个人维护的能力入口",
    sourceKind: "personal_install",
    availability: "available",
    statusTone: "mixed",
    sourceState: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 中的唯一源码已核对`,
    installState: "canonical junction 已安装",
    transactionState: `${generatedPanelFacts.skills.transactionCampaignCount} 个供应事务全部终态；0 个坏事务`,
    currentTaskState: "本轮宿主回执未知",
    freshTaskState: "新任务回执未知",
    endToEndState: "按场景验收",
    evidenceObservedAt: `供应链现场：${generatedPanelFacts.observedAt}；项目场景按各项记录`,
    evidenceBasis: `.agents ${currentERules.releaseId} release ${currentERules.gitCommit.slice(0, 7)}、当前 Personal Skill supply（个人能力供应链），以及本页明确标注的既有项目/Provider（固定服务入口）证据；source/install/transaction 通过不冒充 current/fresh/E2E`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    supplyEvidenceCommand: "E:\\.agents\\tools\\Test-PersonalSkillSupply.ps1 -RequireInstalled -NoExternalEvidence -Json",
    ...definition
  };
}

export const skills = [
  skill({
    slug: "personal-media",
    name: "personal-media",
    title: "个人照片、视频与录音检索",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "用自然语言从本机受管媒体目录查找照片、视频和录音，打开原件，或生成一个可随时清理的临时浏览文件夹。",
    useWhen: ["记得画面、地点、文字、录音内容或大致日期，但不知道原件路径", "需要打开少量真实媒体原件", "需要把一组查询结果放进临时文件夹浏览", "需要明确区分图片、视频和音频"],
    avoidWhen: ["查找 Word、PDF 等非媒体原件", "按人物大范围扫描媒体库", "删除、修改或上传媒体", "重建第二套索引、服务或后台任务"],
    inputs: ["1 到 4 个能出现在内容中的区分词", "可选地点、描述、分类、媒体类型和日期", "明确要求完整集合时才使用 all"],
    outputs: ["少量可读候选和绝对原件路径", "媒体类型、已知日期、地点、分类和匹配依据", "按请求创建的同卷 hardlink 浏览目录", "零命中时的真实过滤条件和覆盖缺口"],
    flow: ["把用户原话压缩成最小可靠过滤条件", "用 SQLite 条件和 FTS 执行小结果 search", "核对权威原件定位记录确实指向现存原件", "需要浏览时创建 task-unique hardlink 文件夹", "身份问题只把选中的少量原件交给 person:self 能力", "用户不再需要时只清理那个受管浏览目录"],
    boundaries: ["私密项默认隐藏，只有用户明确要求才包含", "地点只表示已复核的拍摄现场，文字里的地名走 query", "不使用当前没有证据的人物过滤", "不读取完整 NDJSON、全盘扫描或复制媒体进知识库", "浏览清理绝不删除原件"],
    dependencies: ["V:\\Personal\\Projects\\personal-media", "E:\\Media\\_manifests\\personal-media-current\\catalog.sqlite3", "E:\\Pictures、E:\\Videos 与 E:\\Music\\录音 canonical roots"],
    tests: "个人媒体项目当前 31 项测试通过、2 项按环境跳过；Skill source、quick validation、junction 和 transaction 均通过。",
    sourcePath: "E:\\.agents\\skills\\personal-media\\SKILL.md",
    endToEndState: "本地 search、browse 和 clean 契约已验"
  }),
  skill({
    slug: "personal-materials",
    name: "personal-materials",
    title: "私有原件定位",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "当文件路径已经忘记、需要跨多个已批准位置查找，或原有定位失效时，用自然语言找到少量经核对的非媒体原件。",
    useWhen: ["知道材料是什么，但不知道它放在哪里", "一个既有 locator 已失效，需要重新发现", "需要在几个已批准位置之间查找同一份非媒体原件"],
    avoidWhen: ["照片、视频或录音", "已经有可靠精确路径", "需要领域判断而不是找原件", "要求全盘扫描或批量建立索引"],
    inputs: ["对材料内容、名称、时间或用途的自然语言描述", "可选的已批准位置或已知 locator"],
    outputs: ["最多几个经核对的候选", "候选的真实原件路径和匹配依据", "零命中时的检查范围、上限和未覆盖缺口"],
    flow: ["先执行有界 find", "必要时进入 discover", "核对候选的路径、hash 和内容特征", "选定后 open 或 open-discovered", "把找不到和未覆盖范围说清"],
    boundaries: ["不扫描媒体库", "不复制或改写原件", "不建立中央个人资料库", "hash 漂移后拒绝沿用旧定位"],
    dependencies: ["V:\\Personal\\Projects\\personal-materials", "项目自己的 locator 和边界配置"],
    tests: "9 项测试通过，覆盖自然查询、零命中、hash drift、媒体拒绝和有界发现。",
    sourcePath: "E:\\.agents\\skills\\personal-materials\\SKILL.md",
    endToEndState: "核心自然查询已验"
  }),
  skill({
    slug: "wechat-direct",
    name: "wechat-direct",
    title: "微信上下文与具名归档",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "读取一段微信对话及回复关系、打开相关媒体，或维护一个明确联系人或群的可重放本地归档。",
    useWhen: ["回答一个聊天中的上下文问题", "读取某个具名联系人或群的历史", "打开聊天中对应的图片、语音或文件", "读取当前已缓存的朋友圈内容"],
    avoidWhen: ["一次同步整个账号", "后台持续同步", "没有明确联系人或范围", "把聊天材料复制到第二数据库"],
    inputs: ["联系人或群名", "账号、时间范围或消息线索", "归档时的单一具名目标"],
    outputs: ["按原生顺序排列的小范围上下文", "消息回复关系和相关媒体", "单一目标的增量归档或朋友圈缓存结果"],
    flow: ["读取项目当前入口说明", "聊天问题走 context", "完整具名历史走 sync-contact", "媒体走 media-open", "朋友圈走 moments 或 sync-moments"],
    boundaries: ["一次只处理一个具名联系人或群", "不做全账号后台任务", "缓存 miss 不冒充无数据", "语音转写交给中文 ASR"],
    dependencies: ["E:\\Projects\\Tools\\WeChatDirect", "中文 ASR 用于语音媒体"],
    tests: "39 项测试通过，覆盖账号身份、原生顺序、回复、媒体、增量归档和朋友圈缓存。",
    sourcePath: "E:\\.agents\\skills\\wechat-direct\\SKILL.md",
    endToEndState: "主要读取和归档路径已验"
  }),
  skill({
    slug: "google-workspace-direct",
    name: "google-workspace-direct",
    title: "Google Workspace 固定入口",
    status: "已安装 / 固定 Google Workspace 服务入口已配置",
    maturity: "A-",
    summary: "需要查自己的 Gmail、Google Drive 或日历时，它固定使用已经登记的同一个账号读取；只有系统确实提供对应写入能力、而且用户明确要求时，才会修改外部内容。",
    useWhen: ["按条件查邮件", "查找或导出 Drive 文件", "读取日历事件", "需要原生 Google Docs 导出"],
    avoidWhen: ["切换其他账号", "静默改走浏览器、公共 Connector 或 rclone", "Provider 没有暴露目标写操作", "Google Photos、Admin 或支付"],
    inputs: ["窄查询、对象 ID 或时间范围", "写操作时的精确对象、内容和动作授权"],
    outputs: ["最小必要邮件、文件或日历结果", "原生文档导出", "写操作的 Provider 回执与 read-back"],
    flow: ["选择固定 Provider 的精确 operation", "默认执行只读", "原生文档必须走 Drive export", "写入前核对 Provider 能力和授权", "按同一 Provider read-back"],
    boundaries: ["不落中央库", "不自动同步", "不换账号或第二 Provider", "删除、发送、邀请和公开分享需要精确授权"],
    dependencies: ["PCConfig 的 google-workspace.primary Provider", "已登记 OAuth 绑定"],
    tests: "Provider binding、action 和 install 三组测试通过；本次未重新验证在线账号身份。",
    sourcePath: "E:\\.agents\\skills\\google-workspace-direct\\SKILL.md",
    endToEndState: "在线身份本轮未复核"
  }),
  skill({
    slug: "chinese-asr",
    name: "chinese-asr",
    title: "中文录音转写与说话人证据",
    status: "已安装 / 正式环境回归通过",
    maturity: "A",
    summary: "处理中文和微信录音的转写、时间戳、匿名说话人聚类、本人语音归属，以及重要录音的本地或受控云端交叉验证。",
    useWhen: ["需要中文录音全文和时间戳", "需要区分匿名说话人 cluster", "需要判断精确句段是否支持 person:self", "重要专业录音需要双链验收"],
    avoidWhen: ["扫描整个音频库", "把 cluster 数直接当真实人数", "把 ASR 当逐字法律证书", "timeout 后盲目重新提交同一 job"],
    inputs: ["一个具名音频或视频音轨", "模式、时间范围和必要的说话人证据边界", "云路线需要明确双开关授权"],
    outputs: ["转写文本、时间戳和匿名 cluster", "objective sidecar 与 job 状态", "本人归属的精确句段、覆盖范围和不确定性"],
    flow: ["普通录音走 strict", "长录音走 long-strict", "说话人先聚类再对精确句段做 held-out attribution", "重要录音按授权进入唯一云路线", "以原音频为权威复核结果"],
    boundaries: ["原音频始终高于转写", "云失败不能伪装成本地成功", "其他说话人保持匿名", "空文本和超时不能自动解释为没有内容"],
    dependencies: ["E:\\Projects\\Tools\\ChineseASR", "模型 registry", "LocalGpuBroker", "本地私有 person:self profile"],
    tests: "2026-08-31 项目正式 Python 3.11 venv 的当前全量回归为 345 tests OK，关键 15 项定向验证全部通过，doctor 也确认 Qwen、FunASR 与 PyTorch 已安装。",
    sourcePath: "E:\\.agents\\skills\\chinese-asr\\SKILL.md",
    endToEndState: "正式 venv 与主要模型链已验"
  }),
  skill({
    slug: "timeaudit-diagnostics",
    name: "timeaudit-diagnostics",
    title: "TimeAudit 有界历史诊断",
    status: "已安装 / 12 项 provider 合同测试与一小时真实查询通过",
    statusTone: "pass",
    maturity: "A",
    summary: "当电脑的卡顿、发热、磁盘/网络、掉帧、睡眠或采集断档需要历史证据时，用一次有界聚合查询回答“这段时间实际覆盖了什么、出现了哪些相关信号、还缺什么”；它不是 TimeAudit 控制器，也不会把相关性冒充根因。",
    useWhen: ["间歇性电脑问题已经过去，需要回看 1 到 168 小时内的历史", "需要先区分没有异常、没有游戏帧和根本没采到数据", "硬件、FPS、睡眠或采集覆盖会改变当前诊断结论", "需要把历史聚合与 Windows、驱动、任务或 PCConfig 现场证据对齐"],
    avoidWhen: ["只需要此刻的实时状态", "想控制、启动、停止或修复 TimeAudit", "需要逐进程或逐窗口明细而当前 aggregate-only 接口不能回答", "试图用一次阈值信号证明硬件损坏、恶意程序或用户意图", "把超过 168 小时拆成大量窗口暴力查询"],
    inputs: ["具体电脑问题与尽可能窄的时间范围", "最近事件可用 1–168 小时，具名事件使用精确 UTC 起止", "需要关联的 Windows、驱动、任务或 PCConfig 现场证据"],
    outputs: ["请求窗口、覆盖新鲜度、样本数、边界/内部最大空档", "CPU/GPU、内存、磁盘、网络与有效游戏帧的聚合摘要", "active/idle/display-off/lock/sleep 的区间并集时长和未覆盖时间", "阈值 occurrence（出现次数）、因果限制、真实缺口与下一项安全诊断动作"],
    flow: ["选择能改变判断的最短时间窗", "调用固定 `timeaudit_diagnostic_summary.py` 一次", "验证 schema、owner、status、窗口、coverage、样本和输出省略标志", "只有 game_performance.status=observed 时解释 FPS/1% Low/frametime", "把信号与实时状态和其他 Owner 证据关联", "先给实用结论，再说明窗口、关键聚合、缺口和下一步"],
    boundaries: ["TimeAudit 只是可选历史证据，不单独证明根因", "单次窗口最多 168 小时，不网格化暴力查询", "provider 为速度与语义稳定只返回聚合；进程、路径、标题等字段类别并非天然敏感，可由其他合适路线在有价值时使用", "不调用 Grafana、db_audit、PCConfig cursor 或采集控制入口", "provider unavailable/stale/empty 时回到普通诊断，不把缺数据写成健康"],
    dependencies: ["E:\\Projects\\Tools\\TimeAudit\\timeaudit_diagnostic_summary.py", "TimeAudit 本机 PostgreSQL 容器", "E:\\Projects\\Tools\\TimeAudit\\TIMEAUDIT_DIAGNOSTIC_SUMMARY_CONTRACT.md"],
    tests: "TimeAudit main 44a842e 的 diagnostic summary provider 合同与测试仍在当前源码；本轮 `--hours 1` 真实查询返回 schema timeaudit.diagnostic-summary.v1、status=ok、coverage=fresh、3702 个样本，最新样本年龄约 0.77 秒，8 个 privacy flag 均为 false。",
    sourcePath: "E:\\.agents\\skills\\timeaudit-diagnostics\\SKILL.md",
    sourceState: `Skill 初始实现来自 d719dea；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与 source/install 供应验证分别回读通过`,
    currentTaskState: "本轮一小时真实 provider 查询通过，未控制或重启任何 TimeAudit 组件",
    freshTaskState: "来源 Owner 的 projectless 任务已发布并回读 Skill 与 provider",
    evidenceObservedAt: `当前 Skill 来源/安装供应回读：${generatedPanelFacts.observedAt}；一小时真实查询现场：2026-08-31 12:13（中国时间）`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 中可发现的 TimeAudit diagnostics Skill、TimeAudit PUBLIC main 44a842e 的 provider/contract/tests，以及既有一小时真实聚合查询；源码、安装、provider 现场与因果结论保持分层。`,
    endToEndState: "固定 Skill → 有界 provider → schema/coverage/聚合解释的真实一小时路径已验"
  }),
  skill({
    slug: "localocr",
    name: "localocr",
    title: "本地精确 OCR",
    status: "已安装 / 上次服务与 E2E 已验",
    maturity: "A",
    summary: "遇到扫描 PDF、多页图片、表格、公式、印章或需要坐标的材料时，它在本机把图片里的文字和版面读出来；普通一两张清晰截图仍直接用原生视觉。",
    useWhen: ["扫描 PDF 或多页图片", "需要表格、公式、版面和坐标", "材料必须本地处理", "普通一两张截图的原生视觉无法可靠读取"],
    avoidWhen: ["一两张清晰普通截图", "把空文本直接理解成没有文字", "timeout 后重复创建同一 job"],
    inputs: ["图片、PDF 或明确文件夹", "engine、版面模式和输出格式"],
    outputs: ["txt、Markdown 或 JSON", "object sidecar、坐标和结构信息", "job、route 和失败层级"],
    flow: ["普通图片先原生视觉", "复杂任务走 ocr smart 的 auto 路线", "必要时显式 structure", "复用返回的 job 和 output", "区分 deadline、broker、配置和识别失败"],
    boundaries: ["不把 timeout 124 当 OCR 失败", "不把空文本当否定结论", "不把本地引擎结果冒充人工视觉校正", "GPU 重载必须串行"],
    dependencies: ["E:\\Projects\\Tools\\LocalOCR", "WSL Python", "PaddleOCR", "LocalGpuBroker"],
    tests: "当前 WSL venv 使用 pytest 9.1.1；141 项 pytest 通过、1 跳过，官方 unittest 142 tests OK、1 跳过，wrapper timeout/objective 专项 24 通过、1 跳过。真实 18,980 字节图片在 12.339 秒完成 auto→ocr，识别三行文字，objective 与 job sidecar 均正式回读。",
    sourcePath: "E:\\.agents\\skills\\localocr\\SKILL.md",
    endToEndState: "真实小图片 OCR、objective 和 sidecar 已验"
  }),
  skill({
    slug: "personal-health",
    name: "personal-health",
    title: "个人健康上下文",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "回答本人的健康、用药、过敏、检查、趋势、睡眠和活动问题，并在收到新报告或明确刷新设备数据时更新当前健康事实。",
    useWhen: ["问题取决于本人的当前健康资料", "需要解释新检查报告", "需要刷新已登记健康设备数据", "高风险健康建议需要结合权威医学资料"],
    avoidWhen: ["与本人无关的通用健康问题", "恢复旧中央个人系统", "把模型建议写成医生结论", "建立持续后台同步"],
    inputs: ["健康问题、新报告或明确纠正", "设备刷新时的已登记数据入口"],
    outputs: ["基于 CURRENT 的当前回答", "事实、医生意见、模型建议和未知的明确分层", "经 Health Owner 审核的更新"],
    flow: ["普通问题先读完整 CURRENT", "高风险问题再查权威指导", "新报告走 capture 和 brief", "由 Health Owner 复核后更新", "保持 unknown 和证据日期"],
    boundaries: ["不读旧记忆代替 CURRENT", "不建中央画像", "不自动持续同步", "不把建议和事实混写"],
    dependencies: ["个人健康项目的 CURRENT", "高风险问题的权威医学来源"],
    tests: "2026-08-31 项目当前 112 项合成回归通过；它不代表真实账号或医学 E2E。供应元数据已修复并通过 320 字符预算与 quick validation。",
    sourcePath: "E:\\.agents\\skills\\personal-health\\SKILL.md"
  }),
  skill({
    slug: "daily-preferences",
    name: "daily-preferences",
    title: "日常偏好与个性化推荐",
    status: "Source（源码）、安装、当前状态、全新任务发现与真实推荐 E2E（端到端）均已验收",
    statusTone: "pass",
    maturity: "A-",
    sourceKind: "personal_install",
    summary: "记录和纠正用户本人尚未由专门领域拥有的当前偏好，再用薄快照和会改变本次决定的最小证据，给出可纠正的美食、购物、支付与消费习惯、出行与旅行住宿、娱乐与数字消费、服务工具、审美和日常决策建议；当前同范围的直接表达始终高于旧记录。",
    useWhen: ["用户本人明确说喜欢、不喜欢、以后想怎样选，或表示自己改主意了", "想根据既有偏好获得美食、购物、支付与消费习惯、出行、旅行景点、住宿、娱乐或数字消费推荐", "要在服务选择、工具习惯、审美或其他没有专门领域 Owner 的日常取舍中得到个性化建议", "需要解释一次购买、用餐、支付或服务选择背后的偏好，并允许后续纠正", "用户明确说“准备投递增量”，需要先查看各来源覆盖与缺口"],
    avoidWhen: ["医学饮食、过敏、用药或治疗限制，应以个人健康入口为主", "预算、债务、还款、授信或资产配置，应交给资产领域", "卡号、密码、登录或执行真实付款，应交给本地凭据入口", "合同、私人专业事务文书或其他正式材料，应交给文书和材料制作入口", "对象、朋友或其他人的偏好，不能由用户本人的消费史代替", "PRD、代码、职业、项目或产品设计，不读取私人偏好快照"],
    inputs: ["用户当前直接表达的喜欢、不喜欢、理由、纠正或改变想法", "一个关于吃喝、购物、支付消费、出行旅行、住宿、娱乐、数字消费、服务工具、审美或日常决策的自然问题", "只有用户明确准备投递增量时，才接收其提供的具名来源包"],
    outputs: ["同范围最新明示成为 current（现行偏好）、旧表述保留为 historical（历史偏好）的可纠正记录", "每个开放领域至少 3 个熟悉稳妥、3 个相邻探索和 3 个明确标为推测的新鲜尝试组成的选择菜单；还有显著不同路线时继续列，不用同款变体凑数", "每个候选的具体内容或规格、适合理由、关键取舍，以及必要的粗略价格、场景或搜索词", "支撑本次排序的最小证据、事实核对、未知和可复制的搜索接力", "增量投递前逐 source instance（来源实例）的实际覆盖截止或快照时间、缺口、原始材料、重叠起点、full/incremental 模式与未取得逻辑来源，以及材料到齐后的投递结果"],
    flow: ["用户直接表达偏好时，运行完整动作 `pwsh -NoProfile -File V:\\Personal\\Projects\\daily-preferences\\daily-preferences.ps1 record --key <preference-key> --statement <用户原话>`；同范围最新明示成为 current，旧表述只保留为 historical", "普通推荐先读取 `E:\\PersonalData\\日常偏好\\CURRENT.md`；薄快照不存在或过期时继续查最小证据，不把缺快照说成用户没有偏好", "运行完整动作 `pwsh -NoProfile -File V:\\Personal\\Projects\\daily-preferences\\daily-preferences.ps1 evidence --query <用户自然问题> --limit 24 --json`；开放题按会改变选择的轴补查，不能把一包最高分命中冒充全貌", "优先保留具体商品、口味、规格或菜品原名；order observation（订单观察）只证明买过或点过，结合 repeat count（重复次数）、跨时间复购和真实 user expression（用户表达）才支持偏好推定，payment observation（支付观察）不重复计算已有详细订单", "准备把具体商品或品类写成复购偏好、或解释为什么时，运行 `facts --term <品牌或核心词> --term <品类词> --json` 核对成功与关闭次数、时间范围和文本变体；商家模板、赠品、未选选项、替他人询问、假设或单纯疑问都不能升级成用户偏好", "只有冲突、过度概括、索引过期或原件细节会改变候选时，才按 locator（原件定位）有界读取原件；媒体和非媒体原件继续由各自入口保管", "开放式推荐把历史当排序依据而不是白名单；每个开放领域至少给 3 个熟悉稳妥、3 个相邻探索和 3 个标明依据的推测新选项，还有显著不同路线时继续列，不用同款变体凑数；每项用一两句说明具体内容、理由和取舍", "实时平台信息有帮助时只给与本次需求匹配的 1–2 个平台和可复制关键词，不冒充权威最低价，也不替用户下单或付款", "用户说“准备投递增量”时，先运行完整动作 `pwsh -NoProfile -File V:\\Personal\\Projects\\daily-preferences\\daily-preferences.ps1 status --json`；逐个 source instance 说明实际覆盖截止，Unknown 时给快照时间，并列缺口、原始材料、重叠起点、full/snapshot/incremental/manual 模式；不同 ChatGPT 账号与 Gemini 快照分别列出，5 个未取得逻辑来源也单列。用户提供材料后才运行 `ingest`，完整权威快照才用 full，普通补包使用 incremental"],
    boundaries: ["当前同范围明示优先，明确回顾过去并给出日期的旧记录不能覆盖现行偏好", "只保留薄快照和会改变当前选择的最小证据，原件留在各自 Owner，不移动、覆盖或删除", "单次订单或付款不自动证明喜欢，偏好推定必须保留具体依据并允许接受、拒绝和纠正", "不输出星座式人格标签，不建立中央个人画像、向量库、服务、队列、第二状态库或后台同步", "不替代个人健康、预算资产、本地凭据与真实付款、文书和材料制作、他人关系偏好或工作产品设计", "除非用户明确只要一个选择，否则不替用户作唯一决定、固定套餐、下单或付款"],
    dependencies: ["V:\\Personal\\Projects\\daily-preferences", "E:\\PersonalData\\日常偏好\\CURRENT.md", "偏好原件仍由各来源 Owner 保管"],
    tests: `2026-09-01 的个人 Skill 供应核对显示 source（源码）、quick validation（快速校验）与 canonical junction（规范目录联接）通过，${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent（活动安装意图）和 ${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 个终态事务闭合；实现项目 PRIVATE main=3860c61，23/23 测试通过，current 快照一致，全新无提示任务能自主选择该入口，开放推荐 E2E 的用户评分为 8/10，独立饮料快照盲测保留具体商品语义并回溯复购事实。`,
    sourcePath: "E:\\.agents\\skills\\daily-preferences\\SKILL.md",
    sourceBytes: 6889,
    sourceSha256: "b0b4735c37fae0eb4c675740993665f4500f838b6342e72aa2f2a06d349ca552",
    sourceState: `canonical Skill 源码已在干净的当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 核对并由 PRIVATE main 远端回读`,
    installState: "canonical junction 已安装并指向唯一源码",
    currentTaskState: "PASS（通过）；16 条 current 用户明示与 6 个 current 快照的 revision 已核对一致",
    freshTaskState: "PASS（通过）；全新无提示任务能自行选择 daily-preferences",
    evidenceObservedAt: `供应链与项目验收现场：${generatedPanelFacts.observedAt}`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `canonical SKILL.md（规范能力说明）的 bytes/hash（字节数/指纹）、当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 的 PRIVATE main 远端回读、实现项目 PRIVATE main=3860c61、${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent（活动安装意图）、canonical junction（规范目录联接）、${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 个终态事务、23/23 项目测试、current 快照一致性、全新无提示任务发现与两条真实推荐/增量验收；任何私人偏好正文均未进入网页。`,
    endToEndState: "PASS（通过）；开放推荐用户评分 8/10；饮料盲测保留具体商品语义并回溯复购；自然增量请求能逐项说明 11 个来源实例的覆盖、缺口、重叠与模式，并单列 5 个未取得逻辑来源"
  }),
  skill({
    slug: "document-materials",
    name: "document-materials",
    registryName: "personal-formal-documents",
    title: "文书和材料制作",
    status: "已安装 / 全新任务已发现 / 主要场景未全部实测",
    maturity: "A-",
    summary: "围绕一份当前材料状态和可靠原件，起草或修订合同、通知、信访/投诉、售后索赔、争议函件、申请材料和提交包；制作前核对事实与证据，完成后逐页检查格式与证据，把材料已生成、本人已操作、平台已收到和接收方已处理分开，明确期限、恢复点并避免重复操作。",
    useWhen: ["起草或修订合同、协议、通知和协商修改稿", "把已经核对的事实整理成信访/投诉、售后索赔或一般争议函件", "制作申请材料、回复、证据清单或完整提交包", "核对当前材料状态、期限和恢复点并避免重复操作"],
    avoidWhen: ["没有原件或事实依据就要求补写内容", "PRD、PPT、电子表格、项目计划或持续工作交付包，应进入文档、演示、表格或工作交付入口", "既有私人争议的进度或专属事项卡，应进入对应私人专业事务入口", "通用翻译、随手文案或他人的事务，不进入本人的正式材料路线", "把材料已生成当成本人已操作", "把平台已收到当成接收方已处理", "未经精确授权替本人提交、付款、撤回或联系外部接收方"],
    inputs: ["当前材料状态、目标和期限", "最小必要原件、已确认事实与证据", "接收方式、格式要求和附件清单", "需要外部动作时对精确对象、内容与动作的授权"],
    outputs: ["一条当前结论、理由和下一步", "已确认事实、可逆推断与真正未知的分层", "经过完整审阅、逐页格式检查和证据验收的合同、通知、投诉/索赔函件、证据清单或提交包", "材料已生成、本人已操作、平台已收到、接收方已处理的独立状态"],
    flow: ["读取当前材料状态", "只打开会改变判断的必要原件", "把事实、证据、未知、期限和下一步分开", "按真实用途制作合同/协议、通知、信访/投诉、售后索赔、争议函件、申请材料或提交包", "完整审阅并逐页完成格式与证据验收", "外部动作完成后从真实平台、接收记录或本人说明回读现实状态", "中断后从最近一次已核对成品和状态继续，避免重复操作"],
    boundaries: ["私人事实、原件、草稿、签名和成品不进入公开 Git", "本人一手陈述是已确认事实，真正不确定的时间、原话或原因继续保留未知", "材料已生成不等于本人已操作，平台已收到也不等于接收方已处理", "不新建数据库、服务、后台同步或第二套材料系统"],
    dependencies: ["受保护的当前材料状态与原件", "正式文书与材料生成、逐页渲染和校验入口", "必要时的原件定位、消息上下文、录音转写或扫描识别能力"],
    tests: `现行 Skill 源码、快速校验、canonical junction（规范目录联接）与 ${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 供应事务均通过；安装后的全新 Sol Max 任务已准确发现名称、说明和路径。本轮没有调用 Skill，也没有把合同/协议、通知、信访/投诉、售后索赔、争议函件、申请材料与提交包冒充为全部 E2E（端到端）通过。`,
    sourcePath: "E:\\.agents\\skills\\personal-formal-documents\\SKILL.md",
    sourceBytes: 2159,
    sourceSha256: "a006fe6a82423935c4a058a02d9d91f031518ba91fa7d6e5757009bc6fb3503f",
    sourceState: `Skill 内容在 1870d6f 已正式回读；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与供应安装现场另行回读，各层分开说明`,
    installState: "canonical junction 已安装并与规范源码一致",
    currentTaskState: "本轮未制作或提交真实材料",
    freshTaskState: "安装后的全新 Sol Max 任务已发现 personal-formal-documents；发现通过不等于领域执行通过",
    evidenceObservedAt: `当前供应链：${generatedPanelFacts.observedAt}；安装后全新任务发现：2026-08-31`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `.agents 1870d6f 的 personal-formal-documents Skill 内容、当前 source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId}、${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent、${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 终态事务和安装后全新任务发现；Skill 内容代、当前源码和活动规则身份保持分层。`,
    endToEndState: "公开请求族本轮未全部完成真实 E2E（端到端）验收；只报告各自已有证据，不作全量通过声明"
  }),
  skill({
    slug: "work-delivery",
    name: "work-delivery",
    title: "工作交付副驾驶",
    status: "已安装 / 全新任务已发现 / 首版领域 E2E 本轮未重跑",
    maturity: "B+",
    summary: "把用户明确选中的需求、会议记录、规则和表格冻结成可追溯来源，分开事实、假设、冲突和未知，再从同一事实版本生成 PRD（产品需求文档）、项目计划、评审 PPT（演示文稿）、执行表、周报和汇报。来源变化后，它指出哪些事实和旧成品受到影响，而不是把整套材料悄悄重写。",
    useWhen: ["一个持续工作事项有 2–5 份明确来源，并且需要两类以上相互一致的交付物", "需求或来源会继续变化，需要知道哪些事实和成品已经过期", "需要让 PRD、项目计划、评审 PPT、执行表、周报/汇报和追溯清单使用同一口径", "要继续一个已经存在的交付包，而不是重新整理全部材料"],
    avoidWhen: ["只编辑一次单个 Word、PPT 或表格", "没有用户明确选择来源就扫描目录、账号或旧对话", "学习、职业发展、求职或私人文书材料", "未经精确授权发送、发布、审批、建任务或修改外部系统"],
    inputs: ["用户明确选择的 2–5 份需求、会议记录、规则、表格或其他工作资料", "新持续事项的稳定且非空 package ID、标题和目标；已有交付包使用原 ID 进入更新命令", "交付目标、受众、范围、期限和需要生成的产物", "需要确认或驳回的候选事实、冲突、假设和未知", "中国工作或个人配置，以及时区、币种、角色词表和 Office/WPS 兼容要求"],
    outputs: ["带来源定位的事实修订版、未解决冲突和 manifest 的 quality 状态", "使用同一事实版本生成的 PRD、项目计划、评审 PPT、执行跟踪表、周报或汇报", "Markdown/JSON/CSV 预览和追溯清单", "来源变化后的影响清单、过期成品和唯一待决定事项"],
    flow: ["新持续 PRD 使用一个 work-delivery.batch.v1 请求提交 package ID、标题、目标、2–5 份明确来源和所需产物，不为每份来源/事实各启一个进程", "为每份来源保存不可变快照、内容指纹和可定位证据片段", "把事实、假设、冲突和未知分开，由用户确认真正影响交付的项目", "只有 manifest 报告 quality.status=ready 才调用正式 Office 构建；只要 PRD 时只请求 docx，不等待 PPTX/XLSX", "已有 package ID 通过普通更新命令继续，重复创建同 ID 是显式错误", "来源更新时比较新旧快照，只标出受影响事实和旧构建", "用户确认后生成下一版并保留前后差异"],
    boundaries: ["一次性单文件或无持续来源/version上下文的 PRD 直接使用现成文档、演示或表格能力，不增加交付包", "普通 2–5 份来源约 5 分钟内给出覆盖、关键事实、冲突/缺口、结构或准确的复杂度感知 ETA；最终时间按来源长度、冲突数、输出规模、模型实际速度和同模型/同质量直接处理基线判断，不设固定完成截止线压低质量", "事实已经确认后，确定性 PRD.md + DOCX 构建在当前机器上的目标不超过 15 秒；只要 PRD 时不等待 PPT 或 XLSX", "缺目标、范围、需求、异常、验收、证据或存在关键冲突时，quality 不得 ready，正式 Office builder 不运行", "不扫描未选目录、账号、仓库或旧对话，不建立长期个人记忆", "不建设后台同步、连接器平台、向量库、消息队列或第二状态库", "外部发送、发布、审批、邀请和修改必须由当前请求另行精确授权"],
    dependencies: ["V:\\Personal\\Projects\\work-delivery-copilot", "E:\\.agents\\skills\\work-delivery\\SKILL.md", "现有文档、演示文稿和电子表格能力作为正式产物渲染器"],
    tests: `Skill 源码、快速校验、canonical junction（规范目录联接）和 ${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 供应事务通过；安装后的全新 Sol Max 任务已准确发现 work-delivery。当前 Skill 已明确 batch.v1 单命令新建、稳定 package ID、重复 ID 拒绝、quality.ready 构建门、复杂度感知 ETA 和 PRD-only 不等待其他产物；本轮没有调用 Skill 或重跑领域 E2E。`,
    sourcePath: "E:\\.agents\\skills\\work-delivery\\SKILL.md",
    sourceBytes: 4530,
    sourceSha256: "2fcba1a69b0f73cb45dac06e967ab98cffb04c0e1011ec1f81b6245d6c6428ff",
    sourceState: `Skill 内容在 1870d6f 已正式回读；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与供应安装现场另行回读，各层分开说明`,
    installState: "canonical junction 已安装并与规范源码一致",
    currentTaskState: "本轮未创建真实工作交付包",
    freshTaskState: "安装后的全新 Sol Max 任务已发现 work-delivery；发现通过不等于领域执行通过",
    evidenceObservedAt: `当前供应链：${generatedPanelFacts.observedAt}；安装后全新任务发现：2026-08-31`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `.agents source 1870d6f 的 work-delivery Skill、当前 source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId}、work-delivery-copilot main cc0f9fe 的当前产品合同、${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent、${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 终态事务和安装后全新任务发现；未使用源码、安装或发现回执冒充领域执行验收。`,
    endToEndState: "Skill discovery（能力发现）通过；真实交付包创建、跨产物构建、来源变化影响分析与自然语言路由 E2E 本轮 Unknown（未知）"
  }),
  skill({
    slug: "documents",
    name: "documents",
    title: "可编辑 Word 文书与逐页验收",
    status: "宿主已集成 / 本轮未跑真实文档",
    statusTone: "mixed",
    maturity: "A-",
    provenance: "宿主集成能力",
    sourceKind: "host_integrated",
    capabilityId: "host:documents",
    evidenceSourceCommit: null,
    summary: "创建、编辑、修订或批注 DOCX（可编辑 Word 文档）时，先按文档用途选结构和样式，再把成品渲染为逐页图片检查裁切、重叠、字体、表格与页眉页脚；只有最后一轮逐页目检通过才交付可编辑文书。",
    useWhen: ["创建或编辑 DOCX / Word 文书", "需要修订痕迹、批注、表单或内容控件", "需要把本地 DOCX 导入原生 Google Docs", "版面、表格、页眉页脚和逐页视觉质量会影响交付"],
    avoidWhen: ["只需要普通纯文本回答", "只读 PDF 而不处理 Word 文档", "把文字提取或 OOXML（Word 文档内部结构）检查当成版面验收", "用户只要最终 DOCX 时交付内部 PNG 或调试 PDF"],
    inputs: ["目标内容、受众、用途与输出格式", "可选模板、参考 DOCX 或必须保留的原结构", "需要修订、批注、表单或 Google Docs 导入时的精确要求"],
    outputs: ["可编辑 DOCX", "需要时的修订、批注、表单或原生 Google Docs 成品", "内部逐页 PNG 目检与结构检查结果"],
    flow: ["发现宿主 workspace 依赖", "按模板或文档类型固定结构与样式 token", "创建或做最小局部编辑", "渲染全部页面为 PNG", "逐页检查并修复后重新渲染", "只交付用户要求的最终文档"],
    boundaries: ["bundle（随宿主发布的能力包）版本只记录本次观察，不作为未来准入", "每个有意义的编辑批次后重新渲染并逐页检查", "Google Docs 新文档先生成并验收本地 DOCX，再走原生导入", "LibreOffice 缺失时必须明确说明未完成视觉门，其他渲染错误先修复"],
    dependencies: ["Codex bundled workspace dependencies", "宿主当前 documents capability（文档能力）"],
    tests: "宿主源码与集成状态可发现；本轮未创建或编辑真实 DOCX，Current/Fresh/E2E 保持 Unknown。",
    sourcePath: "host:documents",
    observedSourcePath: "C:\\Users\\10979\\.codex\\plugins\\cache\\openai-primary-runtime\\documents\\26.826.12353\\skills\\documents\\SKILL.md",
    sourceBytes: 42857,
    sourceSha256: "adb4fa343854795dcb724871b66c5e05ba537d110a62ecc700fa2f44967a0295",
    evidenceSourceCommit: null,
    sourceState: "宿主 bundle canonical source（规范源码）已核对",
    installState: "宿主已集成；按稳定能力发现，不以 bundle 版本准入",
    transactionState: "宿主集成能力不经过个人 Skill 安装事务",
    currentTaskState: "本轮未创建或编辑真实 DOCX",
    freshTaskState: "Fresh task（全新任务）回执 Unknown（未知）",
    endToEndState: "真实文档创建、渲染与逐页验收 E2E 本轮 Unknown",
    evidenceObservedAt: "宿主 bundle 26.826.12353：2026-08-31 本轮观察",
    evidenceBasis: "宿主集成 documents capability（文档能力）的源码身份只由结构化来源字段记录；宿主版本不成为准入，本轮没有真实文档 E2E。",
    supplyEvidenceCommand: "Codex workspace dependency loader（工作区依赖发现入口）"
  }),
  skill({
    slug: "pdf",
    name: "pdf",
    title: "PDF 读写、表单与逐页验收",
    status: "宿主已集成 / 本轮未跑真实 PDF",
    statusTone: "mixed",
    maturity: "A-",
    provenance: "宿主集成能力",
    sourceKind: "host_integrated",
    capabilityId: "host:pdf",
    evidenceSourceCommit: null,
    summary: "读取、生成、检查或填写 PDF 时，同时核对内容结构与真实页面；交互表单还要检查 AcroForm（PDF 表单字段树）、页面控件、字段值和外观流，不能用“画面看见值”冒充字段已经正确写入。",
    useWhen: ["读取或审阅版面重要的 PDF", "程序化生成正式 PDF", "填写并验证交互式 AcroForm", "需要逐页检查裁切、重叠、字体、表格或页码"],
    avoidWhen: ["只需编辑 DOCX 源文书", "只看文本提取就判断版面正确", "未经明确要求把可编辑表单压平", "把旧页面图或成功退出码当成本轮 PDF 验收"],
    inputs: ["PDF 原件或要生成的内容与版式要求", "表单字段名、目标值和是否明确要求压平", "页数、关键文本、交互性与视觉验收条件"],
    outputs: ["读取结果、生成 PDF 或已填写表单", "字段树、页面控件、字段值与外观的一致性检查", "全部页面的 PNG 目检结论"],
    flow: ["读取结构与页数", "按任务选择生成、提取或表单路线", "表单同时核对字段树和页面控件", "写入后重新打开并验证逻辑值", "渲染全部页面检查真实外观", "只交付最终 PDF"],
    boundaries: ["bundle 版本只记录本次观察，不作为未来准入", "视觉通过不能替代表单字段树和逻辑值检查", "默认保留表单交互性；只有用户明确要求才压平", "每次有意义更新后重新渲染并检查全部页面"],
    dependencies: ["Codex bundled workspace dependencies", "Poppler", "reportlab、pdfplumber 与 pypdf", "宿主当前 pdf capability（PDF 能力）"],
    tests: "宿主源码与集成状态可发现；本轮未读取、生成或填写真实 PDF，Current/Fresh/E2E 保持 Unknown。",
    sourcePath: "host:pdf",
    observedSourcePath: "C:\\Users\\10979\\.codex\\plugins\\cache\\openai-primary-runtime\\pdf\\26.826.12353\\skills\\pdf\\SKILL.md",
    sourceBytes: 7269,
    sourceSha256: "9e429bfc5ada20ccf25a531484e3dcc5da59811d936a7cc5dfd23dbf2dfadd31",
    evidenceSourceCommit: null,
    sourceState: "宿主 bundle canonical source（规范源码）已核对",
    installState: "宿主已集成；按稳定能力发现，不以 bundle 版本准入",
    transactionState: "宿主集成能力不经过个人 Skill 安装事务",
    currentTaskState: "本轮未读取、生成或填写真实 PDF",
    freshTaskState: "Fresh task（全新任务）回执 Unknown（未知）",
    endToEndState: "真实 PDF 读写、表单与逐页验收 E2E 本轮 Unknown",
    evidenceObservedAt: "宿主 bundle 26.826.12353：2026-08-31 本轮观察",
    evidenceBasis: "宿主集成 pdf capability（PDF 能力）的源码身份只由结构化来源字段记录；宿主版本不成为准入，本轮没有真实 PDF E2E。",
    supplyEvidenceCommand: "Codex workspace dependency loader（工作区依赖发现入口）"
  }),
  skill({
    slug: "md-to-pdf",
    name: "md-to-pdf",
    title: "Markdown 导出 PDF",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    provenance: "本地维护插件",
    summary: "在 Windows 上把 Markdown 按文档语义转换成 PDF，支持中文路径、样式配置、精确分页和不依赖 Typora 的导出。",
    useWhen: ["Markdown 需要正式 PDF", "需要 CSS 或 presentation profile", "需要精确页数或分页", "中文文件名和路径必须稳定"],
    avoidWhen: ["需要修改原 Markdown 正文", "把渲染成功当语义验收", "绕过现有文档样式约束"],
    inputs: ["Markdown 源文件", "输出 PDF 路径", "可选 CSS、profile 和页数要求"],
    outputs: ["原子发布的 PDF", "source hash、页数、文本和布局验证结果"],
    flow: ["先判断文档语义", "选择批量 preset 或 styled converter", "优先 Playwright，必要时使用 Edge CLI fallback", "验证 hash、时间、大小、页数和 Unicode 文本", "交给 PDF 安全渲染做目检"],
    boundaries: ["不修改 Markdown", "不依赖 Typora 许可", "fallback 不降低验收", "陈旧 PDF 不能冒充本轮结果"],
    dependencies: ["本地 Edge", "Node 浏览器运行时或 Edge CLI", "md-pdf-toolkit"],
    tests: "插件转换相关的 13 项测试和 4 个子测试全部通过。",
    sourcePath: "E:\\.agents\\plugins\\md-pdf-toolkit\\skills\\md-to-pdf\\SKILL.md",
    endToEndState: "核心转换与样式路径已验"
  }),
  skill({
    slug: "pdf-render-safe",
    name: "pdf-render-safe",
    title: "PDF 安全渲染与目检",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    provenance: "本地维护插件",
    summary: "把 PDF 的每一页变成清晰图片和一张总览图，方便我肉眼检查排版；同时核对原文件指纹，避免拿旧图片或错误渲染结果当成这次输出。",
    useWhen: ["需要肉眼检查 PDF 布局", "需要高 DPI 页面或联系表", "怀疑输出陈旧", "中文路径或页码选择需要稳定"],
    avoidWhen: ["只验证纯文本内容", "使用未受支持的 shell wrapper renderer", "删除其他任务产生的图片"],
    inputs: ["PDF 路径", "页码、DPI 和输出 prefix"],
    outputs: ["页面 PNG", "contact sheet", "含 source SHA、页数、renderer 和 stale cleanup 的 JSON report"],
    flow: ["150 DPI 全量初检", "定位可疑页", "只对可疑页提高 DPI", "验证 source fingerprint 和输出集合", "结合文本与页数判断"],
    boundaries: ["只删除同 prefix 的陈旧 PNG", "渲染成功不等于语义完整", "不接受 wrapper 冒充 renderer"],
    dependencies: ["Poppler", "Pillow", "md-pdf-toolkit"],
    tests: "测试通过，覆盖页码选择、prefix、renderer 边界和精确 stale cleanup。",
    sourcePath: "E:\\.agents\\plugins\\md-pdf-toolkit\\skills\\pdf-render-safe\\SKILL.md",
    endToEndState: "主要渲染路径已验"
  }),
  skill({
    slug: "mojibake-doctor",
    name: "mojibake-doctor",
    title: "中文乱码诊断与修复",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "诊断 UTF-8、GBK、GB18030、BOM、替换字符、私用区和双重转码，并以预览、备份和原子替换完成可逆修复。",
    useWhen: ["中文出现乱码", "怀疑编码或 BOM 损坏", "出现替换字符或私用区", "可能发生双重转码"],
    avoidWhen: ["没有读取原始 bytes（字节）", "信息已经丢失却强行猜字符", "跟随 junction（目录联接）修改另一个 source（源码）"],
    inputs: ["精确文件或目录", "可选编码线索"],
    outputs: ["scan 和 diagnosis", "默认只读 repair plan", "apply 后的 verify 结果和原字节 backup"],
    flow: ["读取 raw bytes", "scan 和 diagnose", "先 preview", "显式 apply", "重新读取并 verify"],
    boundaries: ["单文件 hash-pinned transaction", "原字节 backup", "atomic replace", "信息丢失时回到 Git、备份或重新生成"],
    dependencies: ["本地 Python"],
    tests: "12 项 Python 测试和专门 Skill 测试通过。",
    sourcePath: "E:\\.agents\\skills\\mojibake-doctor\\SKILL.md",
    endToEndState: "主要修复路径已验"
  }),
  skill({
    slug: "file-intake-router",
    name: "file-intake-router",
    title: "混合附件分流",
    status: "已安装 / 薄路由",
    maturity: "A-",
    summary: "当我一次给出 Word、PDF、表格、图片、压缩包或整个文件夹，不知道该用哪个读取工具时，它先看清文件结构，再把每一类材料交给真正适合的读取器；单个已知文件不需要它。",
    useWhen: ["附件类型混杂", "无法确认是文本 PDF 还是扫描 PDF", "输入是 archive 或目录", "需要先做最小 inventory"],
    avoidWhen: ["一个已知 Word、PDF、表格或图片", "把所有文件都 OCR", "扫描无关子目录", "路由完成后仍继续接管处理"],
    inputs: ["少量文件 inventory", "用户想得到的最终结果"],
    outputs: ["一个最合适 reader 的明确路由", "必要时最小的后续输入范围"],
    flow: ["识别容器和文件结构", "优先结构化提取", "选择 Word、PDF、表格、OCR、ASR 或其他原生 reader", "交接后退出路由"],
    boundaries: ["单一已知类型直接 reader", "先结构化提取后 OCR", "目录只检查满足请求的子集", "默认不上传私有材料"],
    dependencies: ["当前宿主可用的原生 readers"],
    tests: "source、install、quick validation 与 Personal Skill 语义回归均已通过。",
    sourcePath: "E:\\.agents\\skills\\file-intake-router\\SKILL.md"
  }),
  skill({
    slug: "media-person-self",
    name: "media-person-self",
    title: "具名媒体中的本人判断",
    status: "已安装 / 图像已验 / 语音复用",
    maturity: "B",
    summary: "需要判断一张指定照片里的人是不是我，或一段指定录音、视频音轨里有没有我的声音时，它只比较这几个明确文件，分别给出图像框或语音时间段和不确定性；不会扫描媒体库，也不会识别其他人。",
    useWhen: ["判断用户是否出现在一张明确照片中", "指出哪个 face box 是本人候选", "判断一段具名录音或视频音轨的精确句段是否支持本人说话", "只有一个文件或很短的显式列表"],
    avoidWhen: ["扫描相册、目录或整个媒体库", "识别或命名其他人", "建立人脸或声纹库", "把相似度当法律身份", "把未测试 cluster 的全部语句都归给本人"],
    inputs: ["一个具名媒体或很短的显式列表", "私有可撤销 face template 或 held-out voice profile", "语音需要精确时间戳句段和最小已绑定上下文"],
    outputs: ["图像的 present、not detected、no face 或 unknown", "face index、bounding box 或精确音频时间段", "self、other、unknown 的覆盖范围和一句可反驳依据"],
    flow: ["照片用固定检测器找 face box", "固定识别器与私有模板比较", "录音和视频音轨复用中文 ASR 的时间戳与匿名 cluster", "对最多两句清晰句段做 held-out voice evidence", "分别输出视觉和语音结果，不强行合并", "质量、profile 或覆盖不足时保留 unknown"],
    boundaries: ["不暴露模板向量、声纹或内部相似度", "不命名其他人", "不复制或修改源媒体", "不从文件名、时间接近或目录推断身份", "删除或替换 profile 会改变未来判断"],
    dependencies: ["本地 YuNet 与 SFace", "私有 person:self face template", "ChineseASR 的 Paraformer、时间戳和 held-out voice profile"],
    tests: "照片 adapter 8 项测试通过；语音链复用中文 ASR 的既有句段证据能力，Skill 自身仍缺少一组独立语音回归。",
    sourcePath: "E:\\.agents\\skills\\media-person-self\\SKILL.md",
    endToEndState: "照片路径已验；并发候选不计入"
  }),
  skill({
    slug: "local-secret-broker",
    name: "local-secret-broker",
    title: "本地凭据 Broker",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "需要确认某个账号或密钥是否存在、让程序使用它、或做备份恢复时，它从本机 Password Center（密码中心）走受保护入口处理；默认只返回账号和状态，不把密码或访问令牌暴露到聊天、命令行和普通文件。",
    useWhen: ["查询某个账号或 SecretRef 是否存在", "需要精确获取一个凭据字段", "让浏览器或程序 blind fill", "执行凭据备份、恢复或轮换"],
    avoidWhen: ["把秘密放进聊天、argv、环境变量或普通文件", "未明确请求就揭示明文", "自动处理验证码、Passkey 或 CAPTCHA", "设备处于不可信状态"],
    inputs: ["目标服务、账号或 SecretRef", "一个精确 operation", "需要明文时的明确请求和人类因子"],
    outputs: ["metadata-only lookup", "受保护 capability 或 blind-fill 结果", "必要时单字段明文，不进入普通日志"],
    flow: ["普通查询先 metadata-only", "沿固定 reference 选择精确 operation", "需要最高权限时触发相应因子", "在消费点执行", "正式 read-back"],
    boundaries: ["秘密值不进入公开面板", "人类验证失败只暂停", "管理员权限令牌不扩大授权", "device untrusted（设备不可信）时失败关闭"],
    dependencies: ["PCConfig Password Center（密码中心）", "KDBX 或相应秘密权限来源", "活动保护策略"],
    tests: "精确 lookup fast-path（快速查询路径）测试通过；活动规则权威当前有效。",
    sourcePath: "E:\\.agents\\skills\\local-secret-broker\\SKILL.md",
    endToEndState: "受保护场景按需验收"
  }),
  skill({
    slug: "authorization-file-broker",
    name: "authorization-file-broker",
    title: "最高权限文件加解密",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "当用户明确说要加密或解密某几个文件、某个目录时，它让 Password Center 完成真正的加密、校验和中断恢复；源文件不删除，遇到同名冲突也不会覆盖。",
    useWhen: ["批量加密明确文件或目录", "验证加密 bundle 而不落地明文", "解密到明确目标", "中断后继续已授权任务"],
    avoidWhen: ["扫描磁盘寻找文件", "分析文件语义", "覆盖已存在冲突文件", "删除源文件或 bundle"],
    inputs: ["精确源路径和目标", "Encrypt、Verify 或 Decrypt operation", "最高权限因子"],
    outputs: ["加密 bundle 或恢复目录", "不含内容和 key 的 receipt", "冲突与未处理项"],
    flow: ["解析精确对象", "取得最高权限能力", "执行 Encrypt、Verify 或 Decrypt", "中断时从 authenticated state 恢复", "正式 read-back"],
    boundaries: ["内容和 key 不进入聊天、stdout 或 JSON", "不覆盖冲突", "不删除源", "不扩大到未点名路径"],
    dependencies: ["Password Center", "活动最高权限链"],
    tests: "6 项测试通过，覆盖 round-trip、恢复、幂等解密、篡改和 source change fail-closed。",
    sourcePath: "E:\\.agents\\skills\\authorization-file-broker\\SKILL.md",
    endToEndState: "受保护 round-trip 已验"
  }),
  skill({
    slug: "vault-workflow",
    name: "vault-workflow",
    title: "独立 Vault 与 Key 工作流",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "需要维护独立 Vault、keyfile 或私有 Key 仓库时，它先检查环境、预演变更，再执行加密发布或恢复；密码始终由本机人工输入，这套 Vault 与 Password Center 互不混用。",
    useWhen: ["Vault 加密或验证", "Key 私有仓库发布", "keyfile 恢复", "VAULT03 profile 操作"],
    avoidWhen: ["把它当 Password Center", "把密码交给模型或命令行参数", "向非 PRIVATE 目标发布", "跳过 Doctor 和 WhatIf"],
    inputs: ["profile、mode 和精确加密制品", "本地人工密码 prompt"],
    outputs: ["脱敏 metadata、plan 和 receipt", "远端私有发布或验证状态"],
    flow: ["先 Doctor", "Assess 或 Plan", "WhatIf", "执行精确 mode", "VerifyRemote 和 read-back"],
    boundaries: ["密码只留本地人工 prompt", "不把明文写入模型或磁盘", "与 Secret Broker 和文件加密三域分离", "自检失败立即停止"],
    dependencies: ["vault-tool", "PowerShell wrapper", "PRIVATE GitHub metadata"],
    tests: "Doctor、Assess、Plan、VerifyRemote、WhatIf smoke 和 README helper 测试通过。",
    sourcePath: "E:\\.agents\\skills\\vault-workflow\\SKILL.md",
    endToEndState: "主要私有工作流已验"
  }),
  skill({
    slug: "project-entry-gate",
    name: "project-entry-gate",
    title: "Git 项目身份入口",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "在准备改代码、提交、推送、发布或恢复仓库前，它先确认我究竟在哪个仓库，这个仓库是公开还是私有，当前分支和远端是什么，有没有未提交或未同步的改动，以及现在能不能安全继续。它只提供事实，不替用户授权推送。",
    useWhen: ["不确定当前 checkout（本地检出目录）属于哪个仓库", "准备恢复、迁移、推送或发布", "需要确认仓库是公开还是私有、默认分支是否正确", "多个 Git worktree（工作树）和同步状态会影响实施"],
    avoidWhen: ["已经明确仓库身份、只做普通可逆本地编辑", "把 admission（准入结果）误当成用户已经授权推送", "Git 动态事实不会改变当前决定却仍做全量扫描"],
    inputs: ["要检查的 GitHub 仓库 owner/repo（仓库所有者或命名空间 / 仓库名，例如 wlyaaaaa/wly0829.cn）", "可选的本地工作树或目标分支", "这次只需缓存、实时 GitHub 信息、刷新远端引用，还是完整发布检查"],
    outputs: ["真实本地仓库路径、远端地址、公开性、当前分支、上游分支、工作树、未提交改动和同步状态", "明确的继续、先处理再继续或停止建议；它本身不产生用户授权"],
    flow: ["先判断当前决定需要多新的 Git 事实", "调用 Git Owner 的 admission（准入检查）", "只检查本次指定的工作树或分支", "把事实结果与用户授权分开", "真正发布前再次用完整 publication profile（发布检查）回读"],
    boundaries: ["仅仅出现一个绝对路径不会自动触发", "cached（缓存）事实不能冒充 live（实时）事实", "decision（建议结果）不会自动授予 push（推送）权限", "仓库公开风险不清楚时停止发布"],
    dependencies: ["E:\\GitHub总索引", "Git 和 GitHub metadata"],
    tests: "Skill 和 Provider fixture 通过，覆盖 identity、visibility、target、sync、dirty、no-upstream 和 public exposure。",
    sourcePath: "E:\\.agents\\skills\\project-entry-gate\\SKILL.md",
    endToEndState: "真实仓库 admission 已多次使用"
  }),
  skill({
    slug: "personal-panel-refresh",
    name: "personal-panel-refresh",
    title: "个人项目看板刷新判断",
    status: `已安装 / ${currentERules.releaseId} source 与供应验证通过 / 历史实质刷新链路已验`,
    maturity: "A-",
    summary: "已登记的规则、Skill 或项目完成发布并正式回读后，它会判断这次变化是否让 wly0829.cn 对能力、边界、成熟度或使用判断的说明实质失真。只有确实会失真时，才按活动经济路由选出 Sol 家族或更强未来模型，安排一次独立网站 AI 更新；该 AI 先区分产品与技术的新增、修改、退役/替代和 Unknown，再闭合 Project、Rules、Skills 与 System。来源立即继续，不等待网站完成；格式、时间戳、仅哈希变化或页面已经准确说明的受阻状态不触发。",
    useWhen: ["来源项目已经完成发布和正式回读", "本次变化涉及网站登记的项目、规则或能力", "页面里的事实、解释、边界、成熟度或使用判断可能因此变错"],
    avoidWhen: ["来源还只是草稿、候选或未验证状态", "只有格式、注释、内部重构、时间戳或仅哈希变化", "当前页面已经准确说明受阻状态，没有新的实质失真", "试图让来源工作直接修改或发布网站"],
    inputs: ["网站登记的项目、规则或能力", "来源仓库与已经远端确认的提交", "本次改动范围", "为什么页面可能实质失真的说明"],
    outputs: ["这次变化是否可能影响页面以及原因", "产品与技术新增、修改、退役/替代和 Unknown 的有界语义差分", "Project、Rules、Skills、System 各自 changed、unchanged 或 blocked 的闭包", "无需更新、已经安排一次独立更新或安排失败的明确结果", "网站检查通过后的定向提交、现有 PUBLIC main 正常推送、Pages 部署与公网回读"],
    flow: ["等来源项目负责人先完成自己的发布和正式回读", "每次重新读取网站登记清单", "对照当前页面判断变化是否真的会造成实质失真", "不影响页面时明确说明无需更新", "同一次变化已经安排时不重复安排", "确实会失真时按活动经济路由选择 Sol 家族或更强未来模型并只安排一次独立网站更新", "网站 AI 先形成产品与技术语义差分，再闭合 Project、Rules、Skills 与 System", "来源工作立即继续或结束，不等待也不轮询网站进度", "网站负责人进入自己的仓库，独立完成内容、构建和公开检查", "全部通过后定向提交，正常推送到现有 PUBLIC main，等待 Pages 并从公网回读"],
    boundaries: ["不复制网站登记清单", "不建 watcher（监视器）、daemon（后台进程）、定时任务或轮询", "不在来源工作里编辑、构建、测试或发布网站", "不把草稿、候选或未验证状态当成已发布事实", "同一次变化不重复安排", "语义判断和正文写入不降级到 Luna、Terra 或本地模型，也不把今天的精确模型写成永久上限", "来源只接收是否安排成功的结果，不读取进度、不等待完成、不轮询", "安排失败时说明实际原因并停止，不改派也不盲目重试", "现有长期授权不跳过 system/developer/platform、网站负责人、目标解析、拒绝、补证、网站检查或本人预览，也不覆盖新公网目标、付费、秘密暴露、force-push（强制推送）或用户明确暂缓"],
    dependencies: ["V:\\Personal\\Projects\\wly0829.cn\\config\\panel-projects.json", "V:\\Personal\\Projects\\wly0829.cn\\scripts\\assess-panel-impact.mjs", "native-economy-routing 的当前模型家族与思考强度选择", "桌面 AI 工作台用于安排独立网站更新的现行入口", "已验收的 wly0829.cn PUBLIC main、GitHub Pages 与公网回读路径"],
    tests: "E98 完整本地规则回归 38 pass、0 fail、4 个 cross-owner skip；Skill supply 的 source/install/39 个事务全部闭合，规则测试覆盖发布回读硬路由、隐式描述、实质阈值、一次安排、模型质量下限与四页面域闭包。历史真实链路已完成网站测试、PUBLIC main、Pages 与公网回读。",
    sourceState: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 与活动 ${currentERules.releaseId} 已分别回读；personal-panel-refresh 的发布后触发描述、模型路由和四页面域目标已在 E98 commit e1c1e36 激活`,
    currentTaskState: `E98 已激活并完成 source/install/规则回归；本轮网站任务正在更新 E98 对应快照，但尚未用一个全新自然来源发布任务重验隐式选择，不能把源码和安装 PASS 冒充 fresh-task PASS`,
    freshTaskState: "历史上，来源项目完成发布回读后已安排一次独立网站更新；来源工作没有等待网站完成",
    evidenceObservedAt: `E98 来源发布、活动规则与供应回读，另保留历史独立网站更新现场；当前供应链现场：${generatedPanelFacts.observedAt}`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 E98 e1c1e36 中的 panel_post_publish_closeout、personal-panel-refresh 唯一源码、38/0 本地规则回归与 39/39 供应事务，以及既有一次独立网站更新和网站负责人的内容、构建、PUBLIC 与 Pages 检查；当前供应、fresh task 和历史场景分层，不公开任务编号或内部维护账本。`,
    sourcePath: "E:\\.agents\\skills\\personal-panel-refresh\\SKILL.md",
    endToEndState: "历史链路证明实质变化判断、重复安排拦截、来源立即继续和网站独立发布；E98 隐式发现与 Sol-or-stronger 选择仍待全新任务重验"
  }),
  skill({
    slug: "control-plane-doctor",
    name: "control-plane-doctor",
    title: "三控制面只读体检",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "当用户说“检查三个控制面现在是否健康、有没有漂移、迁移或恢复问题”时，它只读取被点名的 .agents、Git 或 PCConfig 状态，汇总哪里正常、哪里警告、哪里阻塞；它自己不实施修复。",
    useWhen: ["明确要求控制面健康检查", "需要漂移或迁移验收", "跨仓库恢复", "需要聚合 health 和 convergence"],
    avoidWhen: ["普通项目实现", "直接实施修复", "没有选择 Owner 却扫描全部控制面", "把 cached warning 当 block"],
    inputs: ["Owner、check 和 freshness"],
    outputs: ["各 Owner 的 health、convergence、warning 和 block", "精确 remediation owner"],
    flow: ["按选择的 Owner 调用精确 provider", "默认 cached 和 zero-write", "聚合而不篡改原状态", "需要修复时退出 Doctor 并交给真实 Owner"],
    boundaries: ["不修复、不安装、不改任务", "不 commit 或 push", "未选择的 Owner 连 provider 路径都不读取", "warning 与 block 分开"],
    dependencies: ["Personal Skill validator", "Git admission", "PCConfig drift provider"],
    tests: "Owner scope 与 Skill metadata 测试通过；description 已恢复为显式 Use when 入口。",
    sourcePath: "E:\\.agents\\skills\\control-plane-doctor\\SKILL.md"
  }),
  skill({
    slug: "tailscale-safe-exposure",
    name: "tailscale-safe-exposure",
    title: "Tailnet 精确暴露",
    status: "已安装 / 环境条件型",
    maturity: "B",
    summary: "需要让一台指定设备通过 Tailscale 访问本机服务，或检查 Sunshine/Moonlight 为什么走直连、DERP 或中继时，它先看当前监听和防火墙，只开放必要端口给必要 peer，并记录怎样回滚。普通局域网和 Wi-Fi 问题不走它。",
    useWhen: ["只允许 tailnet 内访问本地服务", "需要 peer-scoped firewall", "检查 reverse port 或 loopback 暴露", "验收 Sunshine/Moonlight direct、DERP 或 Peer Relay"],
    avoidWhen: ["普通 LAN、Wi-Fi 或 VPN 问题", "默认打开 Funnel", "把 RemoteAddress 设为 Any", "一次修改多个机制和端口"],
    inputs: ["精确 service、protocol、port 和 peer", "当前 Tailscale 身份、监听和 firewall 基线"],
    outputs: ["preimage、最小配置差异、rollback", "本机、tailnet 和 peer 分层验收"],
    flow: ["读取身份和监听基线", "选择单一最小机制", "记录 preimage 和停止条件", "执行一项变更", "read-back 与具名 peer 验收", "失败按预记 rollback"],
    boundaries: ["默认禁 Funnel", "禁止宽泛 remote/interface", "read-back 失败即回滚", "没有具名 peer 不能声称 E2E"],
    dependencies: ["Tailscale CLI", "精确服务和 peer 环境"],
    tests: "本机 CLI 当前存在；未做本轮具名 peer 连接验收，也没有独立 Skill 全套测试。",
    sourcePath: "E:\\.agents\\skills\\tailscale-safe-exposure\\SKILL.md",
    endToEndState: "具名 peer E2E 未验"
  }),
  skill({
    slug: "llm-backend-toolkit",
    name: "llm-backend-toolkit",
    title: "额外模型 Backend 工具箱",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "当原生子代理不适合、但有一个范围很小且结果可以独立验收的任务时，它可以把这个任务交给本机登记的其他模型后端，保存 job 和结果，再由顶层模型复核。普通并行仍优先原生子代理。",
    useWhen: ["任务封闭且有独立 verifier", "原生代理之外的 Backend 有明确净收益", "允许保存 job、result 和 receipt"],
    avoidWhen: ["普通子代理委派", "没有独立验收标准", "把显式 crosscheck 当 fallback", "云文本没有 cloud allowed"],
    inputs: ["有明确目标和 verifier 的 request JSON", "隐私是否允许云端"],
    outputs: ["job id、result 和 receipt", "由顶层模型独立验收后的结论"],
    flow: ["读取 live backends", "选择符合边界的一条 route", "submit", "按建议时间读取一次 job result", "保留 receipt，由顶层模型验收"],
    boundaries: ["不是原生 child（子代理）", "不自动 fallback（切换后备路线）", "失败不能冒充 complete（完成）", "registry（登记表）状态会漂移，必须现场读取"],
    dependencies: ["E:\\.agents\\config\\llm-backend-registry.json", "对应 Provider runtime"],
    tests: "专项测试、live backend listing、quick validation 和 metadata 语义断言全部通过。",
    sourcePath: "E:\\.agents\\skills\\llm-backend-toolkit\\SKILL.md"
  }),
  skill({
    slug: "native-economy-routing",
    name: "native-economy-routing",
    title: "原生代理经济路由",
    status: "已安装 / 宿主条件型",
    maturity: "B",
    summary: "当任务能拆成互不冲突、可以分别验收的支路时，它先确认当前工作台真实提供的模型、思考强度和父子角色，再判断开零到十个子代理是否真的能提高质量。每个子代理只拿必要范围，创建前再复核一次现场；身份不可靠时只关闭并行委派，主任务继续。",
    useWhen: ["任务出现独立可验支路", "上下文压缩或重大 steer 后需要重判", "child 完成或槽位释放", "当前任务确实需要原生并行"],
    avoidWhen: ["没有可信宿主身份", "普通工具步骤", "把代理名称当身份证明", "固定默认某个模型家族"],
    inputs: ["UserPromptSubmit（用户请求进入时）或 SubagentStart（子代理启动时）注入的 verified model（已验证模型）、effective effort（实际思考强度）、root/child（根/子代理）、turn hash（本轮指纹）、E release 与 contract SHA", "旧 root 完全没有 Hook（宿主钩子）或注入时，同一任务中用户已经给出的自然语言 model/effort 确认；确认层规范化别名，thread binding（任务绑定）只保存 canonical ID（规范标识）", "当前任务的独立支路、slots（并行槽位）、资源和写入冲突", "PreToolUse（工具创建前复核）在真实 spawn（创建子代理）前取得的身份、家族、effort 与参数"],
    outputs: ["0 到 10 的直属代理判断", "模型家族、effort、scope 和 fork 边界"],
    flow: ["root 的 UserPromptSubmit 或 child 的 SubagentStart 在 0–10 判断前注入可信身份与当前 E identity", "只有旧 root 完全没有 Hook 或注入时，才把同一任务中已有的自然语言 model/effort 确认规范化后写入并回读耐久 thread binding；child 不继承", "上下文压缩、E identity 变化或加载不确定时重读当前 11 条路由规则、重派生并刷新代际快照；E 换代本身不要求用户重复确认", "代理自己按任务语义、净收益、冲突和 slots 评估 0–10、模型家族与 effort", "真实 spawn 前由 PreToolUse Hook 复核 TOCTOU、家族上限、effort 上限和参数", "root 继续负责方向、集成和最终验收，不因派出 child 原地空等"],
    boundaries: ["Hook 只验证身份、E identity 与参数，不选择模型家族或代理数量、不创建 child，也不制造授权", "耐久 thread binding 只用于完全没有 Hook 或注入的旧 root，只落 canonical ID，child 不继承", "E release 换代不撤销已经成立的用户确认；规则明确撤销该路径或身份冲突时才失败关闭", "PreToolUse 只是 spawn 前复核，不能代替判断前的可信身份", "Hook 或有效绑定缺失只关闭委派，普通调查、实现和最终答复继续", "不依赖 Stop Hook；app version（应用版本）和 versioned path（带版本路径）不是准入条件", "委派只能收窄 scope、授权、家族和 effort，root 始终保留最终责任"],
    dependencies: ["宿主 UserPromptSubmit 与 SubagentStart Hook", "旧 root 的耐久 thread binding 入口", "真实 spawn 前的 PreToolUse Hook", "当前 E release 与 capability contract", "宿主原生 child identity（子代理身份）与 slots"],
    tests: "聚焦 Gate 与 Hook 回归覆盖判断前身份注入、旧 root 对话绑定、PreToolUse 创建前复核、无 Stop Hook 依赖和更新连续性；真实可用性仍由每个任务的宿主身份、E identity、授权与 slots 决定。",
    sourcePath: "E:\\.agents\\skills\\native-economy-routing\\SKILL.md",
    currentTaskState: "按本次 UserPromptSubmit 或 SubagentStart 注入的宿主身份与 E identity 现场判断；不沿用其他任务的 child 数量或回执",
    freshTaskState: "每个新任务必须重新取得自己的宿主身份；只有完全无 Hook 的旧 root 可建立耐久绑定，child 不继承",
    endToEndState: "判断前注入与创建前复核是两层独立证据；创建成功只证明该次宿主路径，每个任务仍需独立验证模型、effort、E identity 与结果"
  }),
  skill({
    slug: "token-budget-advisor",
    name: "token-budget-advisor",
    title: "工作台配额与 GPT-5.6 Sol 文本计量",
    status: "已安装 / 上次 Fresh task E2E 已验",
    maturity: "A",
    summary: "仅在用户明确询问当前工作台配额或 reset（重置）状态，或要求按 GPT-5.6 Sol 的权威口径计算、比较可见文本的模型计量单位（Token）时触发。配额走只读账号用量入口；Token 优先使用完成响应 usage 或官方 input_tokens，不能取得时返回 Unknown。",
    useWhen: ["用户明确询问当前工作台 quota（配额）或 reset（重置）状态", "用户明确要求按 GPT-5.6 Sol 统计可见文本 Token（模型计数单位）", "比较两个 Prompt（提示词）或文件的 Token 数", "接近明确 Token 边界，需要官方计数"],
    avoidWhen: ["仅仅因为任务长或可能压缩就自动触发", "推断隐藏 prompt、tools 或 reasoning", "把估算当成正式账单", "为了报告数字而回显用户正文"],
    inputs: ["明确的 quota/reset 问题，或一段可见文本/明确文件", "GPT-5.6 Sol 计数口径", "可选的明确 Token 数值预算"],
    outputs: ["只读配额/reset 状态，或 GPT-5.6 Sol 权威 Token 数", "使用的 usage/input_tokens 来源和没有计入的内容", "安全低于、接近、超过预算或 Unknown 的判断"],
    flow: ["配额问题读取只读 account/rateLimits 状态", "Token 问题优先使用响应 usage 或官方 input_tokens", "官方计数不可用时返回 Unknown", "只报告数字、方法、排除项和边界判断"],
    boundaries: ["不猜隐藏上下文", "不回显正文或账号标识", "不计算 API 价格或美元成本", "不把字符、字节或其他模型计数冒充 GPT-5.6 Sol"],
    dependencies: ["工作台只读 usage 状态入口或官方 input_tokens 计数"],
    tests: "Source、quick validation、autonomy、semantic、junction installer 和 supply contract 全部通过；Fresh 0.150.1 root 已发现并实际调用 Skill，o200k_base exact=3，预算 10 时返回 safely_below。",
    sourcePath: "E:\\.agents\\skills\\token-budget-advisor\\SKILL.md",
    freshTaskState: "Fresh root（全新根任务）已发现并实际使用",
    endToEndState: "Token 计数路径已有历史验收；当前配额/reset 只在用户明确请求时现场读取"
  })
];

export const excludedSkills = [];
