import { generatedPanelFacts } from "./panel-facts.generated.js";

const currentERules = generatedPanelFacts.authority;

function skill(definition) {
  return {
    provenance: "个人维护的能力入口",
    sourceKind: "personal_install",
    availability: "available",
    statusTone: "mixed",
    sourceState: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)} 中的唯一源码已核对`,
    installState: "canonical junction 已安装",
    transactionState: `${generatedPanelFacts.skills.transactionCampaignCount} 个供应事务全部终态；0 个坏事务`,
    currentTaskState: "本轮宿主回执未知",
    freshTaskState: "新任务回执未知",
    endToEndState: "按场景验收",
    evidenceObservedAt: `供应链现场：${generatedPanelFacts.observedAt}；项目场景按各项记录`,
    evidenceBasis: `.agents ${currentERules.releaseId} release ${currentERules.gitCommit.slice(0, 7)}、当前 Personal Skill supply（个人能力供应链），以及本页明确标注的既有项目/Provider（固定服务入口）证据；source/install/transaction 通过不冒充 current/fresh/E2E`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    supplyEvidenceCommand: "E:\\.agents\\tools\\Test-PersonalSkillSupply.ps1 -RequireInstalled -NoExternalEvidence -Json",
    ...definition
  };
}

export const skills = [
  skill({
    slug: "personal-media",
    sourceBytes: 6770,
    sourceSha256: "24d27c6372359cac3e2a9696404cfc2534b184f1c76beaac10044e3db081cb3e",
    name: "personal-media",
    title: "个人媒体检索与录音片段定位",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "用画面、地点、文字或录音内容查找本机受管照片、视频和录音，核对原件后打开或建立临时浏览文件夹；已经选中的录音还可复用现有转写，指出某段话从几分几秒开始。",
    useWhen: ["已经选中录音，想知道某段内容在什么时间位置", "记得画面、地点、文字、录音内容或大致日期，但不知道原件路径", "需要打开少量真实媒体原件", "需要把一组查询结果放进临时文件夹浏览", "需要明确区分图片、视频和音频"],
    avoidWhen: ["查找 Word、PDF 等非媒体原件", "按人物大范围扫描媒体库", "删除、修改或上传媒体", "重建第二套索引、服务或后台任务"],
    inputs: ["1 到 4 个能出现在内容中的区分词", "可选地点、描述、分类、媒体类型和日期", "明确要求完整集合时才使用 all"],
    outputs: ["录音中的实际起止时间、命中词、少量 ASR 摘录、时间精度与覆盖范围", "少量可读候选和绝对原件路径", "媒体类型、已知日期、地点、分类和匹配依据", "按请求创建的同卷 hardlink 浏览目录", "零命中时的真实过滤条件和覆盖缺口"],
    flow: ["把用户原话压缩成最小可靠过滤条件", "用 SQLite 条件和 FTS 执行小结果 search", "核对权威原件定位记录确实指向现存原件", "需要浏览时创建 task-unique hardlink 文件夹", "身份问题只把选中的少量原件交给 person:self 能力", "用户不再需要时只清理那个受管浏览目录", "录音片段定位使用 locate-audio，核验当前原件后复用 ChineseASR 已有 hash 绑定时间结果，不启动模型或播放音频", "已有 pending job 就接着同一任务等待；没有可用时间戳且已授权处理时，只对这段录音补本地 Paraformer 句级时间，再重试原定位"],
    boundaries: ["私密项默认隐藏，只有用户明确要求才包含", "地点只表示已复核的拍摄现场，文字里的地名走 query", "不使用当前没有证据的人物过滤", "不读取完整 NDJSON、全盘扫描或复制媒体进知识库", "浏览清理绝不删除原件", "达到 limit 只说明前 N 条，只有显式 --all 才能声称完整匹配集合", "现场地点未登记不能静默降成文字 query；只保留本人给出的其他可靠条件", "录音时间相对原始音轨，匿名说话人不是身份，ASR 摘录不是逐字音频证明；locate-audio 不提供视频片段定位", "明确只读请求只报告时间缺口；不会为导航上传录音、处理目录或猜时间戳"],
    dependencies: ["V:\\Personal\\Projects\\personal-media", "E:\\Media\\_manifests\\personal-media-current\\catalog.sqlite3", "E:\\Pictures、E:\\Videos 与 E:\\Music\\录音 canonical roots"],
    tests: "个人媒体 2026-09-05 验收回执记录 55 项回归，53 项通过、2 项真机项跳过；本轮核对七份源文件承诺，并保留 1,182 项精选已在手机包与云候选的证据。9 月 7 日仅对齐 README 备份范围，未重跑原验收；手机实际清理仍待连接。Skill 的来源与安装证据另行核对。",
    sourcePath: "E:\\.agents\\skills\\personal-media\\SKILL.md",
    endToEndState: "本地 search、browse 和 clean 契约已验"
  }),
  skill({
    slug: "personal-materials",
    sourceBytes: 5277,
    sourceSha256: "15aac8514fe915efb3d114b87078824b3a47e8c6491e8238bbc71b53856d3e32",
    name: "personal-materials",
    title: "非媒体原件与文内位置查找",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "忘了合同、报告放在哪里，或想知道某句话在第几页、哪一段时，它先找到并核对选中的真实原件，再给路径或带位置的小段摘录。AI 阅读默认不弹桌面应用；本人要求打开时才打开。",
    useWhen: ["非媒体原件位置未知、原有定位失效，或需要在登记来源内有界查找", "已经选定一份文件，需要定位特定内容的 PDF 页、Word 段落/表格或文本行", "需要给 AI 一条现场核验过的原件路径，而无需启动桌面阅读器"],
    avoidWhen: ["照片、视频、录音或其他视听媒体", "已有可靠精确路径且只需普通直接阅读；已选原件的段落、页码或行定位仍可用 locate-content", "需要判断材料专业含义或执行领域动作，而不是找原件或文内位置", "要求全盘扫描、后台索引或批量复制原件"],
    inputs: ["对材料名称、时间、版本角色、用途或原生目录的普通描述", "可选的已登记来源提示；不要求用户重复系统已经知道的本机路径或内部 ID"],
    outputs: ["find/discover 的少量候选和真实覆盖范围", "inspect/inspect-discovered 返回现场核验路径、大小与 SHA-256，不写索引或启动应用", "locate-content 返回绑定当前原件版本的页码、段落/表格位置或行号，以及有界摘录、格式与覆盖限制", "本人明确要求打开时，才记录核验/登记状态并启动默认应用"],
    flow: ["可靠原件定位已知时直接用原生 reader（文件读取器），跳过再次查找", "位置未知时先 find；登记不足才在获准来源执行 discover", "选中后用 inspect 或 inspect-discovered 只读核验路径；AI 从该精确原件继续读取", "问某段内容在哪里时直接对已选原件运行 locate-content，不额外重复 inspect", "PDF 文本层返回页码，DOCX 返回正文段落或表格单元格，TXT/Markdown 返回行号", "没有可提取文字时，仅针对这个原件复用 PDF/LocalOCR；不能执行就明确定位缺口", "只有本人要求在桌面打开才运行 open/open-discovered；需要登记但不弹窗时显式 --no-launch"],
    boundaries: ["照片、视频、录音及其他视听媒体始终交给 personal-media", "候选 token、material key 和内部来源 ID 不进入面向用户的回答", "项目只保存最小 locator/metadata SQLite（定位与元数据数据库）及与原件绑定、可删除重建的文字，不保存原件字节、人物事件或跨领域画像", "discover 最多选择 8 个来源，全部来源共享 2500 个文件和总计 8 秒的预算，每来源最多 12 层，并且不跟随链接", "不复制、移动、改写或删除原件；hash 漂移、来源根变化或文件状态变化都失败关闭", "inspect 与 inspect-discovered 是零写核验；open --no-launch 仍写状态，不能当只读替代", "locate-content 自行核验被选原件，不登记发现候选、不启动应用，也不建全库正文索引", "Word 段落编号不是打印页码；PDF 文本层不覆盖图片内文字，局部零命中不能证明全文件没有内容", "提取/OCR 结果须绑定当前原件 hash 和实际页/区域，已有绑定结果可复用"],
    dependencies: ["个人材料查找项目（私有源码）", "personal-materials.handoff.v1 与项目最小 locator/metadata SQLite（定位与元数据数据库）"],
    tests: "2026-09-07 来源 main 1425c7f；tests/test_materials.py 的 66 项回归通过，用时 57.35 秒，覆盖只读核验和选定文件定位。本网站任务没有访问私人原件，实际文件/默认应用结果仍独立。",
    sourcePath: "E:\\.agents\\skills\\personal-materials\\SKILL.md",
    endToEndState: "默认只读核验与文内定位由当前源码合同证明；本网页任务没有打开或提取私人原件，真实具体文件结果不在此宣称通过"
  }),
  skill({
    slug: "wechat-direct",
    currentTaskState: "本轮只核对已发布代码、Skill与合成回归，未读取真实消息或媒体",
    freshTaskState: "当前新自然请求的context/导出/媒体真实结果未由本网站任务重验",
    evidenceObservedAt: "2026-09-07：.agents 7a7fbda 与 WeChatDirect 96b0fb6；既有归档规模为2026-09-01历史观察",
    sourceBytes: 5036,
    sourceSha256: "3c056cb5894989418930cb9adcdde8f4cc7f2d37bade5ed203d5d2d1844a2fa7",
    name: "wechat-direct",
    title: "微信上下文与具名归档",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "读取一个明确微信对话的上下文、回复和媒体，或导出所选消息与可验证的图片、表情、语音、视频、文件。具名联系人/群可持续维护本地归档；窗口没有本人消息、图片尚缺或只见缓存，都不会被说成完整历史结论。",
    useWhen: ["回答某个联系人或群的当前/历史上下文，或找一条消息附近的对话", "把已选消息导出为可继续理解的 conversation.json、media/ 与 ai-context.md，必要时附 HTML", "打开有原生定位和校验证据的图片、表情、语音、视频或文件", "维护一个本人明确指定联系人/群的可重放增量归档", "查看某个账号当前本地朋友圈缓存"],
    avoidWhen: ["一次同步整个账号", "后台持续同步", "没有明确联系人或范围", "把聊天材料复制到第二数据库"],
    inputs: ["联系人或群名", "账号、时间范围或消息线索", "归档时的单一具名目标"],
    outputs: ["按原生顺序与真实发送者角色排列的小窗口、回复和可用历史提示", "默认 conversation.json、media/、ai-context.md 导出，以及按需 HTML", "图片DAT V1/V2解码、原PNG/GIF/WXGF表情、WAV语音及本机精确定位的视频/文件，附真实缺口", "具名对象增量归档、完整历史发送者统计或当前朋友圈缓存"],
    flow: ["直接选择现有CLI的context、export-context、media-open、sync-contact、moments或preserve，参数不清先读该命令help", "context从最小窗口开始，使用固定query游标或around定位附近；读取senderRoleCounts、selfObservation与availableHistoryHint，不把窗口self=0推成从未说话", "显式导出或打开媒体时按原生MD5/索引定位、解码并核对，不从相邻目录猜文件", "原生表情在显式export-context/media-open中可沿同条CDN记录补取并核MD5/size/decoder；--local-only严格禁网络", "具名sync-contact第一次取本机当前可见完整历史，后续沿同目录增量，旧历史/游标或后到媒体才full-reconcile", "旧归档下次同对象同步先验真，再按sender_identity_reconcile重核发送者；已无源旧消息保留正文与原归属证据并标未重核", "朋友圈未点名账号时分别读primary和secondary并分开说明，不用auto或根据昵称猜账号", "需要保全证据时才preserve；它与普通context、具名归档各自有界"],
    boundaries: ["一次只处理一个明确联系人或群，不做全账号同步、第二数据库或后台任务", "context只用本机；sync-contact/preserve不自动请求远端表情；--local-only拒绝所有网络补取", "发送者按同分片Name2Id和账号原生承诺解析，openim与非文本消息保留真实角色，长ID作为字符串", "旧原生消息已不存在时，不伪造身份重新核验成功；原正文和归属证据仍保留", "noChange和普通增量都核对媒体与WAV哈希，状态无变化不省略完整性核验", "复杂WXGF分区或透明度缺证继续明确gap，不把仅能读部分画面称完整还原", "小窗口self=0不是整个聊天本人从未发言；完整历史结论使用同对象归档manifest的统计", "硬崩溃半成品不冒充自动续跑，缓存未命中不等于没有内容；语音转写交给中文ASR"],
    dependencies: ["E:\\Projects\\Tools\\WeChatDirect", "中文 ASR 用于语音媒体"],
    tests: "2026-09-07 PUBLIC main 96b0fb6；137 项测试与 32 个子测试通过，用时 3.49 秒。网站任务没有读取真聊天、打开真实媒体或新建归档；旧3个归档/6032条仅是2026-09-01历史观察。",
    sourcePath: "E:\\.agents\\skills\\wechat-direct\\SKILL.md",
    endToEndState: "137项与32子测试通过；真聊天、媒体解码、显式CDN取回及当前具名归档仍以各自真实回读为准"
  }),
  skill({
    slug: "google-workspace-direct",
    sourceBytes: 3474,
    sourceSha256: "0412c2b0f53a0a711aaceee71346830350aa3a26170729292aaf4b390ffd2426",
    name: "google-workspace-direct",
    title: "Google Workspace 固定入口",
    status: "已安装 / 固定 Google Workspace 服务入口已配置",
    maturity: "A-",
    summary: "需要查自己的 Gmail、Google Drive 或日历时，它固定使用已经登记的同一个账号读取；只有系统确实提供对应写入能力、而且用户明确要求时，才会修改外部内容。",
    useWhen: ["按条件查邮件", "查找或导出 Drive 文件", "读取日历事件", "需要原生 Google Docs 导出", "需要读取 Drive 内普通 TXT、DOCX 或 PDF 文件正文"],
    avoidWhen: ["切换其他账号", "静默改走浏览器、公共 Connector 或 rclone", "Provider 没有暴露目标写操作", "Google Photos、Admin 或支付"],
    inputs: ["窄查询、对象 ID 或时间范围", "写操作时的精确对象、内容和动作授权"],
    outputs: ["最小必要邮件、文件或日历结果", "原生文档导出", "写操作的 Provider 回执与 read-back", "普通存储文件经固定 Provider 的 DriveDownload 下载后的原生读取结果"],
    flow: ["直接选择需要的窄读取，不先预检 Provider 或枚举全部工具；Gmail 搜索默认不读正文", "选择固定 Provider 的精确 operation", "默认执行只读", "原生文档必须走 Drive export", "写入前核对 Provider 能力和授权", "按同一 Provider read-back"],
    boundaries: ["不落中央库", "不自动同步", "不换账号或第二 Provider", "删除、发送、邀请和公开分享需要精确授权", "MCP 只暴露元数据或没有 drive_download，不等于固定 Provider 没能力；普通文件可走已登记 CLI DriveDownload", "普通文件用 files.get?alt=media，原生 Google Docs 必须 files.export；不能混用或切换第二 Provider"],
    dependencies: ["PCConfig 的 google-workspace.primary Provider", "已登记 OAuth 绑定"],
    tests: "Provider binding、action 和 install 三组测试通过；本次未重新验证在线账号身份。",
    sourcePath: "E:\\.agents\\skills\\google-workspace-direct\\SKILL.md",
    endToEndState: "在线身份本轮未复核"
  }),
  skill({
    slug: "chinese-asr",
    sourceBytes: 16392,
    sourceSha256: "538acb66abd3d418bbcb21737a834a5204afd686fbdd9cfbaff8b088b6851b2c",
    name: "chinese-asr",
    title: "中文录音转写与说话人证据",
    status: "已安装 / 正式环境回归通过",
    maturity: "A",
    summary: "把中文和微信录音转成可搜索文字，按需要附时间位置、匿名说话人或本人声音线索。定位已选录音片段先复用已有结果；明确允许上传时，同一个阿里云入口可做重要录音交叉验证，也可复核普通转写质量，二者不会混同证据等级。",
    useWhen: ["需要中文录音全文，或明确选择带时间位置的模式", "需要区分匿名说话人 cluster", "需要判断精确句段是否支持 person:self", "重要专业录音需要双链验收", "普通本地转写存在影响理解的疑点，且选定录音/任务已明确授权云质量复核"],
    avoidWhen: ["扫描整个音频库", "把 cluster 数直接当真实人数", "把 ASR 当逐字法律证书", "timeout 后盲目重新提交同一 job"],
    inputs: ["一个具名音频或视频音轨", "模式、时间范围和必要的说话人证据边界", "云路线需要明确双开关授权"],
    outputs: ["转写文本；所选模式支持时附时间戳，需要时附匿名 cluster", "objective sidecar 与 job 状态", "本人归属的精确句段、覆盖范围和不确定性", "已存时间结果的实际时间、timestamp_granularity、质量、覆盖与原件/artifact绑定", "同一云入口明确的 important_evidence 或 quality_review purpose、分块范围和保存结果"],
    flow: ["查找某段录音时间时先用 transcript-readback 或媒体库 locate-audio，核对已存结果与当前原件 hash", "已返回定位缺口且允许补时，只对选中录音走本地 quick + paraformer，复用同一 job；导航不要求云上传或重跑目录", "普通录音走 strict", "长录音走 long-strict", "说话人先聚类再对精确句段做 held-out attribution", "重要录音按授权进入唯一云路线", "以原音频为权威复核结果"],
    boundaries: ["原音频始终高于转写", "云失败不能伪装成本地成功", "其他说话人保持匿名", "空文本和超时不能自动解释为没有内容", "云请求必须在 -Important 与 -QualityReview 中选择一个，并有 -CloudUploadAuthorized；质量复核不是重要证据，也不额外要求两条本地引擎先失败", "已明确的精确云授权跨续作与后代持续有效；不按任意录音数量或反复本地失败自加门", "复用 qwen-audio-3.0-asr-flash 及现有 SecretRef；不创建公网文件 URL、不切 Provider、不让云模型成为普通默认", "云块时间只能帮助定位大段，不等于句级时间、说话人归属或逐字正确；API 成功也不证明人名与文字正确"],
    dependencies: ["E:\\Projects\\Tools\\ChineseASR", "模型 registry", "LocalGpuBroker", "本地私有 person:self profile"],
    tests: "2026-08-31 的 345 项完整回归与 15 项定向验证保留为历史；当前 .agents 7a7fbda 说明已增加 transcript-readback 与 quality_review 两个实际入口。网站任务未启动模型、读取私人录音或发起云请求；当前实现验收由 ChineseASR 项目独立说明。",
    sourcePath: "E:\\.agents\\skills\\chinese-asr\\SKILL.md",
    endToEndState: "主要模型链有历史真实证据；当前时间戳复用与质量复核不因 Skill 存在就冒充本轮录音 E2E"
  }),
  skill({
    slug: "timeaudit-diagnostics",
    name: "timeaudit-diagnostics",
    title: "TimeAudit 有界历史诊断",
    status: "已安装 / 12 项 provider 合同测试与一小时真实查询通过",
    statusTone: "pass",
    maturity: "A",
    summary: "当电脑的卡顿、发热、磁盘/网络、掉帧、睡眠或采集断档需要历史证据时，用一次有界聚合查询回答“这段时间实际覆盖了什么、出现了哪些相关信号、还缺什么”；它不是 TimeAudit 控制器，也不会把相关性冒充根因。",
    useWhen: ["间歇性电脑问题已经过去，需要回看 1 到 168 小时内的历史", "需要先区分没有异常、没有游戏帧和根本没采到数据", "硬件、FPS、睡眠或采集覆盖会改变当前诊断结论", "需要把历史聚合与 Windows、驱动、任务或 PCConfig 现场证据对齐"],
    avoidWhen: ["只需要此刻的实时状态", "想控制、启动、停止或修复 TimeAudit", "需要逐进程或逐窗口明细而当前 aggregate-only 接口不能回答", "试图用一次阈值信号证明硬件损坏、恶意程序或用户意图", "把超过 168 小时拆成大量窗口暴力查询"],
    inputs: ["具体电脑问题与尽可能窄的时间范围", "最近事件可用 1–168 小时，具名事件使用精确 UTC 起止", "需要关联的 Windows、驱动、任务或 PCConfig 现场证据"],
    outputs: ["请求窗口、覆盖新鲜度、样本数、边界/内部最大空档", "CPU/GPU、内存、磁盘、网络与有效游戏帧的聚合摘要", "active/idle/display-off/lock/sleep 的区间并集时长和未覆盖时间", "阈值 occurrence（出现次数）、因果限制、真实缺口与下一项安全诊断动作"],
    flow: ["选择能改变判断的最短时间窗", "调用固定 `timeaudit_diagnostic_summary.py` 一次", "验证 schema、owner、status、窗口、coverage、样本和输出省略标志", "只有 game_performance.status=observed 时解释 FPS/1% Low/frametime", "把信号与实时状态和其他 Owner 证据关联", "先给实用结论，再说明窗口、关键聚合、缺口和下一步"],
    boundaries: ["TimeAudit 只是可选历史证据，不单独证明根因", "单次窗口最多 168 小时，不网格化暴力查询", "provider 为速度与语义稳定只返回聚合；进程、路径、标题等字段类别并非天然敏感，可由其他合适路线在有价值时使用", "不调用 Grafana、db_audit、PCConfig cursor 或采集控制入口", "provider unavailable/stale/empty 时回到普通诊断，不把缺数据写成健康"],
    dependencies: ["E:\\Projects\\Tools\\TimeAudit\\timeaudit_diagnostic_summary.py", "TimeAudit 本机 PostgreSQL 容器", "E:\\Projects\\Tools\\TimeAudit\\TIMEAUDIT_DIAGNOSTIC_SUMMARY_CONTRACT.md"],
    tests: "TimeAudit main 44a842e 的 diagnostic summary provider 合同与测试仍在当前源码；本轮 `--hours 1` 真实查询返回 schema timeaudit.diagnostic-summary.v1、status=ok、coverage=fresh、3702 个样本，最新样本年龄约 0.77 秒，8 个 privacy flag 均为 false。",
    sourcePath: "E:\\.agents\\skills\\timeaudit-diagnostics\\SKILL.md",
    sourceState: `Skill 初始实现来自 d719dea；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与 source/install 供应验证分别回读通过`,
    currentTaskState: "本轮一小时真实 provider 查询通过，未控制或重启任何 TimeAudit 组件",
    freshTaskState: "来源 Owner 的 projectless 任务已发布并回读 Skill 与 provider",
    evidenceObservedAt: `当前 Skill 来源/安装供应回读：${generatedPanelFacts.observedAt}；一小时真实查询现场：2026-08-31 12:13（中国时间）`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 中可发现的 TimeAudit diagnostics Skill、TimeAudit PUBLIC main 44a842e 的 provider/contract/tests，以及既有一小时真实聚合查询；源码、安装、provider 现场与因果结论保持分层。`,
    endToEndState: "固定 Skill → 有界 provider → schema/coverage/聚合解释的真实一小时路径已验"
  }),
  skill({
    slug: "localocr",
    name: "localocr",
    title: "图像理解与精确 OCR 分工",
    status: "已安装 / 三条自然请求验收已通过",
    maturity: "A",
    summary: "处理图片时先看用户真正要什么：只描述场景就用原生视觉；要逐字、坐标、表格或本地处理就用 LocalOCR；既要看画面又要抄文字时，两条路线独立取证并分开呈现。",
    useWhen: ["准确抄写图片里的小字、浅色字或关键数字", "扫描 PDF、多页图片、表格、公式、印章、版面或坐标", "既要描述场景又要准确复制文字", "源像素必须留在本机处理"],
    avoidWhen: ["只需要描述普通照片里的场景、物体、活动、颜色或纹理", "把原生视觉当逐字正确证明", "把 OCR 当场景描述模型", "把空文本直接理解成没有文字", "timeout 后重复创建同一 job"],
    inputs: ["一张或多张图片、PDF 或明确文件夹", "想要的结果：场景描述、精确文字或两者", "是否要求全部本地处理，以及可选 engine、版面模式和输出格式"],
    outputs: ["场景请求的原生视觉观察", "精确 OCR 文字、坐标、置信度、表格和版面结构", "API、TXT、Markdown 与 JSON 中确定性的 display_summary（人话状态摘要）", "分开的视觉观察、精确文字、识别状态、不确定与冲突"],
    flow: ["先按请求结果选择原生视觉、LocalOCR 或两路", "只看场景时直接检查原图，不启动 LocalOCR", "精确文字与结构请求走本机 OCR", "混合请求让两条路线独立读取同一原图", "按视觉观察、精确文字、识别状态和冲突合并答案", "复用返回的 job 和 output，区分 deadline、broker、配置和识别失败"],
    boundaries: ["原生视觉负责场景理解，不是逐字正确证明", "LocalOCR 负责精确文字证据，不是场景描述模型", "两路冲突时保留分歧并复核原图区域，不静默覆盖", "明确要求全部本地时不把源像素交给原生视觉", "display_summary 只投影客观状态，不替代原始 OCR 或 objective sidecar", "不把 timeout 124 当 OCR 失败，不把空文本当否定结论", "GPU 由当前 PCConfig 兼容策略调度：一路 OCR 可与一路 ASR 并行，同类及 Ollama 互斥；普通冲突不创建持久排队任务"],
    dependencies: ["E:\\Projects\\Tools\\LocalOCR", "WSL Python", "PaddleOCR", "LocalGpuBroker"],
    tests: ".agents 31278a0 的 autonomy 回归覆盖混合触发、三路选择与证据分离；来源 Owner 的实现盲自然请求验收已分别通过只看场景、精确抄字、场景加精确文字三条路径。LocalOCR acc6d15 为 display_summary 的客观投影、多格式输出和缓存版本增加回归；此前 18,980 字节小图 auto→ocr、objective 与 job sidecar 的真实验收仍是历史运行证据，本次网站刷新没有重跑源像素。",
    sourcePath: "E:\\.agents\\skills\\localocr\\SKILL.md",
    currentTaskState: "本轮网站任务只核对来源提交、供应状态和公开展示，没有处理新的图片或启动 OCR 模型",
    freshTaskState: "来源 Owner 已用实现盲自然请求分别验收场景只走视觉、精确文字走 OCR、混合请求分离两类证据",
    evidenceObservedAt: "Skill 供应、.agents 与 LocalOCR 远端 main 回读：2026-09-02 12:17（中国时间）",
    evidenceBasis: ".agents source 31278a0 的 LocalOCR Skill、openai.yaml 与自治回归，LocalOCR PUBLIC main acc6d15 的 display_summary 实现/测试，以及来源 Owner 的三条实现盲用户路径；source、install、产品代码、历史真实 OCR 与本轮网站取证保持分层。",
    endToEndState: "场景只用原生视觉、精确文字用 LocalOCR、混合请求分开视觉观察/精确文字/识别状态/冲突的三条用户路径已验"
  }),
  skill({
    slug: "personal-health",
    sourceBytes: 3317,
    sourceSha256: "f70c777fed5919d4caaeaf723843e82f52d64e2a3d92410459775b720340adf0",
    name: "personal-health",
    title: "个人健康上下文",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "回答本人的健康、用药、过敏、检查、趋势、睡眠和活动问题，并在收到新报告或明确刷新设备数据时更新当前健康事实。",
    useWhen: ["问题取决于本人的当前健康资料", "需要解释新检查报告", "需要刷新已登记健康设备数据", "高风险健康建议需要结合权威医学资料"],
    avoidWhen: ["与本人无关的通用健康问题", "恢复旧中央个人系统", "把模型建议写成医生结论", "建立持续后台同步"],
    inputs: ["健康问题、新报告或明确纠正", "设备刷新时的已登记数据入口"],
    outputs: ["基于 CURRENT 的当前回答", "事实、医生意见、模型建议和未知的明确分层", "经 Health Owner 审核的更新"],
    flow: ["普通问题先读完整 CURRENT", "高风险问题再查权威指导", "新报告走 capture 和 brief", "由 Health Owner 复核后更新", "保持 unknown 和证据日期", "共同本人背景会改变回答时才按个人理解库合同读取；有依据的新背景或更正在同任务回写并回读"],
    boundaries: ["不读旧记忆代替 CURRENT", "不建中央画像", "不自动持续同步", "不把建议和事实混写", "健康 CURRENT 已能回答时保持快路径，不为每个健康问题额外加载本人理解库", "报告、药物、医学状态和具体健康建议留在健康项目；共同背景分支不复制病历、设备原始数据或另一份本人档案"],
    dependencies: ["个人健康项目的 CURRENT", "高风险问题的权威医学来源"],
    tests: "2026-08-31 项目当前 112 项合成回归通过；它不代表真实账号或医学 E2E。供应元数据已修复并通过 320 字符预算与 quick validation。",
    sourcePath: "E:\\.agents\\skills\\personal-health\\SKILL.md"
  }),
  skill({
    slug: "daily-preferences",
    name: "daily-preferences",
    title: "个人理解库与可纠正建议",
    status: "已安装 / 共用本人背景与证据回写已实现 / 真实取用按场景核对",
    statusTone: "mixed",
    maturity: "A-",
    sourceKind: "personal_install",
    summary: "把本人基本情况、真实经历、生活重点、价值取舍、认知和偏好放在同一份可查原文、能补充纠正的理解库里。普通问题读相关认识，复杂问题再展开经历和证据；工作、健康、文书等项目按需共用背景，专业事实和行动继续由各自负责。",
    useWhen: ["查询、补充或纠正本人的基本情况、真实经历、生活重点、通用价值取舍与偏好", "希望吃喝、购物、旅行、娱乐、工具或审美建议能结合本人已有经历，并解释为什么", "某个领域任务需要共同本人背景，或产生有依据、值得以后使用的新认识或更正", "用户明确要求更新偏好、按最新资料理解自己或准备投递增量"],
    avoidWhen: ["不相关的普通问题，不加载本人整库", "专业医学、财务计划、工作状态、正式材料或他人关系资料由相应领域维护", "把最新口述自动当作已证事实、把模型评价/模拟经历写成本人真实经历", "因为准备共同背景就提前启动尚未建立的社交或财务项目", "卡号、密码、登录、真实付款或未经授权的外部动作"],
    inputs: ["本人当下原话、补充、更正或改变想法，并保留出处、时间与语境", "当前问题需要的核心认识、摘要索引、完整详卡、现行/历史明示及原文候选", "本机 Chrome、Steam 与本人当前已登录 Chrome 中哔哩哔哩的按需更新", "本人投递的具名平台、订单、支付或对话材料；既有原件保持所属来源位置", "领域回写的稳定 delivery-id、来源项目、原始出处与 expected-current-id"],
    outputs: ["同源 CURRENT 短入口与 PROFILE 完整详档：先说明核心经历、价值与判断意义，再按需展开细节和原文", "保留摘要、完整详述、别名和支持/反例/语境证据的可纠正认识", "supplement（补充）、temporary（临时表达）、correction（更正）、withdrawal（撤回）各自明确的表达版本；旧内容不会因新表述就自动被抹掉", "相关领域已经实际取用的最小本人背景，以及有依据新认识的同任务回写与回读", "开放式推荐仍给每域至少 3 个熟悉稳妥、3 个相邻探索、3 个明确推测的新鲜选择，说明具体内容、适合理由与取舍", "按需刷新逐来源报告采集/导入变化、语义变化和受影响卡片；重复无变化可返回 no_change", "当前来源覆盖、真实缺口与日期；原文命中、程序通过和全面理解不会互相冒充"],
    flow: ["AI 按当前问题、已有上下文、缺口和后果自主决定读多深，不按字数/关键词固定分流", "整体理解先用核心认识和典型经历概括；需要更多细节时读 profile --index 摘要导航，已知键可直接 profile --key 多卡完整读取", "source_materials 是原文候选；需要判断时沿 original 读必要原话与上下文，区分本人说法、转贴、假设和旧 AI 建议", "领域读取/回写遵从 DOMAIN_CONTRACT；共同本人背景在这里维护，专业事实、计划、对象资料和历史成果留在领域", "有新表达时按实际语义区分补充、临时、更正或撤回；更正/撤回指向确切旧表达，同一重试沿用 delivery-id 并核对 expected-current-id", "结合真实依据形成 snapshot 摘要/详卡，证据角色区分 supports、contradicts、context；相关现行表达必须被考虑，但不强迫作为支持", "证据或卡片失效后复核新旧含义，显式重写受影响详述并回读，保留未被推翻的内容，不停在“已记录”", "有更新意图时复用当前 Chrome 获取哔哩哔哩六类行为，再 refresh Chrome/Steam；人工来源没有新包就维持原快照", "普通补包用 incremental，只有同来源完整权威快照才用 full；新增、增强、减弱或无语义变化都要继续解释", "订单/支付、退款、收藏和使用分别判断，事实与偏好推断分开；最后用真实自然问题核对结果能否被当前任务使用"],
    boundaries: ["最新表述的 current 只是版本状态，不是通用最高证据；行动授权、当前自述、事实和稳定推断分层", "旧表达只有明确更正/撤回及其关联依据改变时才影响支持；补充默认保留未撤回的旧内容", "索引摘要、原文候选或命中数量不等于完整原文已读、全语义已整合或身份事实已认证", "支付旁证可靠关联订单时不重复计权；未匹配但有明确品名/商户的有效支付可支持消费事实和可推翻偏好，泛称只证明渠道", "可靠同订单链全额退款使原成功行退出普通偏好和复购计数，原事实保留；部分退款、组单或关联不唯一仍为 partial/Unknown", "收藏、稍后看、追番追剧只在同账号完整 current set 时局部退役；播放、点赞、投币不因窗口消失清退，移除也不反推不喜欢", "Steam 只把实际玩过的 game/demo 用于普通游戏偏好；时长不评分、当前免费略低权，历史取得方式保持 Unknown", "一次成功耐用品、软件或行程仍是正向事实；低频、久远、长期未买和没有记录都不自动等于不喜欢", "更新只在当前请求内发生，不建后台同步、服务、队列、全生活时间线、向量库或第二数据库", "不存在稳定比价 API 不阻止估价或公开搜索，但不冒充实时最低价；除本人要求唯一选择外，保留选择菜单，不代下单付款", "领域共用本人背景不重建旧中央调度，也不复制医学记录、财务账本、工作业务事实或另一份本人档案", "原件与数据根仍走现有 PersonalData 保全；没有独立跨机恢复验收，不把程序完成说成全面了解本人"],
    dependencies: ["daily-preferences 私有项目的稳定入口与 DOMAIN_CONTRACT", "现有单一 SQLite、同源 CURRENT/PROFILE、相关详卡和原文证据定位", "需要更新哔哩哔哩时本人当前已登录的外部 Chrome", "专业领域的实际读取/回写入口；材料与媒体原件由各自项目保管"],
    tests: "2026-09-07 PRIVATE main 1401051，parser v0.12.0、schema 6；185 项 Python 测试及 14 个子测试、7 项 Node 测试通过。只读汇总为 73 个来源实例（12 acquired_verified、61 snapshot_only）、16 个逻辑来源；190,266 条 current / 232,496 条总记录 / 42,230 条历史记录；current/historical 明示 71/32，认知卡 current/historical/stale 为 48/138/152。quick_check 正常、外键问题 0。银行、京东、拼多多、美团、菜鸟 5 项尚缺；YouTube/Maps 已由本人明确排除。",
    sourcePath: "E:\\.agents\\skills\\daily-preferences\\SKILL.md",
    sourceBytes: 19746,
    sourceSha256: "a47c4789347852155aca13588effd55f85893a59a4515da065685b03d58a9723",
    sourceState: "规范 Skill 在 .agents PRIVATE main 7a7fbda 已发布并回读；个人理解库实现源 main 1401051 与活动规则 E118 各自绑定，不互相替代",
    installState: "canonical junction 已安装并指向唯一源码",
    currentTaskState: "本轮核对产品合同、已发布源码和无正文汇总；未读取 CURRENT/PROFILE、私人原文或执行认知重建",
    freshTaskState: "2026-09-05 推荐/三源刷新自然路由为历史验收；当前个人理解库扩展的全新任务真实取用不由旧回执替代",
    evidenceObservedAt: "2026-09-07：.agents 7a7fbda、实现源 1401051、产品合同与只读汇总；历史真实三源刷新为 2026-09-05",
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: "来源 Skill 的当前字节、DOMAIN_CONTRACT、实现 main 1401051、185+14 子测试与 7 Node、只读数据库 aggregate 和完整性回读；没有读取或复制本人详档、原文、具体订单、行程或账号组合",
    endToEndState: "可靠投递、卡片/证据角色与检索合同的合成验证通过；旧真实三源刷新保留为历史，全面了解本人、领域实际取用和跨机恢复仍须对应真实证据"
  }),
  skill({
    slug: "document-materials",
    name: "document-materials",
    registryName: "personal-formal-documents",
    title: "文书和材料制作",
    status: "已安装 / 2.0.1 虚构生成链已验 / 真实事项未运行",
    maturity: "A-",
    summary: "把必要原件整理成合同、说明、申请、通知、售后材料或附件包，同时生成可编辑文档和 PDF 并逐页检查；文件做完、本人签完、真正递送和对方处理会分开记录。",
    useWhen: ["已有明确目标、接收对象和必要原件，需要形成正式可编辑文书", "需要同源 DOCX、PDF、附件清单或自包含材料包", "需要逐页核对、签名图片存在性与可见性、版本冻结和后续状态留痕", "需要判断当前究竟是已生成、本人已签、可递送、已递送、已收件还是已处理"],
    avoidWhen: ["只修改一个已知 Word/PDF 文件，直接使用文档或 PDF 能力", "只需要找到原件，进入个人材料查找", "持续变化的需求、项目评审与执行跟踪，进入工作交付", "通用翻译、随手文案、普通消息或他人的事务", "没有原件或事实依据就补写内容", "把本地生成、签名或 ready 状态写成外部现实结果", "未经精确授权递送、付款、撤回或联系外部对象"],
    inputs: ["当前事项的目标、接收对象、期限、状态和下一步", "最小必要原件、已确认事实、来源说明与真正未知", "输出格式、附件、签名要求和接收渠道", "需要外部动作时对精确对象、版本、内容和动作的授权"],
    outputs: ["可继续编辑的 DOCX、同源 PDF 和核过附件", "绑定输入、审计、逐页彩色/灰度图与所需签名快照的自包含材料包", "内容、页码、页面边缘、签名图片存在性与可见性、精确文件集合与哈希验收", "produced（已生成）、signed（本人已签）、ready_for_delivery（已具备递送条件）、delivered（已递送）、received（已收件）、handled（已处理）的分层状态", "独立的 counterparty_signed_returned（对方签回）记录、下一步与恢复点"],
    flow: ["判断是否应进入本项目", "读取当前事项并只取必要原件", "分开事实、来源说明、未知和本人决定", "冻结DOCX/PDF、附件、签名和渠道方案", "生成同源成品", "重读正文并逐页检查彩色/灰度页面", "形成自包含ready_for_delivery材料包", "现实动作完成后分别回读递送、收件、处理和对方签回", "中断后先核对最近材料包再继续", "相关本人背景来自个人理解库；形成有依据的新本人信息或更正时按同一合同回写与回读"],
    boundaries: ["私人事实、原件、草稿、签名、成品和回执不进入公开 Git", "整包输入固定不等于每条事实来源已机械闭合，真正未知继续保留", "自动字段/页面验收不等于整篇语义和语气已审完", "本人签名与对方签回相互独立", "ready_for_delivery 明确 delivered=false", "不建立数据库、后台服务、队列或第二套材料系统", "正式文书字段绑定本次明确输入；本人理解库后续更正不追改已经签署、递送或保留为证据的历史成果", "具体事项与处理状态仍由文书项目维护，不复制另一份现行本人档案"],
    dependencies: ["受保护的当前材料状态与原件", "正式文书与材料生成、逐页渲染和校验入口", "必要时的原件定位、消息上下文、录音转写或扫描识别能力"],
    tests: `Skill 快速校验、canonical junction（规范目录联接）与 ${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 供应事务通过；2026-09-01 的 2.0.1 基线保留 526 pass、6 skip、101 subtests，以及隔离 wheel 两个入口用 Microsoft Word + Poppler 完成的虚构 plan/build/verify。本轮只重跑通用文书 32 pass，没有运行真实个人材料或外部递送 E2E。`,
    sourceLocatorVisibility: "withheld",
    sourcePath: "withheld:document-materials",
    publicSourceLabel: "个人 Skill 供应链中的“文书和材料制作”入口",
    sourceBytes: 2681,
    sourceSha256: "6c86770191a0895d87eba2fd1657b5f08c0d905bf5581bf9181024898403f0ae",
    sourceState: `文书和材料制作 Skill 内容已正式回读；当前 .agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId} 与供应安装现场另行回读，各层分开说明`,
    installState: "canonical junction 已安装并与规范源码一致",
    currentTaskState: "本轮只运行完全虚构样张，未制作或递送真实个人材料",
    freshTaskState: "安装后的全新 Sol Max 任务已发现“文书和材料制作”入口；发现通过不等于真实事项执行通过",
    evidenceObservedAt: `当前供应链：${generatedPanelFacts.observedAt}；实现与隔离安装验收：2026-09-01`,
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: `文书和材料制作 Skill 当前说明、.agents source ${generatedPanelFacts.sourceCommit.slice(0, 7)}、活动 ${currentERules.releaseId}、${generatedPanelFacts.skills.activeInstallIntent} 个 active install intent、${generatedPanelFacts.skills.transactionCampaignCount}/${generatedPanelFacts.skills.transactionCampaignCount} 终态事务、实现项目 PRIVATE main 3ab7fb4、全仓/聚焦回归与隔离 wheel 虚构验收；供应、实现和真实事项证据保持分层。`,
    endToEndState: "PASS（完全虚构安装后 plan/build/verify）；真实个人材料、真实签名和外部递送 E2E 为 not_run"
  }),
  skill({
    slug: "work-delivery",
    name: "work-delivery",
    title: "工作支持与交付",
    status: "已安装 / 工作支持已扩展 / 真实工作价值待验",
    maturity: "B+",
    summary: "真实工作中的资料理解、沟通、决策、评审和成品交付，都先在现有项目选择最有用的做法。只有来源版本会持续变化、确实需要追溯关系时才建交付包；一次性问题和文件直接完成。",
    useWhen: ["有具体真实工作事项，需要理解资料、准备沟通、判断方案、组织评审或交付结果", "本人选定 2–5 份资料并要求保留版本/来源关系，且需要多种一致成品或持续变化的 PRD", "已有交付包需要沿原 ID 继续更新", "工作任务需要相关真实经历与协作取舍，或产生值得回写的本人认识"],
    avoidWhen: ["只编辑一次单个 Word、PPT 或表格", "没有用户明确选择来源就扫描目录、账号或旧对话", "学习、职业发展、求职或私人文书材料", "未经精确授权发送、发布、审批、建任务或修改外部系统"],
    inputs: ["用户明确选择的 2–5 份需求、会议记录、规则、表格或其他工作资料", "新持续事项的稳定且非空 package ID、标题和目标；已有交付包使用原 ID 进入更新命令", "每条候选事实或假设的值、类别、原文证据、动作和非空决定理由", "本轮实际需要的 docx、pptx、xlsx 格式；只要 PRD 时只请求 docx"],
    outputs: ["来源覆盖、已确认事实、假设、冲突、未知、质量状态和唯一待决定事项", "PRD.md、manifest.json、traceability.csv、产品需求文档.docx、项目评审.pptx、执行跟踪表.xlsx 中本轮实际请求且质量允许的文件", "来源变化后的自动重新绑定、过期事实、过期 build 和下一版决定"],
    flow: ["先明确实际工作问题，按项目 AGENTS 选择资料理解、沟通、决策、评审或制品路径；不把所有问题强制做成交付包", "需要本人通用背景时按个人理解库 DOMAIN_CONTRACT 读取相关内容；有依据的新认识在当前任务回写并回读", "读取项目当前 AGENTS.md 和稳定入口，不在 Skill 里复制实现", "新持续 PRD 使用一个 work-delivery.batch.v1 请求提交 package ID、标题、目标、2–5 份明确来源、证据事实和所需格式", "先交回来源覆盖、关键事实、冲突/缺口和拟采用结构或准确 ETA", "把事实、假设、冲突和未知分开，只让用户处理真正需要决定的项目", "只有 SQLite 重建的 canonical manifest 报告 quality.status=ready 才调用正式 Office 构建；手写 ready 被拒绝", "只要 PRD 时只请求 docx，不等待或启动 PPTX/XLSX", "已有 package ID 通过 update-source、impact、review、build、verify 和 artifacts 继续", "来源更新时唯一原文自动重新绑定，消失或不唯一的事实和引用变化的旧 build 才过期"],
    boundaries: ["一次性单文件或无持续来源关系的普通文本 PRD 直接使用现成文档、演示或表格能力，不增加交付包", "当前正式输出只有 PRD.md、manifest.json、traceability.csv、产品需求文档.docx、项目评审.pptx、执行跟踪表.xlsx；没有现成项目计划、周报或汇报", "可靠输入仍以本地文本、Markdown 和 CSV 为主；其他格式先由相应能力读取或导出", "AI 分析在项目外，Skill 与项目核心都不内置模型或扫描器", "普通 2–5 份来源约 5 分钟内给出覆盖、关键事实、冲突/缺口、结构或准确 ETA；最终时间按来源长度、冲突、输出和同模型同质量直接基线判断", "事实确认后的确定性 PRD.md + DOCX 目标不超过 15 秒；机械时间不冒充整个工作提速", "缺目标、范围、需求、异常、验收、证据或存在关键冲突时，quality 不得 ready，正式 Office builder 保持 0", "没有交付包导出、SQLite 备份、数据库丢失恢复或跨机器迁移", "外部发送、发布、审批、邀请和修改必须由当前请求另行精确授权", "共同本人背景不能冒充已确认业务证据；工作事实、交付状态与专业判断留在工作项目，不另维护本人档案", "没有具体事项时不虚构公司、职位、任务或预建台账"],
    dependencies: ["PRIVATE work-delivery-copilot 项目", "work-delivery.batch.v1 规范请求", "现有文档、演示文稿和电子表格运行时作为正式产物构建依赖"],
    tests: "2026-09-07 source main 57bf3c6 已扩大为工作支持与交付，当前项目回归由主项目证据说明。0.2.0 的 37 项测试、两套合成 Office E2E 与 2026-09-01 无路线提示的 draft 阻断验收保留为历史；它们不证明新广义工作场景的实际价值或真实总用时。",
    sourcePath: "E:\\.agents\\skills\\work-delivery\\SKILL.md",
    sourceBytes: 6155,
    sourceSha256: "306951bda50a0597ed464f698514d6fe7f32e1fc1452d805786fa1d46eb0d80c",
    sourceState: "work-delivery Skill 的当前说明已在 .agents PRIVATE main 7a7fbda 回读；工作项目 main 57bf3c6、活动 E118 与安装证据分别陈述",
    installState: "canonical junction 已安装并与规范源码一致",
    currentTaskState: "本轮只核对当前产品入口与公开安全合同；没有建立真实工作包或处理公司资料",
    freshTaskState: "2026-09-01 fresh Sol Max 的持续交付包路由与 draft 阻断是历史证据；广义工作支持不沿用为本轮 E2E",
    evidenceObservedAt: "2026-09-07：.agents 7a7fbda 与工作源 57bf3c6；合成 Office 和原实现盲验收为 2026-09-01",
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: "当前 .agents 7a7fbda Skill、工作实现 main 57bf3c6 与共用本人背景合同；0.2.0 的 37项回归、合成Office和2026-09-01 draft自然路由为历史证据。当前真实工作/来源变化/同模型同质量收益不由历史测试代替。",
    endToEndState: "既有持续来源包的合成 Office 与无提示 draft 阻断有历史通过；真实工作、首次真实来源变化和同模型同质量时间价值仍为 not_run / baseline_required"
  }),
  skill({
    slug: "documents",
    name: "documents",
    title: "可编辑 Word 文书与逐页验收",
    status: "宿主已集成 / 本轮未跑真实文档",
    statusTone: "mixed",
    maturity: "A-",
    provenance: "宿主集成能力",
    sourceKind: "host_integrated",
    capabilityId: "host:documents",
    evidenceSourceCommit: null,
    summary: "创建、编辑、修订或批注 DOCX（可编辑 Word 文档）时，先按文档用途选结构和样式，再把成品渲染为逐页图片检查裁切、重叠、字体、表格与页眉页脚；只有最后一轮逐页目检通过才交付可编辑文书。",
    useWhen: ["创建或编辑 DOCX / Word 文书", "需要修订痕迹、批注、表单或内容控件", "需要把本地 DOCX 导入原生 Google Docs", "版面、表格、页眉页脚和逐页视觉质量会影响交付"],
    avoidWhen: ["只需要普通纯文本回答", "只读 PDF 而不处理 Word 文档", "把文字提取或 OOXML（Word 文档内部结构）检查当成版面验收", "用户只要最终 DOCX 时交付内部 PNG 或调试 PDF"],
    inputs: ["目标内容、受众、用途与输出格式", "可选模板、参考 DOCX 或必须保留的原结构", "需要修订、批注、表单或 Google Docs 导入时的精确要求"],
    outputs: ["可编辑 DOCX", "需要时的修订、批注、表单或原生 Google Docs 成品", "内部逐页 PNG 目检与结构检查结果"],
    flow: ["有模板或参考时保留原结构与风格；新文档无明确视觉方向时仅在选择器可用且本人未拒绝时提供模板，取消/缺失/失败就继续", "先让标题和开篇清楚说明主题、用途、读者行动与事实依据，不用模板示例虚构作者经历", "发现宿主 workspace 依赖", "按模板或文档类型固定结构与样式 token", "创建或做最小局部编辑", "渲染全部页面为 PNG", "逐页检查并修复后重新渲染", "只交付用户要求的最终文档"],
    boundaries: ["bundle（随宿主发布的能力包）版本只记录本次观察，不作为未来准入", "每个有意义的编辑批次后重新渲染并逐页检查", "Google Docs 新文档先生成并验收本地 DOCX，再走原生导入", "渲染失败先按 packaged renderer 日志诊断；尚未完成逐页目检就如实保留缺口", "只用 workspace dependency loader 返回的运行时与 bundle LibreOffice；不因为 bundled 渲染失败就切到本机另一份 Office", "Google Docs 定向 DOCX 导入前先清除 Word 标题边框残留并回验；原生导入能力与外部写入授权仍独立成立", "用户只要 DOCX 时只交付所需最终文件，逐页 PNG 与调试 PDF 留在内部"],
    dependencies: ["Codex bundled workspace dependencies", "宿主当前 documents capability（文档能力）"],
    tests: "本任务正常能力清单与当前宿主源文件可发现；没有创建、修改或渲染真实制品，Current/Fresh/E2E 保持 Unknown",
    sourcePath: "host:documents",
    observedSourcePath: "E:\\Data\\AppData\\Codex\\plugins\\cache\\openai-primary-runtime\\documents\\26.904.11930\\skills\\documents\\SKILL.md",
    sourceBytes: 42428,
    sourceSha256: "9fcc13c3cc34746b134d4ecf4a3c96c9f464d59944fcc99862b2e69ac953f19e",
    evidenceSourceCommit: null,
    sourceState: "当前宿主规范源文件已读取并核对 SHA-256；版本只是观察，不作未来准入",
    installState: "宿主已集成；按稳定能力发现，不以 bundle 版本准入",
    transactionState: "宿主集成能力不经过个人 Skill 安装事务",
    currentTaskState: "本轮未创建或编辑真实 DOCX",
    freshTaskState: "Fresh task（全新任务）回执 Unknown（未知）",
    endToEndState: "真实文档创建、渲染与逐页验收 E2E 本轮 Unknown",
    evidenceObservedAt: "2026-09-07：宿主当前 bundle 26.904.11930 的真实源文件与本任务能力清单",
    evidenceBasis: "宿主集成 documents capability（文档能力）的源码身份只由结构化来源字段记录；宿主版本不成为准入，本轮没有真实文档 E2E。",
    supplyEvidenceCommand: "Codex workspace dependency loader（工作区依赖发现入口）"
  }),
  skill({
    slug: "pdf",
    name: "pdf",
    title: "PDF 读写、表单与逐页验收",
    status: "宿主已集成 / 本轮未跑真实 PDF",
    statusTone: "mixed",
    maturity: "A-",
    provenance: "宿主集成能力",
    sourceKind: "host_integrated",
    capabilityId: "host:pdf",
    evidenceSourceCommit: null,
    summary: "读取、生成、检查或填写 PDF 时，同时核对内容结构与真实页面；交互表单还要检查 AcroForm（PDF 表单字段树）、页面控件、字段值和外观流，不能用“画面看见值”冒充字段已经正确写入。",
    useWhen: ["读取或审阅版面重要的 PDF", "程序化生成正式 PDF", "填写并验证交互式 AcroForm", "需要逐页检查裁切、重叠、字体、表格或页码"],
    avoidWhen: ["只需编辑 DOCX 源文书", "只看文本提取就判断版面正确", "未经明确要求把可编辑表单压平", "把旧页面图或成功退出码当成本轮 PDF 验收"],
    inputs: ["PDF 原件或要生成的内容与版式要求", "表单字段名、目标值和是否明确要求压平", "页数、关键文本、交互性与视觉验收条件"],
    outputs: ["读取结果、生成 PDF 或已填写表单", "字段树、页面控件、字段值与外观的一致性检查", "全部页面的 PNG 目检结论"],
    flow: ["读取结构与页数", "按任务选择生成、提取或表单路线", "表单同时核对字段树和页面控件", "写入后重新打开并验证逻辑值", "渲染全部页面检查真实外观", "只交付最终 PDF"],
    boundaries: ["bundle 版本只记录本次观察，不作为未来准入", "视觉通过不能替代表单字段树和逻辑值检查", "默认保留表单交互性；只有用户明确要求才压平", "每次有意义更新后重新渲染并检查全部页面"],
    dependencies: ["Codex bundled workspace dependencies", "Poppler", "reportlab、pdfplumber 与 pypdf", "宿主当前 pdf capability（PDF 能力）"],
    tests: "本任务正常能力清单与当前宿主源文件可发现；没有创建、修改或渲染真实制品，Current/Fresh/E2E 保持 Unknown",
    sourcePath: "host:pdf",
    observedSourcePath: "E:\\Data\\AppData\\Codex\\plugins\\cache\\openai-primary-runtime\\pdf\\26.904.11930\\skills\\pdf\\SKILL.md",
    sourceBytes: 7269,
    sourceSha256: "9e429bfc5ada20ccf25a531484e3dcc5da59811d936a7cc5dfd23dbf2dfadd31",
    evidenceSourceCommit: null,
    sourceState: "当前宿主规范源文件已读取并核对 SHA-256；版本只是观察，不作未来准入",
    installState: "宿主已集成；按稳定能力发现，不以 bundle 版本准入",
    transactionState: "宿主集成能力不经过个人 Skill 安装事务",
    currentTaskState: "本轮未读取、生成或填写真实 PDF",
    freshTaskState: "Fresh task（全新任务）回执 Unknown（未知）",
    endToEndState: "真实 PDF 读写、表单与逐页验收 E2E 本轮 Unknown",
    evidenceObservedAt: "2026-09-07：宿主当前 bundle 26.904.11930 的真实源文件与本任务能力清单",
    evidenceBasis: "宿主集成 pdf capability（PDF 能力）的源码身份只由结构化来源字段记录；宿主版本不成为准入，本轮没有真实 PDF E2E。",
    supplyEvidenceCommand: "Codex workspace dependency loader（工作区依赖发现入口）"
  }),
  skill({
    slug: "md-to-pdf",
    name: "md-to-pdf",
    title: "Markdown 导出 PDF",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    provenance: "本地维护插件",
    summary: "在 Windows 上把 Markdown 按文档语义转换成 PDF，支持中文路径、样式配置、精确分页和不依赖 Typora 的导出。",
    useWhen: ["Markdown 需要正式 PDF", "需要 CSS 或 presentation profile", "需要精确页数或分页", "中文文件名和路径必须稳定"],
    avoidWhen: ["需要修改原 Markdown 正文", "把渲染成功当语义验收", "绕过现有文档样式约束"],
    inputs: ["Markdown 源文件", "输出 PDF 路径", "可选 CSS、profile 和页数要求"],
    outputs: ["原子发布的 PDF", "source hash、页数、文本和布局验证结果"],
    flow: ["先判断文档语义", "选择批量 preset 或 styled converter", "优先 Playwright，必要时使用 Edge CLI fallback", "验证 hash、时间、大小、页数和 Unicode 文本", "交给 PDF 安全渲染做目检", "相对图片按 Markdown 原文件目录解析，外链 CSS 中资源按各 CSS 所在目录解析", "严格 expected-pages 先检查 staging PDF；页数不符或不可读时保留已接受输出，不替换"],
    boundaries: ["不修改 Markdown", "不依赖 Typora 许可", "fallback 不降低验收", "陈旧 PDF 不能冒充本轮结果", "输出路径或同一文件身份不能覆盖 Markdown/CSS 原件", "相对资源路径与中文路径保持原语义，不因为把 HTML 放临时目录而丢图或字体"],
    dependencies: ["本地 Edge", "Node 浏览器运行时或 Edge CLI", "md-pdf-toolkit"],
    tests: "2026-09-06 e325d75 与 fbdf978 已发布页数先验后替换、源文件不覆盖及独立 Markdown/CSS 资源基址修复，并增加对应回归；旧 13 项与 4 子测试是历史基线，本轮网页没有生成真实 PDF。",
    sourcePath: "E:\\.agents\\plugins\\md-pdf-toolkit\\skills\\md-to-pdf\\SKILL.md",
    endToEndState: "核心转换与样式路径已验"
  }),
  skill({
    slug: "pdf-render-safe",
    name: "pdf-render-safe",
    title: "PDF 安全渲染与目检",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    provenance: "本地维护插件",
    summary: "把 PDF 的每一页变成清晰图片和一张总览图，方便我肉眼检查排版；同时核对原文件指纹，避免拿旧图片或错误渲染结果当成这次输出。",
    useWhen: ["需要肉眼检查 PDF 布局", "需要高 DPI 页面或联系表", "怀疑输出陈旧", "中文路径或页码选择需要稳定"],
    avoidWhen: ["只验证纯文本内容", "使用未受支持的 shell wrapper renderer", "删除其他任务产生的图片"],
    inputs: ["PDF 路径", "页码、DPI 和输出 prefix"],
    outputs: ["页面 PNG", "contact sheet", "含 source SHA、页数、renderer 和 stale cleanup 的 JSON report"],
    flow: ["150 DPI 全量初检", "定位可疑页", "只对可疑页提高 DPI", "验证 source fingerprint 和输出集合", "结合文本与页数判断"],
    boundaries: ["只删除同 prefix 的陈旧 PNG", "渲染成功不等于语义完整", "不接受 wrapper 冒充 renderer"],
    dependencies: ["Poppler", "Pillow", "md-pdf-toolkit"],
    tests: "测试通过，覆盖页码选择、prefix、renderer 边界和精确 stale cleanup。",
    sourcePath: "E:\\.agents\\plugins\\md-pdf-toolkit\\skills\\pdf-render-safe\\SKILL.md",
    endToEndState: "主要渲染路径已验"
  }),
  skill({
    slug: "mojibake-doctor",
    name: "mojibake-doctor",
    title: "中文乱码诊断与修复",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "诊断 UTF-8、GBK、GB18030、BOM、替换字符、私用区和双重转码，并以预览、备份和原子替换完成可逆修复。",
    useWhen: ["中文出现乱码", "怀疑编码或 BOM 损坏", "出现替换字符或私用区", "可能发生双重转码"],
    avoidWhen: ["没有读取原始 bytes（字节）", "信息已经丢失却强行猜字符", "跟随 junction（目录联接）修改另一个 source（源码）"],
    inputs: ["精确文件或目录", "可选编码线索"],
    outputs: ["scan 和 diagnosis", "默认只读 repair plan", "apply 后的 verify 结果和原字节 backup"],
    flow: ["读取 raw bytes", "scan 和 diagnose", "先 preview", "显式 apply", "重新读取并 verify"],
    boundaries: ["单文件 hash-pinned transaction", "原字节 backup", "atomic replace", "信息丢失时回到 Git、备份或重新生成"],
    dependencies: ["本地 Python"],
    tests: "12 项 Python 测试和专门 Skill 测试通过。",
    sourcePath: "E:\\.agents\\skills\\mojibake-doctor\\SKILL.md",
    endToEndState: "主要修复路径已验"
  }),
  skill({
    slug: "file-intake-router",
    name: "file-intake-router",
    title: "混合附件分流",
    status: "已安装 / 薄路由",
    maturity: "A-",
    summary: "当我一次给出 Word、PDF、表格、图片、压缩包或整个文件夹，不知道该用哪个读取工具时，它先看清文件结构，再把每一类材料交给真正适合的读取器；单个已知文件不需要它。",
    useWhen: ["附件类型混杂", "无法确认是文本 PDF 还是扫描 PDF", "输入是 archive 或目录", "需要先做最小 inventory"],
    avoidWhen: ["一个已知 Word、PDF、表格或图片", "把所有文件都 OCR", "扫描无关子目录", "路由完成后仍继续接管处理"],
    inputs: ["少量文件 inventory", "用户想得到的最终结果"],
    outputs: ["一个最合适 reader 的明确路由", "必要时最小的后续输入范围"],
    flow: ["识别容器和文件结构", "优先结构化提取", "选择 Word、PDF、表格、OCR、ASR 或其他原生 reader", "交接后退出路由"],
    boundaries: ["单一已知类型直接 reader", "先结构化提取后 OCR", "目录只检查满足请求的子集", "默认不上传私有材料"],
    dependencies: ["当前宿主可用的原生 readers"],
    tests: "source、install、quick validation 与 Personal Skill 语义回归均已通过。",
    sourcePath: "E:\\.agents\\skills\\file-intake-router\\SKILL.md"
  }),
  skill({
    slug: "browser-control-continuity",
    name: "browser-control-continuity",
    title: "浏览器连续操作与本地预览",
    status: "已安装 / Fresh 自然路由已验 / 真实浏览证据分层",
    statusTone: "pass",
    maturity: "B+",
    sourceKind: "personal_install",
    summary: "默认接着本人现有外部 Chrome 工作。遇到升级后连不上、单个标签页失联、本地 HTML 预览、异步表单或上传假完成时，先保住已登录和已填写的页面，再沿当前官方安装路线恢复并重新读取真实页面状态。",
    useWhen: ["需要真实浏览本地 HTML，或本人未另选浏览器时应复用外部 Chrome", "浏览控制内核或受管运行文件缺失，但旧标签页和登录态仍有价值", "表单下拉项依赖前一层异步加载，连续点击会丢状态", "需要逐个上传文件并确认页面真正进入成功态", "点击提交后必须从新生成的平台记录核对字段和附件", "一次跨项目浏览故障已经完成真实恢复，需要判断是否沉淀可复用教训"],
    avoidWhen: ["页面专属字段、收件人、业务规则或提交内容，应留在所属项目", "当前没有受管浏览 Provider（能力提供方），本 Skill 不能自造浏览器客户端", "想用本地恢复权限绕过登录、验证码、网站权限或外部动作授权", "只有猜测或一次失败，没有成功恢复和用户可见 E2E", "需要任意下载第三方二进制或覆盖现有运行文件"],
    inputs: ["当前受管浏览 Provider 的原生操作说明", "现有标签页、控制会话与页面的实时状态", "运行缺口报错中精确的 canonical browser scripts 目录", "用户明确选择的单个上传文件和目标表单", "真实失败、最小恢复与最终页面回读证据"],
    outputs: ["保留或重新接管的同一已登录标签页，必要时同 Profile（浏览器配置档）的新标签页", "只复制缺失文件且可清理的临时运行兼容恢复回执", "逐文件 authoritative success（权威成功态）与精确附件数回读", "提交前字段快照、提交后平台记录与实际附件核对", "达到真实证据阈值后原位更新且带退出条件的跨项目浏览教训"],
    flow: ["默认外部 Chrome，先检查本人现有配置和标签页；用户明确另选时服从选择", "本地 HTML 首次导航走已有 HTTP 开发/预览服务；必要临时服务只绑定 127.0.0.1，保留 PID/session、就绪期限与准确清理路径", "浏览运行缺口先读当前 App 的 .codex-plugin/plugin.json，核对 service/files、manifest executable、installer 及四条 appServerRuntimePaths，不相信版本号、.tmp、旧 globals 或 latest 别名", "允许的本地修复先保存 allowed_origins；latest 无法替换时保留别名，使用当前 Host 旁安装器生成的 extension-host-config.json，设置 manifest path、恢复 origins 并回读", "先读当前受管浏览能力的原生说明并列出现有受控标签页", "控制重置后优先重新取得同一标签页；锁定页保留为备份，只有继续价值更高时才在同一已登录 Profile 新开标签", "运行文件缺失时先走官方刷新；无支持路线且满足同官方包族、只补缺失、禁止覆盖时，先 Inspect 再 Repair", "helper 只处理 browser-service.mjs、browser-accessibility.wasm.br 与 zxing_reader.wasm 三个受管文件，并逐一回读 SHA-256", "恢复后必须真实连接并做只读标签页核对，任务结束或原生包恢复后凭 receipt（回执）Cleanup", "上传时先等待 file chooser（文件选择器），再点按钮并一次只放一个绝对路径", "每个文件要求页面 authoritative success 与精确文件名回读后才继续", "异步控件按实时依赖一层层展开，下一层标签出现后再选择", "提交前重读关键字段、附件数与文件名；提交后打开平台记录再次核对", "只有失败、成功恢复与用户可见 E2E 三层齐全时，才把跨项目机制写回本 Skill 并说明退休条件"],
    boundaries: ["这是受管浏览能力之上的连续性层，不是第二浏览器客户端、原始自动化服务器或授权旁路", "优先保护已填写、已登录和用户拥有的标签页，不先重载、导航或关闭", "文件名、100% 进度或页面跳转都不是成功；必须读取页面成功态和最终记录", "临时恢复只补精确缺失文件，核对 source/target SHA-256 一致，不覆盖现有目标，并在原生路径恢复后清理", "本地恢复不授权登录、传输、上传、验证码、删除或最终提交", "不公开标签页正文、附件名、平台记录 ID、截图、秘密或临时回执内容", "跨项目浏览机制归本 Skill，页面字段与业务含义归具体项目", "browser-disconnected 表示新会话也无法读取标签页；stale-debugger-unattached 表示新会话正常、仅旧页脱离调试，保留旧页并用同 Profile 新页，不反复 claim/reset", "status=ready 只说明 source 路线，不证明可执行健康；临时缓存恢复是官方 source/install 修复之后的窄后备", "纯文件生成不启动预览服务；独立 HTML 保持独立文件，临时预览结束只清本任务进程，不建常驻服务"],
    dependencies: ["当前宿主提供的 managed browser Provider（受管浏览能力）", "同一官方 bundled browser package family（浏览器包族）的完整旧版本，仅用于有界缺失文件恢复", "scripts/Invoke-BrowserControlContinuity.ps1 的 Inspect / Repair / Cleanup", "当前任务 E 盘临时目录中的恢复 receipt"],
    tests: "当前 source/install/transaction 供应验证通过；3212630、7cf91e3、b19dacb 修复当前官方插件源优先、精确 Host 注册与新会话闭合判断。当前网页任务没有执行修复、启动新浏览会话或重放真实上传。",
    sourcePath: "E:\\.agents\\skills\\browser-control-continuity\\SKILL.md",
    sourceBytes: 8439,
    sourceSha256: "b9649a131101c4a10991515453cf5e8246645a8231e307992f3cbe54c4d01e7c",
    sourceState: "当前 Skill 与恢复 helper 已在 .agents PRIVATE main 7a7fbda 发布并回读；本轮只检查字节和安装供应",
    installState: "canonical junction 已安装，source 与 quick validation 通过",
    currentTaskState: "本轮读取官方路线与 Skill/helper 合同，未修改浏览器注册、重启控制内核或执行上传/提交",
    freshTaskState: "此前自然路由有历史验收；本轮没有新建浏览会话验收当前安装恢复",
    evidenceObservedAt: "2026-09-07：.agents 7a7fbda；当前官方 host 闭合改动发布于 2026-09-06，历史上传/提交另有原观察日期",
    evidenceBasis: "当前 .agents 7a7fbda 的 Skill 与 helper 字节、已安装个人供应和官方 source/Host/setup 合同；原有真实上传恢复只作为历史事实，不把当前注册存在或 status=ready 当执行健康",
    endToEndState: "旧真实任务的标签页保留、上传成功态与提交回读继续是历史证据；当前安装修复必须另以所选浏览器的新会话与只读标签页核对闭合"
  }),
  skill({
    slug: "media-person-self",
    name: "media-person-self",
    title: "具名媒体中的本人判断",
    status: "已安装 / 图像已验 / 语音复用",
    maturity: "B",
    summary: "需要判断一张指定照片里的人是不是我，或一段指定录音、视频音轨里有没有我的声音时，它只比较这几个明确文件，分别给出图像框或语音时间段和不确定性；不会扫描媒体库，也不会识别其他人。",
    useWhen: ["判断用户是否出现在一张明确照片中", "指出哪个 face box 是本人候选", "判断一段具名录音或视频音轨的精确句段是否支持本人说话", "只有一个文件或很短的显式列表"],
    avoidWhen: ["扫描相册、目录或整个媒体库", "识别或命名其他人", "建立人脸或声纹库", "把相似度当法律身份", "把未测试 cluster 的全部语句都归给本人"],
    inputs: ["一个具名媒体或很短的显式列表", "私有可撤销 face template 或 held-out voice profile", "语音需要精确时间戳句段和最小已绑定上下文"],
    outputs: ["图像的 present、not detected、no face 或 unknown", "face index、bounding box 或精确音频时间段", "self、other、unknown 的覆盖范围和一句可反驳依据"],
    flow: ["照片用固定检测器找 face box", "固定识别器与私有模板比较", "录音和视频音轨复用中文 ASR 的时间戳与匿名 cluster", "对最多两句清晰句段做 held-out voice evidence", "分别输出视觉和语音结果，不强行合并", "质量、profile 或覆盖不足时保留 unknown"],
    boundaries: ["不暴露模板向量、声纹或内部相似度", "不命名其他人", "不复制或修改源媒体", "不从文件名、时间接近或目录推断身份", "删除或替换 profile 会改变未来判断"],
    dependencies: ["本地 YuNet 与 SFace", "私有 person:self face template", "ChineseASR 的 Paraformer、时间戳和 held-out voice profile"],
    tests: "照片 adapter 8 项测试通过；语音链复用中文 ASR 的既有句段证据能力，Skill 自身仍缺少一组独立语音回归。",
    sourcePath: "E:\\.agents\\skills\\media-person-self\\SKILL.md",
    endToEndState: "照片路径已验；并发候选不计入"
  }),
  skill({
    slug: "local-secret-broker",
    name: "local-secret-broker",
    title: "本地凭据 Broker",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "需要确认某个账号或密钥是否存在、让程序使用它、或做备份恢复时，它从本机 Password Center（密码中心）走受保护入口处理；默认只返回账号和状态，不把密码或访问令牌暴露到聊天、命令行和普通文件。",
    useWhen: ["查询某个账号或 SecretRef 是否存在", "需要精确获取一个凭据字段", "让浏览器或程序 blind fill", "执行凭据备份、恢复或轮换", "一个已登记本地载体需要在原环境缺失时独立恢复"],
    avoidWhen: ["把秘密放进聊天、argv、环境变量或普通文件", "未明确请求就揭示明文", "自动处理验证码、Passkey 或 CAPTCHA", "设备处于不可信状态"],
    inputs: ["目标服务、账号或 SecretRef", "一个精确 operation", "需要明文时的明确请求和人类因子"],
    outputs: ["metadata-only lookup", "受保护 capability 或 blind-fill 结果", "必要时单字段明文，不进入普通日志"],
    flow: ["普通查询先 metadata-only", "沿固定 reference 选择精确 operation", "需要最高权限时触发相应因子", "在消费点执行", "正式 read-back", "精确载体恢复由现有 RecoverRegisteredCarrier 生成请求/新运行绑定，先检查选中备份再进行所需因子确认", "本地恢复成功但备份刷新部分失败时，只用 Backup -Query carrier_id 重试该载体，不重复恢复或复用已消费请求"],
    boundaries: ["秘密值不进入公开面板", "人类验证失败只暂停", "管理员权限令牌不扩大授权", "device untrusted（设备不可信）时失败关闭", "载体 ID 只从 PCConfig 登记读取，恢复不依赖旧 C Policy/CoreGoal，也不覆盖仍可读旧备份", "替换设备上的恢复码按备份验证，不要求事先已有本地密码数据库；本网站不执行或接收任何秘密"],
    dependencies: ["PCConfig Password Center（密码中心）", "KDBX 或相应秘密权限来源", "活动保护策略"],
    tests: "精确 lookup fast-path（快速查询路径）测试通过；活动规则权威当前有效。",
    sourcePath: "E:\\.agents\\skills\\local-secret-broker\\SKILL.md",
    endToEndState: "受保护场景按需验收"
  }),
  skill({
    slug: "authorization-file-broker",
    name: "authorization-file-broker",
    title: "最高权限文件加解密",
    status: "已安装 / 受保护",
    maturity: "A",
    summary: "当用户明确说要加密或解密某几个文件、某个目录时，它让 Password Center 完成真正的加密、校验和中断恢复；源文件不删除，遇到同名冲突也不会覆盖。",
    useWhen: ["批量加密明确文件或目录", "验证加密 bundle 而不落地明文", "解密到明确目标", "中断后继续已授权任务"],
    avoidWhen: ["扫描磁盘寻找文件", "分析文件语义", "覆盖已存在冲突文件", "删除源文件或 bundle"],
    inputs: ["精确源路径和目标", "Encrypt、Verify 或 Decrypt operation", "最高权限因子"],
    outputs: ["加密 bundle 或恢复目录", "不含内容和 key 的 receipt", "冲突与未处理项"],
    flow: ["解析精确对象", "取得最高权限能力", "执行 Encrypt、Verify 或 Decrypt", "中断时从 authenticated state 恢复", "正式 read-back"],
    boundaries: ["内容和 key 不进入聊天、stdout 或 JSON", "不覆盖冲突", "不删除源", "不扩大到未点名路径"],
    dependencies: ["Password Center", "活动最高权限链"],
    tests: "6 项测试通过，覆盖 round-trip、恢复、幂等解密、篡改和 source change fail-closed。",
    sourcePath: "E:\\.agents\\skills\\authorization-file-broker\\SKILL.md",
    endToEndState: "受保护 round-trip 已验"
  }),
  skill({
    slug: "vault-workflow",
    name: "vault-workflow",
    title: "本地加密库查看、编辑与备份",
    status: "已安装 / 隔离回归已验",
    maturity: "A",
    summary: "为 vault-tool 选择仅检查、本地查看／编辑或私人密文备份入口。只检查时不解密；需要原文时明确指定库，由本人在本地输入密码和必要密钥文件。编辑保留未改成员与原参数；普通密文发布有远端字节回读，README保护另报其较窄的API结果。不把未保存退出当成功，也不与密码中心混用。",
    useWhen: ["不打开原文地检查库结构与环境", "在本机查看或编辑指定库里的支持文本", "核对精确密文的私人备份", "明确要求保护指定远端 README 正文"],
    avoidWhen: ["把它当 Password Center（密码中心）", "把密码交给模型或命令行参数", "向非 PRIVATE（私有）目标发布", "把预演、路径存在或关闭窗口当成保存完成"],
    inputs: ["明确的模式、操作意图和目标库；LocalView/LocalEdit 要求 VaultFile", "本人只在本地输入密码，按库要求选择精确密钥文件", "远端写入还需明确的私人目标、路径和制品"],
    outputs: ["不含原文的元数据、建议与实际效果状态", "本地窗口中的支持文本，或明确的 saved／未保存／取消结果", "普通发布的真实写入和远端密文字节回读；README保护只有单提交API结果，不混同"],
    flow: ["先分清仅检查、本地读写还是远端动作", "检查模式只读结构和环境，不自动执行建议", "本地读写明确目标，本人提供所需凭据；不捕获会打印明文的CLI查看输出", "保存前检查成员、原KDF（密码派生参数）和槽位容量；不能保真则停止", "普通密文发布核对默认分支字节；README保护只有本地候选自检与单提交API结果，后续字节回读另列未实现"],
    boundaries: ["密码和原文不返回模型；本地读写不把原文落盘", "PromptOnly只采集并丢弃输入，不验证密码或自动找库", "编辑不静默更换密钥文件、KDF或丢弃未解锁槽", "回退失败须保留失败状态和密文恢复副本，不能被下一次操作洗成成功", "与密码中心及其最高权限文件入口各自独立"],
    dependencies: ["vault-tool 的本地容器与加密实现", "PowerShell 适配脚本和本地 Tk 图形界面", "仅远端动作依赖 GitHub 私人目标与现有 gh 工具"],
    tests: "本轮41项虚构文件回归通过，覆盖元数据、成员与参数保真、容量拒绝、保存和回退失败、发布结果字段校验；独立复验通过。真实密码框、私人远端和换机恢复不由隔离替身测试代替。",
    sourcePath: "E:\\.agents\\skills\\vault-workflow\\SKILL.md",
    endToEndState: "隔离样例已验；真实私人操作未验"
  }),
  skill({
    slug: "project-entry-gate",
    name: "project-entry-gate",
    title: "Git 项目身份入口",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "在准备改代码、提交、推送、发布或恢复仓库前，它先确认我究竟在哪个仓库，这个仓库是公开还是私有，当前分支和远端是什么，有没有未提交或未同步的改动，以及现在能不能安全继续。它只提供事实，不替用户授权推送。",
    useWhen: ["不确定当前 checkout（本地检出目录）属于哪个仓库", "准备恢复、迁移、推送或发布", "需要确认仓库是公开还是私有、默认分支是否正确", "多个 Git worktree（工作树）和同步状态会影响实施"],
    avoidWhen: ["已经明确仓库身份、只做普通可逆本地编辑", "把 admission（准入结果）误当成用户已经授权推送", "Git 动态事实不会改变当前决定却仍做全量扫描"],
    inputs: ["要检查的 GitHub 仓库 owner/repo（仓库所有者或命名空间 / 仓库名，例如 wlyaaaaa/wly0829.cn）", "可选的本地工作树或目标分支", "这次只需缓存、实时 GitHub 信息、刷新远端引用，还是完整发布检查"],
    outputs: ["真实本地仓库路径、远端地址、公开性、当前分支、上游分支、工作树、未提交改动和同步状态", "明确的继续、先处理再继续或停止建议；它本身不产生用户授权"],
    flow: ["先判断当前决定需要多新的 Git 事实", "调用 Git Owner 的 admission（准入检查）", "只检查本次指定的工作树或分支", "把事实结果与用户授权分开", "真正发布前再次用完整 publication profile（发布检查）回读"],
    boundaries: ["仅仅出现一个绝对路径不会自动触发", "cached（缓存）事实不能冒充 live（实时）事实", "decision（建议结果）不会自动授予 push（推送）权限", "仓库公开风险不清楚时停止发布"],
    dependencies: ["E:\\GitHub总索引", "Git 和 GitHub metadata"],
    tests: "Skill 和 Provider fixture 通过，覆盖 identity、visibility、target、sync、dirty、no-upstream 和 public exposure。",
    sourcePath: "E:\\.agents\\skills\\project-entry-gate\\SKILL.md",
    endToEndState: "真实仓库 admission 已多次使用"
  }),
  skill({
    slug: "personal-panel-refresh",
    name: "personal-panel-refresh",
    title: "个人看板实质刷新与发布合并",
    status: "已安装 / 来源暂停与对应快照合并边界已更新",
    maturity: "A-",
    summary: "一个已登记项目、规则或能力发布后，它只检查网站里对应的说明会不会因此说错话。需要更新时优先交给正在发布的网站负责人合并；没人负责才开新任务，不扩成全站重做，也不让来源项目原地等待。",
    useWhen: ["来源项目已经完成发布和正式回读", "本次变化涉及网站登记的项目、规则或能力", "页面里的事实、解释、边界、成熟度或使用判断可能因此变错", "网站可能已有另一个活动发布 Owner，需要避免重复发布或竞争写入"],
    avoidWhen: ["来源还只是草稿、候选或未验证状态", "只有格式、注释、内部重构、时间戳或仅哈希变化", "当前页面已经准确说明受阻状态，没有新的实质失真", "需要本人明确启动的页面没有新的更新请求", "试图让来源工作直接修改、测试或发布网站"],
    inputs: ["网站登记的项目、规则或能力", "来源身份、正式远端回读提交、改动路径、观察时间与活动代际", "assessor（影响评估器）原因与为什么页面会实质失真的 Source Owner 判断", "产品、Rules、Skills、System 中确实由这个来源直接影响的公共表面"],
    outputs: ["无需更新，或需要网站跟进的实质判断与理由", "发送给现有活动发布 Owner 的一次有界增量，或没有活动 Owner 时安排一份全新网站工作", "绑定来源身份、回读提交、改动路径、观察时间与活动代际的对应快照增量", "产品与技术新增、修改、退役/替代和 Unknown 的有界语义差分", "Project、Rules、Skills、System 各自 changed、unchanged 或 blocked 的闭包", "一个稳定发布批次的一次完整网站检查、单次定向提交、现有 PUBLIC main 正常推送、Pages 部署与公网回读"],
    flow: ["本人暂停更新或要求稍后合并时，先暂停该范围的自动评估与交接；来源本身的编辑、测试、发布继续", "等来源 Owner 完成自己的发布和正式回读", "每次重新读取网站登记清单，把来源解析到唯一对应快照，只运行相关路径影响评估，不枚举无关项目或转成全站复核", "Source Owner 对照当前页面判断是否真的实质失真", "不影响页面或需要本人明确启动的页面没有新请求时明确 no-op", "读取实时任务列表；只有状态精确为 active 且当前 Owner 范围覆盖本次网站发布才复用，标题、更新时间、旧交接、历史 Owner 或来源对话都不充分，其他状态全部排除", "存在唯一合格发布 Owner 时只发送一次来源身份、提交、路径、原因、实质判断和受影响表面；即使它由另一来源创建或正在刷新别的登记快照，也由它合并同一候选", "没有合格发布 Owner 时保留本人当前明确的 Astra Max 语义执行选择、核对原生身份与父级上限后安排一份全新网站工作", "安排受理只证明发送或创建成功，不证明已读、合并或完成；来源立即继续，不等待、不轮询", "网站负责人为每个增量绑定来源身份、回读提交、路径、观察时间和活动代际；同源后继提交只替换被它包含的同源证据，其他来源增量继续保留", "只有来源输入、E 代际、Registry revision（登记表修订号）和负责表面仍匹配时才复用证据；同源新提交本身不制造 Owner 范围反复变更", "先完成一个连贯编辑批次和对应聚焦检查；批次稳定后只运行一次完整测试、构建、公开内容门和最终浏览验收", "同一失败类别在输入未变时重复两次就先诊断共同原因；预览服务使用可控后台会话、就绪期限和仅清理本任务进程的收口", "全部检查通过后只发布一次现有 PUBLIC main，等待 Pages 并从公网回读"],
    boundaries: ["每次来源事件只更新它的对应登记快照与会因此说错的直接表面，不调用全站复核", "不复制网站登记清单", "不建 watcher（监视器）、daemon（后台进程）、定时任务或轮询", "不在来源工作里编辑、构建、测试或发布网站", "不把草稿、候选或未验证状态当成已发布事实", "同一来源提交与同一网站目标不重复发送或创建", "现有活动发布 Owner 优先；发送失败时不另开竞争任务", "不把开发或预览服务当前台长任务等待；只启动可控制、可限时并能准确关闭的后台会话", "语义判断和正文写入不降级到 Luna、Terra 或本地模型，也不把今天的精确模型写成永久上限", "跨任务派发受理不等于对方已读或完成，来源不读取进度、不等待、不轮询", "现有长期授权不跳过 system/developer/platform、Owner scope、目标解析、拒绝、补证、网站检查或本人预览，也不覆盖新公网目标、付费、秘密暴露、force-push（强制推送）或用户明确暂缓", "恢复只按本人后续指令取当前已发布事实，不自动重放暂停期间每个提交，也不建立暂停登记表、积压队列或第二定时任务", "全站增量由网站既有统一任务或本人明确全量请求负责；来源 Skill 仍只处理一个对应快照", "本网站内容、设计、创意与内容验收当前默认 Astra Max；可用性不足如实报告，不静默降为旧默认"],
    dependencies: ["wly0829.cn Registry 与路径影响评估器", "网站 Execution Owner 与当前任务状态解析", "native-economy-routing 的当前模型家族与思考强度选择", "桌面 AI 工作台的现有任务跟进与全新工作入口", "已验收的 PUBLIC main、GitHub Pages 与公网回读路径"],
    tests: "当前 Skill source、install 与供应事务通过；原有单快照、精确 active Owner、失败不创建竞争任务和稳定批次语义继续保留。当前源增加暂停时先停自动交接、恢复按新指令读取已发布事实，不回放积压或建队列。",
    sourceState: "当前 personal-panel-refresh 唯一源码在 .agents PRIVATE main 7a7fbda 发布；网页语义执行默认 Astra Max 来自本人当前项目明确要求，源 Skill 的历史 Sol 质量下限不覆盖该要求",
    currentTaskState: "本轮为本人明确发起的恢复更新候选；实际发布尚未完成，不能把本地候选或派发受理写成 Pages 已闭合",
    freshTaskState: "既有无活动 Owner 新建路线和活动 Owner 跟进路线为历史验收；本轮以当前明确请求和真实施工范围推进",
    evidenceObservedAt: "2026-09-07：.agents 7a7fbda 与当前项目明确 Astra Max 选择；此前网站发布回读为历史证据",
    evidenceSourceCommit: generatedPanelFacts.sourceCommit,
    evidenceBasis: "已发布 Skill、活动 E118、当前网站项目要求和本轮精确源码范围；没有用历史 Pages 或旧 active Owner 接受回执证明本候选发布",
    sourcePath: "E:\\.agents\\skills\\personal-panel-refresh\\SKILL.md",
    sourceBytes: 8374,
    sourceSha256: "da27e3d130b31ad65d584ca992c3f4b414b32ea485c724aec1de04e2e5b22519",
    endToEndState: "历史派发/发布路线保留；本轮候选整合、Astra Max 独立验收、Pages 与公网回读由网站主任务分别闭合"
  }),
  skill({
    slug: "control-plane-doctor",
    sourceBytes: 4503,
    sourceSha256: "b75e71563ad7fe8f44a11a226be5f3417c460d29d116fbc723beb71a1393787b",
    name: "control-plane-doctor",
    title: "能力可用性与三控制面体检",
    status: "已安装 / 回归通过",
    statusTone: "pass",
    maturity: "A",
    summary: "问“这个能力现在能用吗”时，它可只检查具名 Skill 的源码、安装和使用验证覆盖；问三个控制面状态时，才按选中的责任源汇总健康、警告与收口问题。诊断不代替真正完成业务任务，也不自动修复。",
    useWhen: ["只想知道一个具名 Skill 的供应是否健康、当前/全新任务/真实场景到底验到了哪里", "明确要求控制面健康检查", "需要漂移或迁移验收", "跨仓库恢复", "需要聚合 health 和 convergence"],
    avoidWhen: ["普通项目实现", "直接实施修复", "没有选择 Owner 却扫描全部控制面", "把 cached warning 当 block"],
    inputs: ["可单独给 SkillName；不必知道控制面内部 check 名", "Owner、check 和 freshness"],
    outputs: ["各 Owner 的 health、convergence、warning 和 block", "精确 remediation owner", "supply_health 与 verification_coverage 分开；未知的使用覆盖不把健康供应判坏，也不声称真实可用"],
    flow: ["具名 Skill 可只用 -SkillName，等价于 agents/skill_supply；显式 Owner/CheckId 会保留并验证所选范围", "按选择的 Owner 调用精确 provider", "默认 cached 和 zero-write", "聚合而不篡改原状态", "需要修复时退出 Doctor 并交给真实 Owner"],
    boundaries: ["不修复、不安装、不改任务", "不 commit 或 push", "未选择的 Owner 连 provider 路径都不读取", "warning 与 block 分开", "未安装意图、退役或未知名称只报告限制，不自动安装或复活", "普通状态问题不先跑仓库测试；只有当前实现改动或怀疑缺陷才验证相应代码", "默认不传 Owner 时兼容选择三个责任源；正常具名问题主动收窄，不把全扫作为前置门"],
    dependencies: ["Personal Skill validator", "Git admission", "PCConfig drift provider"],
    tests: "Owner scope 与 Skill metadata 测试通过；description 已恢复为显式 Use when 入口。",
    sourcePath: "E:\\.agents\\skills\\control-plane-doctor\\SKILL.md"
  }),
  skill({
    slug: "tailscale-safe-exposure",
    name: "tailscale-safe-exposure",
    title: "Tailnet 精确暴露",
    status: "已安装 / 环境条件型",
    maturity: "B",
    summary: "需要让一台指定设备通过 Tailscale 访问本机服务，或检查 Sunshine/Moonlight 为什么走直连、DERP 或中继时，它先看当前监听和防火墙，只开放必要端口给必要 peer，并记录怎样回滚。普通局域网和 Wi-Fi 问题不走它。",
    useWhen: ["只允许 tailnet 内访问本地服务", "需要 peer-scoped firewall", "检查 reverse port 或 loopback 暴露", "验收 Sunshine/Moonlight direct、DERP 或 Peer Relay"],
    avoidWhen: ["普通 LAN、Wi-Fi 或 VPN 问题", "默认打开 Funnel", "把 RemoteAddress 设为 Any", "一次修改多个机制和端口"],
    inputs: ["精确 service、protocol、port 和 peer", "当前 Tailscale 身份、监听和 firewall 基线"],
    outputs: ["preimage、最小配置差异、rollback", "本机、tailnet 和 peer 分层验收"],
    flow: ["读取身份和监听基线", "选择单一最小机制", "记录 preimage 和停止条件", "执行一项变更", "read-back 与具名 peer 验收", "失败按预记 rollback"],
    boundaries: ["默认禁 Funnel", "禁止宽泛 remote/interface", "read-back 失败即回滚", "没有具名 peer 不能声称 E2E"],
    dependencies: ["Tailscale CLI", "精确服务和 peer 环境"],
    tests: "本机 CLI 当前存在；未做本轮具名 peer 连接验收，也没有独立 Skill 全套测试。",
    sourcePath: "E:\\.agents\\skills\\tailscale-safe-exposure\\SKILL.md",
    endToEndState: "具名 peer E2E 未验"
  }),
  skill({
    slug: "llm-backend-toolkit",
    name: "llm-backend-toolkit",
    title: "额外模型 Backend 工具箱",
    status: "已安装 / 回归通过",
    maturity: "A",
    summary: "当原生子代理不适合、但有一个范围很小且结果可以独立验收的任务时，它可以把这个任务交给本机登记的其他模型后端，保存 job 和结果，再由顶层模型复核。普通并行仍优先原生子代理。",
    useWhen: ["任务封闭且有独立 verifier", "原生代理之外的 Backend 有明确净收益", "允许保存 job、result 和 receipt"],
    avoidWhen: ["普通子代理委派", "没有独立验收标准", "把显式 crosscheck 当 fallback", "云文本没有 cloud allowed"],
    inputs: ["有明确目标和 verifier 的 request JSON", "隐私是否允许云端"],
    outputs: ["job id、result 和 receipt", "由顶层模型独立验收后的结论"],
    flow: ["读取 live backends", "选择符合边界的一条 route", "submit", "按建议时间读取一次 job result", "保留 receipt，由顶层模型验收"],
    boundaries: ["不是原生 child（子代理）", "不自动 fallback（切换后备路线）", "失败不能冒充 complete（完成）", "registry（登记表）状态会漂移，必须现场读取"],
    dependencies: ["E:\\.agents\\config\\llm-backend-registry.json", "对应 Provider runtime"],
    tests: "专项测试、live backend listing、quick validation 和 metadata 语义断言全部通过。",
    sourcePath: "E:\\.agents\\skills\\llm-backend-toolkit\\SKILL.md"
  }),
  skill({
    slug: "native-economy-routing",
    sourceBytes: 2874,
    sourceSha256: "ce8eaa135f755a1398b540f5d8dd3bdba89aed993c2251a229779e78a56445c8",
    name: "native-economy-routing",
    title: "原生代理经济路由",
    status: "已安装 / 宿主条件型",
    maturity: "B",
    summary: "当任务能拆成互不冲突、可以分别验收的支路时，它先确认当前工作台真实提供的模型、思考强度和父子角色，再判断开零到十个子代理是否真的能提高质量。每个子代理只拿必要范围，创建前再复核一次现场；身份不可靠时只关闭并行委派，主任务继续。",
    useWhen: ["任务出现独立可验支路", "上下文压缩或重大 steer 后需要重判", "child 完成或槽位释放", "当前任务确实需要原生并行"],
    avoidWhen: ["没有可信宿主身份", "普通工具步骤", "把代理名称当身份证明", "固定默认某个模型家族"],
    inputs: ["UserPromptSubmit（用户请求进入时）或 SubagentStart（子代理启动时）注入的 verified model（已验证模型）、effective effort（实际思考强度）、root/child（根/子代理）、turn hash（本轮指纹）、E release 与 contract SHA", "旧 root 完全没有 Hook（宿主钩子）或注入时，同一任务中用户已经给出的自然语言 model/effort 确认；确认层规范化别名，thread binding（任务绑定）只保存 canonical ID（规范标识）", "当前任务的独立支路、slots（并行槽位）、资源和写入冲突", "PreToolUse（工具创建前复核）在真实 spawn（创建子代理）前取得的身份、家族、effort 与参数"],
    outputs: ["0 到 10 的直属代理判断", "模型家族、effort、scope 和 fork 边界", "Luna/Terra/Sol/Astra 四档或同一未分类型号的真实选择依据，受根与直接父双上限"],
    flow: ["root 的 UserPromptSubmit 或 child 的 SubagentStart 在 0–10 判断前注入可信身份与当前 E identity", "只有旧 root 完全没有 Hook 或注入时，才把同一任务中已有的自然语言 model/effort 确认规范化后写入并回读耐久 thread binding；child 不继承", "上下文压缩、E identity 变化或加载不确定时重读当前 11 条路由规则、重派生并刷新代际快照；E 换代本身不要求用户重复确认", "代理自己按任务语义、净收益、冲突和 slots 评估 0–10、模型家族与 effort", "真实 spawn 前由 PreToolUse Hook 复核 TOCTOU、家族上限、effort 上限和参数", "root 继续负责方向、集成和最终验收，不因派出 child 原地空等", "Luna 适合封闭可验读重工作，Terra 适合强耦合与深调试，Sol 适合复杂实现、战略与终审，Astra 用于关键路径最高难度和减少返工；按总交付成本判断", "遇到其他 verified 型号时标 unclassified，允许同一精确 ID 后代，不猜更强或自动转派便宜型号"],
    boundaries: ["Hook 只验证身份、E identity 与参数，不选择模型家族或代理数量、不创建 child，也不制造授权", "耐久 thread binding 只用于完全没有 Hook 或注入的旧 root，只落 canonical ID，child 不继承", "E release 换代不撤销已经成立的用户确认；规则明确撤销该路径或身份冲突时才失败关闭", "PreToolUse 只是 spawn 前复核，不能代替判断前的可信身份", "Hook 或有效绑定缺失只关闭委派，普通调查、实现和最终答复继续", "不依赖 Stop Hook；app version（应用版本）和 versioned path（带版本路径）不是准入条件", "委派只能收窄 scope、授权、家族和 effort，root 始终保留最终责任", "四档为 gpt-5.6-luna、gpt-5.6-terra、gpt-5.6-sol、gpt-6-astra；每档只派本档与已知更低档", "档位取宿主实际可用集；Luna/Terra Max 是常用质量基线，不是禁止低档的门；后代 effort 不超过根/直接父及 ultra", "task name 以实际模型与启动 effort 开头，只为可读性，不证明身份；槽位满本身不授权创建顶层任务"],
    dependencies: ["宿主 UserPromptSubmit 与 SubagentStart Hook", "旧 root 的耐久 thread binding 入口", "真实 spawn 前的 PreToolUse Hook", "当前 E release 与 capability contract", "宿主原生 child identity（子代理身份）与 slots"],
    tests: "聚焦 Gate 与 Hook 回归覆盖判断前身份注入、旧 root 对话绑定、PreToolUse 创建前复核、无 Stop Hook 依赖和更新连续性；真实可用性仍由每个任务的宿主身份、E identity、授权与 slots 决定。",
    sourcePath: "E:\\.agents\\skills\\native-economy-routing\\SKILL.md",
    currentTaskState: "按本次 UserPromptSubmit 或 SubagentStart 注入的宿主身份与 E identity 现场判断；不沿用其他任务的 child 数量或回执",
    freshTaskState: "每个新任务必须重新取得自己的宿主身份；只有完全无 Hook 的旧 root 可建立耐久绑定，child 不继承",
    endToEndState: "判断前注入与创建前复核是两层独立证据；创建成功只证明该次宿主路径，每个任务仍需独立验证模型、effort、E identity 与结果"
  }),
  skill({
    slug: "token-budget-advisor",
    name: "token-budget-advisor",
    title: "工作台配额与 GPT-5.6 Sol 文本计量",
    status: "已安装 / 上次 Fresh task E2E 已验",
    maturity: "A",
    summary: "仅在用户明确询问当前工作台配额或 reset（重置）状态，或要求按 GPT-5.6 Sol 的权威口径计算、比较可见文本的模型计量单位（Token）时触发。配额走只读账号用量入口；Token 优先使用完成响应 usage 或官方 input_tokens，不能取得时返回 Unknown。",
    useWhen: ["用户明确询问当前工作台 quota（配额）或 reset（重置）状态", "用户明确要求按 GPT-5.6 Sol 统计可见文本 Token（模型计数单位）", "比较两个 Prompt（提示词）或文件的 Token 数", "接近明确 Token 边界，需要官方计数"],
    avoidWhen: ["仅仅因为任务长或可能压缩就自动触发", "推断隐藏 prompt、tools 或 reasoning", "把估算当成正式账单", "为了报告数字而回显用户正文"],
    inputs: ["明确的 quota/reset 问题，或一段可见文本/明确文件", "GPT-5.6 Sol 计数口径", "可选的明确 Token 数值预算"],
    outputs: ["只读配额/reset 状态，或 GPT-5.6 Sol 权威 Token 数", "使用的 usage/input_tokens 来源和没有计入的内容", "安全低于、接近、超过预算或 Unknown 的判断"],
    flow: ["配额问题读取只读 account/rateLimits 状态", "Token 问题优先使用响应 usage 或官方 input_tokens", "官方计数不可用时返回 Unknown", "只报告数字、方法、排除项和边界判断"],
    boundaries: ["不猜隐藏上下文", "不回显正文或账号标识", "不计算 API 价格或美元成本", "不把字符、字节或其他模型计数冒充 GPT-5.6 Sol"],
    dependencies: ["工作台只读 usage 状态入口或官方 input_tokens 计数"],
    tests: "Source、quick validation、autonomy、semantic、junction installer 和 supply contract 全部通过；Fresh 0.150.1 root 已发现并实际调用 Skill，o200k_base exact=3，预算 10 时返回 safely_below。",
    sourcePath: "E:\\.agents\\skills\\token-budget-advisor\\SKILL.md",
    freshTaskState: "Fresh root（全新根任务）已发现并实际使用",
    endToEndState: "Token 计数路径已有历史验收；当前配额/reset 只在用户明确请求时现场读取"
  })
];

export const excludedSkills = [];
