"""留空位与样稿组件；由主引擎自动发现。"""
from .shots import render_screenshot, render_screenshot_compare, SHOT_SPEC_FIELDS
from .live import render_live_box, render_live_embed
from .controls import render_input_field, render_button_variants
from .mocks import render_document_mock, render_site_chrome_reference

COMPONENTS = {
    "screenshot": render_screenshot,
    "screenshot_compare": render_screenshot_compare,
    "live_box": render_live_box,
    "live_embed": render_live_embed,
    "input_field": render_input_field,
    "button_variants": render_button_variants,
    "document_mock": render_document_mock,
    "site_chrome_reference": render_site_chrome_reference,
}

# 只登记本族实际消费的规格字段；未知正值由主引擎记未完成。
SPEC_FIELDS = {'screenshot': ['indices',
                'columns',
                'columns_v',
                'ratio',
                'ratios',
                'max_width',
                'max_width_v',
                'align',
                'text_position',
                'caption_mode',
                'caption_per_slot',
                'slot_groups',
                'number_position',
                'label_above',
                'equal_row_height',
                'connector',
                'frame_style',
                'protected_parts',
                'items_layout',
                'requested_slots'],
 'screenshot_compare': ['indices',
                        'columns',
                        'columns_v',
                        'ratio',
                        'ratios',
                        'max_width',
                        'max_width_v',
                        'align',
                        'items_layout'],
 'document_mock': ['variant',
                   'columns',
                   'header_nodes',
                   'footer_nodes',
                   'section_starts',
                   'heading_refs',
                   'highlights',
                   'status_prefixes',
                   'mock_layout',
                   'layout',
                   'appearance',
                   'directory_art',
                   'file_icons',
                   'attach_to',
                   'labels',
                   'label_role',
                   'echo_repeats',
                   'base_asset',
                   'base_asset_index',
                   'label_text_ref',
                   'label_columns',
                   'label_rows',
                   'label_positions',
                   'label_bindings'],
 'site_chrome_reference': [],
 'button_variants': ['states', 'buttons', 'where', 'address'],
 'input_field': ['field', 'fields', 'field_steps', 'place_fields', 'states', 'where', 'address'],
 'live_box': ['layout',
              'variant',
              'keys',
              'key',
              'live_key',
              'part',
              'shared_key',
              'icons',
              'items_layout',
              'illustration',
              'columns',
              'columns_v',
              'size',
              'empty',
              'slots',
              'icon_position',
              'third_icon_position'],
 'live_embed': ['key', 'live_key', 'keys', 'leaves', 'leaf_asset']}

SPEC_FIELDS.update(SHOT_SPEC_FIELDS)
SPEC_FIELDS['document_mock'] += ['illustration', 'paper', 'render_text', 'size', 'align', 'motion_regions', 'motion_asset_sha256']
SPEC_FIELDS['button_variants'] += ['variant', 'size', 'columns', 'columns_v', 'items_layout']
SPEC_FIELDS['input_field'] += ['variant', 'size', 'columns', 'columns_v', 'items_layout', 'connector', 'illustration', 'icons']
